### ISSUE TITLE
BUG?: CORS request

### ISSUE THREAD

**Issue by perfectstrong** [Hypertopic/Porphyry#113]
When i try this piece of code to delete a viewpoint
````javascript
      hypertopic.get({ _id: this.props.viewpoint.id })
        .then(hypertopic.delete)
        .then(_ => this.props.onDeleteHandler())
        .catch(err => {
          console.error(err);
          window.alert("Erreur lors de la suppression");
        });
````
The navigateur blocks my request with this reasonning:

> Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://argos2.test.hypertopic.org/3da79aca2107ccd0c42d9d775853d130. Raison : échec du canal de pré-vérification des requêtes CORS.

Is this the default behavior of server or just i made mistakes somewhere?

P/s: the delete request on RESTClient of FF still works.

**Comment by perfectstrong** [comment]
Tracing requests gives me this:
> OPTIONS http://argos2.test.hypertopic.org/07006a36c72e007bd7510cd48038150e 405 (Method Not Allowed)

**Comment by perfectstrong** [comment]
When i tried with RESTClient
````
OPTIONS http://argos2.test.hypertopic.org/07006a36c72e007bd7510cd48038150e
````
I got 
````
{
  "error": "method_not_allowed",
  "reason": "Only DELETE,GET,HEAD,POST,PUT,COPY allowed"
}
````
It seems the server does not allow method OPTIONS.

**Comment by benel** [comment]
There's probably something to change in CouchDB settings... I'm on it...

**Comment by benel** [comment]
I asked StackOverflow: https://stackoverflow.com/questions/50914196

**Comment by benel** [comment]
Solution found on StackOverflow!

**Comment by benel** [comment]
@perfectstrong @Hypertopic/porphyry-pour-la-valorisation-des-vitraux 

Avez-vous lu ma réponse ?
J'y ai passé plusieurs heures et dans l'urgence (notamment dimanche, au cours d'une fête familiale), j'espère que ça vous a servi à quelque chose...

**Comment by perfectstrong** [comment]
@benel oui, j'ai lu. Le code de suppression via UI (#111) marche bien maintenant. Merci de votre travail.
