### ISSUE TITLE
See topics as "word cloud" in the portfolio view

### ISSUE THREAD

**Issue by aurorethomas** [Hypertopic/Porphyry#119]
## Content

Allow to see topics as "word cloud" based on the number of items linked to a topic in the portfolio view. 
Linked to issue #38 

---

## Checklist

- [ ] Scenarios
- [ ] Mock-up
- [ ] Automated tests
- [ ] Implementation

**Comment by benel** [comment]
Same as #80.

**Comment by aurorethomas** [comment]
Closed now. I'm sorry, I didn't saw it before.

**Comment by benel** [comment]
@aurorethomas No problem. My comment was only to document (to other people who could read your issue) why the issue was closed.
