### ISSUE TITLE
Moving topics by selecting them and dragging and dropping them

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#139]
Inspiration for the viewpoint editor is OmniOutliner (on macOS) or [CheckVist](https://checkvist.com/) (on the Web).

**Comment by franck-eyraud** [comment]
In fact, CheckVist does not use drag and drop, but Ctrl-Up, Ctrl-Down. Which one should we implement ?

**Comment by benel** [comment]
> In fact, CheckVist does not use drag and drop, but Ctrl-Up, Ctrl-Down. Which one should we implement ?

True. I did't notice that. Checkvist inspiration was more for the use of `TAB`, `SHIFT+TAB` and `ENTER` (that is common to OmniOutliner).

My personal inspiration is really OmniOutliner that I find both efficient and relatively intuitive. But I was looking for a similar product that can be tested by people who don't own a mac or an OmniOutliner license.

**Comment by benel** [comment]
> OmniOutliner that I find both efficient and relatively intuitive

Except from the active zone for rows selection that I find weird...

**Comment by franck-eyraud** [comment]
I see. The keyboard way is quite easy to do, following what has been done for `SHIFT+TAB` 61bdd57 and `ENTER` c3ebf55, so I can as well include it.
But let's also go also for drag'n drop. Do you have some example of such manipulation integrated with React.js ?

**Comment by benel** [comment]
> Do you have some example of such manipulation integrated with React.js ?http://react-dnd.github.io/react-dnd/about

**Comment by benel** [comment]
> Do you have some example of such manipulation integrated with React.js ?

Did you have a look at [React-DND](http://react-dnd.github.io/react-dnd/about). If I understand, it injects props to our own components.

**Comment by franck-eyraud** [comment]
Thank you. Yes, I saw it, but wasn't sure if it was a path to follow. So I will study it, as I don't immediately understand how it exactly "inject props" and how it will be easy to handle :smile:

**Comment by benel** [comment]
> I saw it, but wasn't sure if it was a path to follow. 

I'm not completely sure it is the best path to follow, but the approach seems to make sense.

**Comment by franck-eyraud** [comment]
I have up to now failed in having react-dnd work. 

But it seems possible to to Drag N Drop in React without it, as explained in [this article](https://codepen.io/frcodecamp/post/a-react-example-drag-and-drop-with-html5-api), using the fact that it is a HTML5 feature. I'll try to implement that, it should avoid the use of a quite heavy library.
