### ISSUE TITLE
UX coherence for editing attributes and (un)assigning topics

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#140]
We must choose EITHER "ready to go" text boxes OR edition state (if the second is chosen, the big button should be replaced with a small pen button).

Our aim is "content first" (not sure if light white boxes are more or less invasive than a pen button).

**Comment by franck-eyraud** [comment]
Is there any more recent suggestion about this ? I'm not sure that I have a preference between the two.
One thing I can notice though is that the "add attribute" feature #31 might be improved, indeed...

**Comment by benel** [comment]
@franck-eyraud Here is a quick mockup for adding topics and attributes in a coherent manner:

![img_0534](https://user-images.githubusercontent.com/597307/53436133-c3237980-39fa-11e9-8124-09bf9bd909e0.jpeg)

**Comment by benel** [comment]
@franck-eyraud Like in Facebook, the button could appear only when the carret enters the text box.
![img_0535](https://user-images.githubusercontent.com/597307/53436941-9ec89c80-39fc-11e9-97ba-619702e27fda.jpeg)

The interface is then "lighter".

**Comment by franck-eyraud** [comment]
OK, I see, it makes sense. 
Is it required to add (edit ?) attributes by typing key:value in one text box instead of 2 text boxes as now ?

**Comment by benel** [comment]
> Is it required to add (edit ?) attributes by typing key:value in one text box instead of 2 text boxes as now ?

I see a few pros in doing this:
- giving an understandable placeholder for the whole thing (you cannot imagine the horrors I saw in LaSuli v2's data for `attribute` and `value`),
- making understand that both comes together (for the same reason): for example, it is not the `attribute` (?) and the `value` (?) of an archeological artifact,
- it will make the job far more efficient: for example when I upload 100 pictures from the same location, I can copy and paste "spatial: Église Saint-Pierre-et-Saint-Paul, Géraudot".  For now I have to copy and paste the value and type "spatial" for the attribute 100 times.

> (edit ?)

For editing, It is less needed (since most of the time you edit either the value or the attribute). However, coherence is better for both UX and code.

**Comment by franck-eyraud** [comment]
OK, thanks. I just pushed a [new branch](https://github.com/franck-eyraud/Porphyry/tree/set_attributes) , let me know what you think.

**Comment by benel** [comment]
> OK, thanks. I just pushed a new branch , let me know what you think.

Thank you Franck!

I realise I forgot this branch, because it wasn't in the PR list :P 

There are very good things in this branch:
- the button that appears when it gets the focus,
- and that goes green when data are valid,
- the cancelation with ESC,
- the general feeling.

Small issues:
- small incoherence in attribute editing format rules (test it with `FOO : BAR`, i.e. with extra spaces) between:
  1. the button going green or not, 
  2. the ability to add it with the button, 
  3. the ability to add it with ENTER.
- the position of the attribute remove/edit  buttons (why between the attribute key and attribute value?)
- the text box is a bit short to read `Ajouter un attribut et une valeur...`
- the attribute edit mode (with both the original and the being modified attribute) seems very weird to me...  The most common way would be to edit in place. Another way would be to hide it from the list and have it only in the edition box...

**Comment by franck-eyraud** [comment]
In fact, the corresponding pull request it this one #151 but it seems indeed that github doesn't show it...

OK, I will have a look at these comments, thank you.

**Comment by franck-eyraud** [comment]
OK, I pushed some modifications in #151.

> small incoherence in attribute editing format rules (test it with FOO : BAR, i.e. with extra spaces) between: 

I don't see what is wrong here, I might miss something.

> the attribute edit mode (with both the original and the being modified attribute) seems very weird to me... The most common way would be to edit in place. Another way would be to hide it from the list and have it only in the edition box...

OK, I implemented the edit in place way 1abe71e, by using a new component Attribute. Let me know if it seems OK. I have problem with the width changing when switching from edit and non edit mode, couldn't find the correct CSS rules to have the input control having the same width than normal div...
