### ISSUE TITLE
Add a resource to an item (as a link)

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#143]

**Comment by benel** [comment]
Can be emulated by posting a comment with a link in it (see feature #47).

**Comment by benel** [comment]
Because a resource is just an attribute with an HTTP-URI value, this could done by adding an attribute. However, for now, URIs are truncated after `http`.

**Comment by neumeiej** [comment]
It is possible to find a workaround of the problem. Create an attribute, give it a random value, than modify it to put the link.

<img width="471" alt="Capture d’écran 2020-03-12 à 10 20 04" src="https://user-images.githubusercontent.com/33666392/76506210-11ab8680-644b-11ea-9b23-6e26925f834d.png">

**Comment by Ciyax** [comment]
Dans le cadre du projet Studying Abroad, l'ajout d'une ressource sous forme d'un lien représente un enjeu important étant donné qu'elle permettrait d'accéder directement à la page externe dédiée d'une UE, ou au site d'une Université ou d'une formation qu'elle propose.

**Comment by ghost** [comment]
Dans le cadre de Collectives' stories, nous voulons que les utilisateurs, conteurs d'expériences, aient la possibilité de donner un lien pour en savoir plus sur leur expérience, leur activité, leur profil, leur association, etc...

**Comment by EmileReyUL** [comment]
Approche par compétences de la formation : Permettrait de renvoyer vers des ressources externes (page Moodle, sites d'informations sur les technologies utilisées, etc)

**Comment by benel** [comment]
Deployed.
