### ISSUE TITLE
Autocompletion matching should start on each word

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#149]
Examples:

- `pierre` should match `Simon / Pierre`,
- `mages` should match `Visite des mages`,
- `Voici l'h` should match `"Voici l'homme"` (with quotes),
-  `oreille` should match "Guérison de l'oreille du serviteur du grand prêtre".

---
### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy
### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

**Comment by Damien71** [comment]
Studying abroad : self-completion is very interesting for a quick search. For our project, it also allows to find topics according to keywords, for example, when typing management, suggestions can be the UEs that contain this keyword.

**Comment by moonkeys** [comment]
Young Artist: 
Avec les nombreux mots clés qui sont utilisés pour qualifier une image, cette fonctionnalité est importante pour gagner du temps mais également éviter de faire des fautes de frappe.

**Comment by benel** [comment]
> Avec les nombreux mots clés qui sont utilisés pour qualifier une image

@moonkeys Vous prévoyez d'avoir à peu près combien de mots-clefs dans votre projet ?

**Comment by moonkeys** [comment]
@benel Nous ne savons pas encore exactement, c'est encore trop flou.

**Comment by benel** [comment]
@moonkeys J'aurais tendance à penser que votre projet est celui où il y aura le moins de catégories... Mais je me trompe peut-être. À creuser...

**Comment by moonkeys** [comment]
@benel c'est pour cela que nous avons mis ce ticket dans les moins important.

**Comment by benel** [comment]
Deployed.
