### ISSUE TITLE
Search for a topic and select it

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#154]
Type the name of a topic in a search bar with autocompletion. 
On validation, the topic is selected.

## Workaround

Use CTRL+F (however it doesn't work if one of the topic ancestor is collapsed).

**Comment by benel** [comment]
@gumn

**Comment by garnier5** [comment]
For "study abroad" project, it would be easier to quickly find out what you are looking for when you are on the platform.

**Comment by benel** [comment]
@garnier5 OK. Maybe an example would be good, to compare browsing and searching a topic.

**Comment by garnier5** [comment]
@benel If we wish to search for ISI items, a university that we like more than another, or a country in which we wish to stay.

**Comment by hebertquentin** [comment]
Pour Archéologie grecque, il serait bien de pouvoir sélectionner un topic après simple recherche. Cela simplifierait la navigation et multiplierait le nombre de chemins pour accéder à une ressource.

**Comment by Rinkichi75** [comment]
To look for an item with a specific topic such as agriculture.

**Comment by benel** [comment]
@Rinkichi75 As I wrote to @garnier5, because you can already do that by browsing the viewpoint you should explain why it would be better by searching.

**Comment by Rinkichi75** [comment]
Projet Partage de récit d'expérience
cela permet de faire une recherche plus rapide. Exemple: Bio-Équitable

**Comment by benel** [comment]
@Rinkichi75 C'est vrai. Mais contrairement à la navigation, il faut déjà savoir ce que l'on cherche. Autrement dit, ça fonctionne bien si les termes sont assez connus ou courants.

**Comment by EmileReyUL** [comment]
Approche par compétences de la formation : Permettrait de sélectionner toutes les UEs d'un certain type (CS, TM, ME, etc)

**Comment by Damien71** [comment]
Mock-up attached for the Studying Abroad project :

![image](https://user-images.githubusercontent.com/50024514/78921455-3835ff00-7a95-11ea-9f3f-9d8b6657b925.png)

![image](https://user-images.githubusercontent.com/50024514/78921479-42f09400-7a95-11ea-8d9d-ddeb46b990b5.png)

![image](https://user-images.githubusercontent.com/50024514/78921513-4edc5600-7a95-11ea-9cc5-8994d06fd304.png)

**Comment by benel** [comment]
Deployed.
