### ISSUE TITLE
Reuse an existing attribute or value

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#156]
#### Which user action should be enabled (or restricted)? For who?

Autocompletion based on the data of portfolio corpora.

#### Additional details (solutions you think about, or workarounds you tried)

Please note that, on Chrome, "attribute:values" used on the computer are already suggested.

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy

#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

### Phase 3
- [x] Screencast

**Comment by benel** [comment]
As reported by @gumn, this could be useful for the Cité du vitrail.

**Comment by UndersCoco** [comment]
It would be interesting for our project "Studying abroad" to have an autocompletion of the attributes, such as the teacher, course name, semester...

**Comment by benel** [comment]
@UndersCoco I see your point for teacher, and semester... But for course name? Is it a good thing to get all the existing course names when you create a new course?

**Comment by UndersCoco** [comment]
Yes, you're right, it's not a interesting thing for the course name.

**Comment by FirielEinor** [comment]
Visite sur site de vitraux :
Cette fonctionnalité peut être intéressante pour la période des vitraux, pour le contributeur, pour l'auteur si certains auteurs ont fait beaucoup de vitraux

**Comment by benel** [comment]
@FirielEinor Soyez bien précis... Parlez-vous de l'auteur et de la date des photographies ou des vitraux ?

Si vous parlez des vitraux, ce ne sont pas des attributs mais des catégories. Et la bonne nouvelle c'est que pour les catégories la fonctionnalité existe déjà.

Par contre, je vois bien l'intérêt pour les attributs. Regardez dans les données, vous avez la chance d'être le seul groupe à les avoir déjà.

**Comment by CarlaRGanier** [comment]
Scénarii du ticket réalisé : 

```gherkin
Scénario 1 : En créant un attribut et une valeur inexistants

Soit l’utilisateur “luce” est connecté 
Et l’utilisateur souhaite éditer l’item “KER 0434”
Quand l’utilisateur renseigne un nouvel attribut en saisissant “spécialité” et la valeur “honorifique”
Alors l’attribut "spécialité" et la valeur ”honorifique” sont créés dans l’item “KER 0434” 
Mais  l’utilisateur ne choisit pas l’attribut "spatial" proposé
Et l’utilisateur ne choisit pas l’attribut “spécificité” proposé


Scénario 2 : En renseignant un attribut et une valeur inexistante

Soit l’utilisateur “luce” est connecté 
Et l’utilisateur souhaite éditer l’item “KER 0434”
Quand l’utilisateur renseigne l’attribut "spatial" préexistant avec une nouvelle valeur “Tombe 1999, Nécropole de l’Ouest de l’Eridanos, Kerameikos" 
Alors l’attribut "spatial" et la valeur “Tombe 1999, Nécropole de l’Ouest de l’Eridanos, Kerameikos" sont créés dans l’item “KER 0434” 



Scénario 3 :  En renseignant un attribut et une valeur existants

Soit l’utilisateur “luce” est connecté 
Et l’utilisateur souhaite éditer l’item “KER 0434”
Quand l’utilisateur renseigne l’attribut "spatial" avec  une nouvelle valeur en saisissant les lettres “To”
Alors l’utilisateur choisit la valeur "Tombe 4, Nécropole au Nord de l’Eridanos, Kerameikos" proposé parmi les autres valeurs existantes
Et l’attribut "spatial" et la valeur "Tombe 4, Nécropole au Nord de l’Eridanos, Kerameikos" sont créés dans l’item “KER 0434” 
```

Co-éditeur : Lucas Da Silva

**Comment by LucasDaSilva95** [comment]
Stratégie d'implémentation :
Le composant React a modifié est le composant Item. 
Sa méthode _setAttributes sera probablement à modifier. 
Les données, à savoir la liste des attributs ainsi que les valeurs utilisées par les items sont à priori déjà chargées.
Une bibliothèque pertinente pourrait être le module React Autocomplete qui fournit un composant d'autocomplete déjà fait à partir d'un tableau des éléments à afficher. (https://www.npmjs.com/package/react-autocomplete) || Regarder pour utiliser le composant inputSuggestions déjà présent dans le projet.
Aucun service externe ne devra être utilisé.

**Comment by CarlaRGanier** [comment]
### **Maquettes correspondant au ticket** 


![159287324-23c0eff7-cca5-4a1d-a667-6807c4b1536d](https://user-images.githubusercontent.com/71191157/165897557-49f3dd37-b488-4c33-9ad3-5a36be16d6cf.jpeg)
![159287366-3dee62b1-6e99-41f4-9c04-08f9b829207d](https://user-images.githubusercontent.com/71191157/165897566-defe251e-af9a-4638-bffb-9085ae68be9f.jpeg)

**Comment by benel** [comment]
### Point d'avancement du 29/04

- Stratégie de développement : tester dans du  code à part le changement de "candidats"
- Scénario et tests de recette : quand le ticket sera terminé tirer des enseignements de la réécriture assez profonde des scénarios.
- Tests de recette : pas sûr que ça prenne en compte les différentes étapes de saisie et de sélection.

**Comment by CarlaRGanier** [comment]
### Démontration du ticket #156

Après avoir réalisé l'implémentation de la fonctionnalité de réutilisation d'un attribut préexistant, voici la vidéo de démonstration la présentant. L'utilisateur doit se situer sur une page d'attribut pour accéder à la fonctionnalité.
En fonction des lettres rentrées dans l'input, un/des attribut(s) et valeur(s) sont proposés en auto-complétion.


https://user-images.githubusercontent.com/71191157/175056765-634fb046-d617-44c7-87df-b3753777621f.mp4
