### ISSUE TITLE
Thumbnails should have the same height

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#157]
While it is fine on Firefox and Safari, it is broken on Chrome.

### On Firefox
<img width="1392" alt="On Firefox" src="https://user-images.githubusercontent.com/597307/54218964-d5b7ab80-44ee-11e9-9c58-42afe4d11fe7.png">

### On Safari
<img width="1392" alt="Capture d’écran 2019-03-12 à 17 42 00" src="https://user-images.githubusercontent.com/597307/54219085-131c3900-44ef-11e9-96e7-3a5b38e6cef7.png">

### On Chrome
<img width="1392" alt="Capture d’écran 2019-03-12 à 17 46 21" src="https://user-images.githubusercontent.com/597307/54219122-23341880-44ef-11e9-98ce-6f0d6bdf25a3.png">

**Comment by MaximeD89** [comment]
**Projet** : _Visite sur site de vitraux_

Traiter ce point serait appréciable afin de rendre l'expérience et la navigation des utilisateurs plus agréable. Notamment pour ceux qui ne disposent ou n'utilisent que de Google Chrome.

**Comment by benel** [comment]
Deployed.
