### ISSUE TITLE
Select items according to a given attribute

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#158]
Alternative to #38. 

---
### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

**Comment by RobinLallier** [comment]
À l'attention du groupe des dessins:
On s'est engagés à faire une recherche par attributs auprès de nos clients. Si vous voulez la faire pas de soucis, regardez quand même la maquette qu'on a réalisée

![Fonction recherche - V2 - inspirée de Mac](https://user-images.githubusercontent.com/33777989/57967000-9cba0e00-7959-11e9-9fc1-c96889835518.png)

En parallèle, il y avait la possibilité de cliquer sur un attribut depuis la page d'un item pour obtenir une recherche selon cet attribut (exemple: si l'on clique sur l'attribut spatial d'un item, on revient sur la page portfolio et on ne voit que les items ayant le même spatial). Ça restera possible d'implémenter ça dans un autre ticket

**Comment by saad-lozzi** [comment]
(Scénario après modification)

Fonctionnalité: Sélectionner des éléments en fonction d'un attribut donné

Contexte:

  Soit "dessins" le portfolio ouvert

Scénario: Recherche par attribut Année


  Quand on ajoute un attribut de recherche "Année" avec pour valeur "2012"
  Alors les dessins "2012_18-25_01_PER_R_C" et "2012_2586_6:9_SYR" sont parmi les dessins affichés

Scénario: Recherche par attributs Année et Âge


  Quand on ajoute un attribut de recherche "Année" avec pour valeur "2012" et un attribut de recherche "Âge" avec pour valeur "10:13"
  Alors les dessins "2012_2595_10:13_SYR" et "2012_2596_10:13_SYR" sont parmi les dessins affichés

**Comment by saad-lozzi** [comment]
Test : 
require 'capybara/cucumber'
require 'selenium/webdriver'

Capybara.run_server = false
Capybara.default_driver = :selenium_chrome_headless
Capybara.app_host = "http://localhost:3000"
Capybara.default_max_wait_time = 10
Capybara.ignore_hidden_elements = false



Soit("{string} le portfolio ouvert") do |portfolio|
  visit "/"
end


Quand("on ajoute un attribut de recherche {string} avec pour valeur {string}") do |attribut, valeur|
  fill_in('Attribut1', with: attribut)
  fill_in('Valeur1', with: valeur)
  click_button('Rechercher')
end

Quand("on ajoute un attribut de recherche {string} avec pour valeur {string} et un attribut de recherche {string} avec pour valeur {string}") do |attribut1, attribut2, valeur1, valeur2|
    fill_in('Attribut1', with: attribut1)
    fill_in('Valeur1', with: valeur1)
    find_button(class: ['btn', 'btn-light', 'creationButton']).click
    fill_in('Attribut2', with: attribut2)
    fill_in('Valeur2', with: valeur2)
    click_button('Rechercher')
  end

# Outcomes

Alors("Alors les dessins {string} et {string} sont parmi les dessins affichés affichés") do |valeur1, valeur2|
    expect(page).to have_content(valeur1)
    expect(page).to have_content(valeur2)
end

**Comment by saad-lozzi** [comment]
On a choisi la maquette du groupe vitraux.
Le scénario : 
#language: fr

Fonctionnalité: Sélectionner des éléments en fonction d'un attribut donné

Contexte:

Soit "dessins" le portfolio ouvert

Scénario: Recherche par attribut 

Quand on met "2012" dans la barre de recherche
Alors les dessins "2012_18-25_01_PER_R_C" et "2012_2586_6:9_SYR" sont parmi les dessins affichés

Le test (à ajouter dans portfolio.rb): 

Quand("on met {string} dans la barre de recherche") do |value|
  fill_in('Rechercher...', with: value).native.send_keys(:return)
end

Alors("Alors les dessins {string} et {string} sont parmi les dessins affichés affichés") do |valeur1, valeur2|
  expect(page).to have_content(valeur1)
  expect(page).to have_content(valeur2)
end

**Comment by saad-lozzi** [comment]
Voici le test final réaliser par moi et Ayoub : 
scénario : 
#language: fr

Fonctionnalité: Sélectionner des éléments en fonction d'un attribut donné

Contexte:

Soit "dessins" le portfolio ouvert

Scénario: Recherche par attribut

  Quand on met "1994" dans la barre de recherche et on clique sur "1994_6-9_11_ROM_R_C"
  Alors le dessin "1994_6-9_11_ROM_R_C" est affiché

Script capybara : 

Quand("on met {string} dans la barre de recherche et on clique sur {string}") do |value1, value2|
    #fill_in "Rechercher", with: 'value1', visible: false

    #within("form-control#Rechercher") do
    #fill_in "Rechercher", :with => @visitor[:value2]
    find('#Rechercher', visible: true).set value1
    find('#link', visible: true).click
    #click_on(value2)
#end

end

Alors("le dessin {string} est affiché") do |valeur|
  expect(page).to have_content valeur
end

Resultat de test : 

![test valide](https://user-images.githubusercontent.com/43405059/59699916-ac47a380-91f2-11e9-9de8-5bff5e75d1f6.png)

**Comment by JoyCJay** [comment]
Bonjour,
Pour la suite de l'implémentation de cette issue. J'arrive à filtrer par des attributs structurés simple (par exemple spatiel), mais il existe encore des attributs structurés complexes, par example "id" ([{...},{...},{...}...]).
Mais il semble que steatelite et agorae sont en panne tout à l'heure.
De plus je reviens à Shanghai à demain. Donc, je vais continuer cette issue quelque jour après.

Cordialement et bonne vacances : )
Chengjie ZHANG

**Comment by gabyseg** [comment]
Approche par compétences de la formation : cela pourrait permettre de rechercher les ues ayant certaines compétences, un certain nombre d'heures ou autres…

**Comment by benel** [comment]
@gabyseg Les compétences, ce serait plutôt des catégories, donc on a déjà la fonctionnalité. Il faudrait trouver d'autres exemples pertinents...

**Comment by melaniehoneychurch** [comment]
Pour le projet des vitraux cette fonctionnalité est intéressante pour sélectionner des vitraux selon un attribut donnés

**Comment by benel** [comment]
> pour sélectionner des vitraux selon un attribut donné

@melaniehoneychurch Par exemple ?

**Comment by ThomasLORIOT** [comment]
Livrable effectué :

![80081552-64508600-8553-11ea-8357-2250ae693880](https://user-images.githubusercontent.com/33529204/81264740-42223200-9042-11ea-947f-67024bf709cf.png)
![80081568-6ca8c100-8553-11ea-9ae1-78cdbabd4f10](https://user-images.githubusercontent.com/33529204/81264736-3cc4e780-9042-11ea-8b40-d7dc2f0da00c.png)

**Comment by benel** [comment]
@ThomasLORIOT Donc votre proposition, c'est d'afficher : 

- les attributs comme si c'était des points de vue,
- les valeurs comme si c'était des catégories de premier niveau.

C'est ça ?

**Comment by benel** [comment]
@ThomasLORIOT Il semblerait que votre maquette décrive d'autres fonctionnalités nouvelles : 

- une sorte de mosaïque à la place de la "planche contact" (grille de vignettes),
- une pagination des résultats.

Par contre, je ne vois pas la manière dont s'afficherait la sélection. Ce qui est embêtant puisque pour le coup, cela fait partie de la fonctionnalité...

**Comment by benel** [comment]
> Par contre, je ne vois pas la manière dont s'afficherait la sélection. 

@ThomasLORIOT Je parle de cette zone-ci : 
<img width="623" alt="Capture d’écran 2020-05-07 à 09 21 03" src="https://user-images.githubusercontent.com/597307/81265881-1dc75500-9044-11ea-8eb6-4177ff36cae9.png">

**Comment by benel** [comment]
> Donc votre proposition, c'est d'afficher :
les attributs comme si c'était des points de vue,
les valeurs comme si c'était des catégories de premier niveau.

@ThomasLORIOT Autrement dit, est-ce que ça ne risque pas d'apporter de la confusion sachant que la différence entre les deux notions est constitutive de l'outil, qu'on la retrouve dans un autre écran (celui de l'item) et que les fonctionnalités associées, même si elles se ressemblent parfois, sont quand même assez différentes ?

**Comment by Kodlah** [comment]
Nous avons pris vos informations en considération et le binôme @ThomasLORIOT / @JoJOes  est en train de modifier le livrable en conséquence.

**Comment by benel** [comment]
@ThomasLORIOT @JoJOes Au cas où, je vous rappelle les différences entre les deux : 

Pour un item donné,  les attributs sont consensuels (ex : dans votre cas, c'est l'auteur du dessin qui a déclaré qu'il habitait par exemple au Burkina, les autres n'ont pas à le contredire), les catégories elles dépendent du point de vue (ce sont les psychologues qui vont interpréter la représentation des animaux, le jury qui va décider que le dessin est digne d'être lauréat). Etc.

Les attributs sont composés d'un nom et d'une valeur. Ils sont définis au niveau d'un item (mais l'un comme l'autre peuvent être réutilisés dans un autre item). Au contraire les catégories sont structurées de manière arborescente. Cette arborescence des catégories est gérée indépendamment des items qui les utilisent.

**Comment by JoJOes** [comment]
Merci pour vos retours ! Nous avons modifié la maquette en prenant en compte les améliorations.
Voici les nouvelles maquettes:

![Maquette1](https://user-images.githubusercontent.com/9683339/81270828-95e54900-904b-11ea-8aff-e8960e4efccf.png)
![Maquette2](https://user-images.githubusercontent.com/9683339/81271061-e3fa4c80-904b-11ea-8604-2925405cf974.png)

**Comment by benel** [comment]
> Nous avons modifié la maquette en prenant en compte les améliorations.

@JoJOes Donc là ce que je vois, c'est ce qui existe déjà : la sélection à partir d'une catégorie (`3-5 ans`) issue d'un point de vue (celui des psychologues). 
Ce qui me manque c'est la manière dont on sélectionne une valeur d'attribut ce qui est précisément le sujet de ce ticket (ex : `spatial: Géorgie` ou `created:2019`). 

Note : En passant ce serait plutôt `3-6 ans` (appelé aussi `Stade de la conviction`) pour la psychologie du développement (cf. [Wikipédia](https://fr.wikipedia.org/wiki/Stades_du_développement_psychosocial#Conviction_:_Initiative_versus_Culpabilité_(3-6_ans))), mais bon...

**Comment by benel** [comment]
> Ce qui me manque c'est la manière dont on sélectionne une valeur d'attribut ce qui est précisément le sujet de ce ticket (ex : `spatial: Géorgie` ou `created:2019`). 

Pour être sûr de me faire comprendre, ce que l'on attend de votre maquette ce sont deux choses principalement :   

- comment sont affichés les attributs et les valeurs et comment j'en sélectionne une,
- comment cette valeur sélectionnée s'affiche dans le statut de la sélection d'une manière compréhensible.

**Comment by ThomasLORIOT** [comment]
Merci pour votre réactivité, nous avons fusionné nos deux maquettes en les corrigeant : 

La partie en dessous "Point de vue" permet de sélectionner des attributs, sans empêcher sélectionner des points de vue.

![80081552-64508600-8553-11ea-8357-2250ae693880](https://user-images.githubusercontent.com/33529204/81274481-a1873e80-9050-11ea-9436-ec2e2241caf7.png)

**Comment by Kodlah** [comment]
Pour l'équipe Graine d'artistes : 

- Le binôme @ThomasLORIOT et @JoJOes s'occuperont du livrable Scénario de ce ticket (#158).

- Le binôme @Kodlah et @MrGabigoo s'occuperont du livrable Stratégie d'implémentation de ce ticket (#158).

**Comment by VinceFrancois** [comment]
Groupe : Archéologie grecque (@VinceFrancois et @Marshlyin )

Voici notre maquette pour le ticket

![image](https://user-images.githubusercontent.com/45287678/81275259-b31d1600-9051-11ea-9221-da04934b9d32.png)

Cliquer sur une valeur d'attribut permet de la retirer du filtre.
Cliquer sur un opérateur permet de le modifier.

Concernant l'ajout d'un filtre, il est possible de : 
- Cliquer sur un point de vue dans la liste de gauche, il est alors ajouté et surligné en rouge dans la liste des points de vue
- Ajouter un attribut avec le bouton "+", un pop-up demande alors l'attribut (via une liste déroulante) et la valeur (via l'autocomplétion) sur lequels filter, ainsi que l'opération

**Comment by benel** [comment]
> La partie en dessous "Point de vue" permet de sélectionner des attributs, sans empêcher sélectionner des points de vue.

@ThomasLORIOT Oui, comme cela il est clair qu'il y a des attributs **et** des point de vue...

Et il me semble effectivement que c'est une bonne idée d'afficher dans la barre de la sélection  le **nom de l'attribut en préfixe**. C'est beaucoup plus clair qu'avec la valeur seule.

Deux petits points d'amélioration : 
- les exemples de catégorie (je vous ai suggéré les stades de développement indiqués dans Wikipédia : `stade de l'espoir`, `stade de la volonté`, `stade de la conviction`, etc.) : on comprendra mieux pourquoi c'est dans le point de vue "Psychologie du développement",
- regardez la position relative des attributs et des points de vue dans la page de l'item, ce serait peut-être bien de chercher une plus grande cohérence.

**Comment by benel** [comment]
@VinceFrancois 

Vous proposez de postfixer les valeurs d'attributs avec les noms d'attributs. Pourquoi pas...

Mais aussi les catégories avec leur catégorie mère. Ce point serait une autre fonctionnalité à planifier à part (puisque ce n'est pas indispensable pour le ticket dont on est en train de parler).

Vous proposez une fenêtre surgissante pour choisir l'attribut : 
- vérifiez que cela est cohérent avec ce qui existe déjà dans l'interface,
- comparez le nombre de clics nécessaires par rapport à la proposition de l'autre équipe (graines d'artistes),
- demandez vous ce que cela donnera sur un terminal mobile de petite taille.

**Comment by benel** [comment]
Aux quatre groupes qui travaillent actuellement sur ce ticket : 
- nous avons deux propositions de ce matin,
- une de l'an dernier.

Elles sont assez représentatives de ce que l'on pouvait imaginer comme solutions.

Je vous invite : 
- à discuter des avantages et inconvénients de chacune, 
- proposer peut-être des petites variantes,
- faire valoir l'intérêt de vos parties prenantes (peut-être ont-ils des spécificités),
- trouver le meilleur compromis avant la semaine prochaine.

**Comment by seguragu** [comment]
Suite à la réunion avec @Hypertopic/visite-sur-site-de-vitraux , @Morillev et moi avons corrigé la maquette précédente pour la feature #158 pour qu'elle soit fidèle au site Porphyry.

Pour plus de lisibilité, les résultats liés aux points de vue et ceux liés aux attributs sont séparés.

![correction maquette 158](https://user-images.githubusercontent.com/56882958/81298273-d73e1e80-9074-11ea-9034-53dd18720783.jpg)

**Comment by line-tan** [comment]
Pour l'équipe Approche par compétences de la formation :

Le binôme @ValentinLouerat  et @EmileReyUL  s'occuperont du livrable Stratégie d'implémentation de ce ticket (#158).

Le binôme @line-tan  et @LeonVongphanith  s'occuperont du livrable Scénario de ce ticket (#158).

**Comment by TheStarTom** [comment]
euh oups, j'ai cliqué sur le mauvais bouton

**Comment by benel** [comment]
> euh oups, j'ai cliqué sur le mauvais bouton

Ça arrive. Vous pouvez le réouvrir.

**Comment by Acendy** [comment]
Groupe Approche par compétences de la formation:
Voici les maquettes pour ce ticket : 

![image](https://user-images.githubusercontent.com/39732027/81311444-af0aeb80-9085-11ea-876e-82157c91f074.png)
![image](https://user-images.githubusercontent.com/39732027/81311466-b7fbbd00-9085-11ea-97cc-4bdce684b671.png)

**Comment by JoJOes** [comment]
**Fonctionnalité**: Sélectionner des éléments en fonction d'un attribut donné

**Contexte**: Soit "dessins" le portfolio ouvert

**Scénario**: Recherche par attribut "Created"

Quand on ajoute un attribut de recherche "Created" avec pour valeur "1996"
Et que des dessins existent avec ce critère de recherche
Alors les dessins "1996_14-17_13_RUS_R_C" et "1996_6-9_08_HUN_R_C" sont parmi les dessins affichés

**Comment by hebertquentin** [comment]
> Vous proposez de postfixer les valeurs d'attributs avec les noms d'attributs. Pourquoi pas...
> 
> Mais aussi les catégories avec leur catégorie mère. Ce point serait une autre fonctionnalité à planifier à part (puisque ce n'est pas indispensable pour le ticket dont on est en train de parler).

Bonjour Monsieur @benel, nous nous demandions ce que vous entendiez par "postfixer" et les catégories/catégories mères. Pourriez-vous nous éclairer svp ?

**Comment by benel** [comment]
> Bonjour Monsieur @benel, nous nous demandions ce que vous entendiez par "postfixer" et les catégories/catégories mères. Pourriez-vous nous éclairer svp ?

Ah désolé. C'est du [vocabulaire informatico-mathématique](https://fr.wikipedia.org/wiki/Notations_infixée,_préfixée,_polonaise_et_postfixée#Notation_postfixée). Par exemple pour additionner 1 et 4 on peut l'écrire de manière : 

- infixée : `1 + 4` (comme vous l'avez appris à l'école),
- préfixée : `+ 1 4` (comme dans Lisp),
- postfixée : `1 4 +` (comme sur les calculatrices HP).

**Comment by benel** [comment]
Dans notre cas, pour indiquer la catégorie mère, ça donne par exemple : 

- en notation préfixée : `Catégorie mère > Catégorie`, ou `Catégorie mère / Catégorie` (courant dans les fils d'Ariane et les systèmes de fichiers)
- en notation postfixée : `Catégorie (Catégorie mère)` ou `Catégorie – Catégorie mère` (utilisé par exemple dans certaines interfaces de macOS).

**Comment by benel** [comment]
Pour l'instant, c'est la proposition de @seguragu de l'équipe vitraux qui a le moins d'impact sur l'interface (c'est important pour "l'apprenabilité") et le code (ça vous donne moins de travail !).

Si on voulait la simplifier encore, on pourrait enlever dans la liste de suggestion la distinction entre attributs et catégories. Je doute que les usagers s'en plaignent : 

- soit ils viennent de découvrir le site et ils ne connaissent pas la différence, 
- soit ils savent très bien ce qu'ils cherchent et du coup ça ne leur apporte pas grand chose.

**Comment by FirielEinor** [comment]
Fonctionnalité : Sélectionner un item selon un attribut donné

Scénario :

Soit "ABT" est affiché
Et "AXN 000" est affiché
Quand l'attribut "Spatial : Église Saint-Loup, Auxon" est sélectionné
Alors "ABT" n'est plus affiché
Et "AXN 000" est affiché

**Comment by seguragu** [comment]
> Suite à la réunion avec @Hypertopic/visite-sur-site-de-vitraux , @Morillev et moi avons corrigé la maquette précédente pour la feature #158 pour qu'elle soit fidèle au site Porphyry.
> 
> Pour plus de lisibilité, les résultats liés aux points de vue et ceux liés aux attributs sont séparés.
> 
> ![correction maquette 158](https://user-images.githubusercontent.com/56882958/81298273-d73e1e80-9074-11ea-9034-53dd18720783.jpg)

La dernière version de la maquette #158 : 

On tape 'Cat' dans la barre de recherche :
![correction maquette 158-1](https://user-images.githubusercontent.com/56882958/81931437-69e93b00-95ea-11ea-99ff-69f33c2b758f.jpg)

Résultat après avoir cliqué sur le résultat 'Spatial : Cathédrale Notre-Dame, Paris'
![correction maquette 158-2](https://user-images.githubusercontent.com/56882958/81932186-aa958400-95eb-11ea-95c4-e4363b2a0b2b.jpg)

**Comment by line-tan** [comment]
Fonctionnalité : Sélectionner des éléments en fonction d'un attribut donné
Scénario : recherche par attribut "name"
Soit "qua" le texte inscrit dans la barre de recherche 
Quand l'utilisateur clique sur "name > qualité logiciel"
Alors l'item de l'UE "Qualité logiciel" est affichée
Quand l'utilisateur clique sur l'item de l'UE "Qualité logiciel"
Alors les information sur l'UE sont affichées.

**Comment by Acendy** [comment]
> Fonctionnalité : Sélectionner des éléments en fonction d'un attribut donné
> Scénario : recherche par attribut "name"
> Soit "qua" le texte inscrit dans la barre de recherche
> Quand l'utilisateur clique sur "name > qualité logiciel"
> Alors l'item de l'UE "Qualité logiciel" est affichée
> Quand l'utilisateur clique sur l'item de l'UE "Qualité logiciel"
> Alors les information sur l'UE sont affichées.

![image](https://user-images.githubusercontent.com/39732027/81941253-d8cd9080-95f8-11ea-96b1-ad3c1274a98a.png)

![image](https://user-images.githubusercontent.com/39732027/81941300-e71bac80-95f8-11ea-804d-66ebe74eaead.png)

![image](https://user-images.githubusercontent.com/39732027/81941332-f1d64180-95f8-11ea-9721-079d5a366f6b.png)

**Comment by ValentinLouerat** [comment]
Pour ce qui est de la stratégie d'implémentation de notre solution avec séparation des deux searchbar, nous la détaillons ici en l'attente d'une négociation pour savoir quelle solution sera retenue. Ce n'est sûrement pas la meilleure solution mais elle nous semble plus facile à développer en terme de complexité de programmation.

- Quelle partie du code sera impactée (classes, méthodes) ?

Les classes searchbar.jsx et portfolio.jsx seront impactées. Searchbar correspond à la barre de recherche qui pour le moment ne recherche que parmi les viewpoints. Portfolio gère l'affichage de la page de listing de PorphyrY

On peut peut voir le lien entre les deux dans Portfolio.jsx

![image](https://user-images.githubusercontent.com/55994851/81941774-8c368500-95f9-11ea-9319-08d8022aaa00.png)

Avons-nous oublié quelque chose ?

- Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?

Pas de souci d’algo à priori, nous pouvons nous baser sur ce qui a déjà été fait pour la première searchbar.

- Les données dont vous avez besoin sont-elles déjà chargées par la page ?

Nous pensons que oui, portfolio contient déjà les données dont on a besoin à savoir la liste de tous les items en plus des viewpoints. Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ?

![image](https://user-images.githubusercontent.com/55994851/81941888-acfeda80-95f9-11ea-8d7e-cf3871c489db.png)

En effet, dans Item.jsx qui décrit la classe Item, il y a un getter pour les items :

![image](https://user-images.githubusercontent.com/55994851/81941951-c99b1280-95f9-11ea-946d-c82b40c85a62.png)

En plus il faudrait assembler toutes les données en un tableau et enlever tous les doublons

- Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?

Le comportement de notre fonctionnalité se rapproche beaucoup de la searchbar, nous ne pensons pas avoir besoin de quoi que ce soit de plus que ce qui est utilisé pour la première search bar.

- Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?

Non.

Rédigé avec @EmileReyUL

**Comment by ShovelBear** [comment]
Avec @seguragu, nous avons réfléchi à une stratégie d'implémentation et en sommes arrivé aux conclusions suivantes :

- Quelle partie du code sera impactée (classes, méthodes) ?

Après inspections du code et de la page web avec l'extension REACT, nous pensons qu'il faudra modifier les classes Portfolio.jsx, SearchBar.jsx et InputWithSuggestions.jsx et notamment la méthode _fetchAll() de Portfolio.jsx car elles sont reliées les unes aux autres et semblent gérer les systèmes d'affichage et de tri des suggestions automatiques (mise en évidence du transfert des informations entre les classes).

![Stratégie](https://user-images.githubusercontent.com/33767746/81950672-885c3000-9604-11ea-915c-fd2a13b9ae17.png)

-Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?

Dans la théorie, il suffira de trouver un moyen d'ajouter les attributs aux données déjà triées par l'algorithme, il ne devrait donc pas y avoir de problème particulier à ce niveau là.

- Les données dont vous avez besoin sont-elles déjà chargées par la page ? 

Comme montré précédemment, nous pensons que les données sont déjà chargées sur la page et sont transmises entre les classes, cependant, il faudra faire en sorte que les attributs restent avec ces données et ne soit pas enlevés par les filtres.

- Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ?

Un item est composé d'un nom (name), de viewpoints et d'attributs, pour le moment, les attributs ne sont pas pris en compte, mais nous pensons changer cela en utilisant une approche similaire à celle de l'algorithme de notre premier projet REACT (notamment .map(y => `/attribute/${y.id}/spatial`)).

-Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?

Dans la partie algorithme, nous avons dit ne pas penser avoir de problème particulier, une bibliothèque supplémentaire ne sera donc pas nécessaire.

-Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?

Même réponse que la question précédente, pas de nécessité de faire appel à un service extérieur.

**Comment by benel** [comment]
Je crois que vous avez compris.

Mais ce qui n'est peut-être pas très clair dans votre explication c'est que c'est la constitution de la liste des candidats (par la méthode `candidates()`) qui va devoir tenir compte d'une nouvelle propriété (pour les attributs) : 

https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/SearchBar.jsx#L11-L19

Par ailleurs, vous voyez que ça utilise une méthode de classe (`Topic.getAllPaths()`) qui met en forme les données pour transformer des points de vue en une liste de chemins : 

https://github.com/Hypertopic/Porphyry/blob/v7/src/model.js

Ce serait pas mal de faire pareil pour transformer des corpus en une liste d'attributs/valeurs.

**Comment by ShovelBear** [comment]
C'était pas forcément bien expliqué mais c'est ce qu'on voulait faire, on voulait modifier la création des candidats à la source pour ajouter les attributs, mais on avait pas encore fini de comprendre tout le code et on était pas encore remonté jusqu'au bout. Merci pour les conseils, on fera au mieux.

**Comment by benel** [comment]
> Par ailleurs, vous voyez que ça utilise une méthode de classe (Topic.getAllPaths()) qui met en forme les données pour transformer des points de vue en une liste de chemins :
https://github.com/Hypertopic/Porphyry/blob/v7/src/model.js
Ce serait pas mal de faire pareil pour transformer des corpus en une liste d'attributs/valeurs.

@Morillev @seguragu La bonne nouvelle c'est que ce bout de code a été implémenté à l'occasion de l'ajout de la carte statique : 

https://github.com/Hypertopic/Porphyry/blob/v7/src/model.js#L32-L43

Vous pouvez l'utiliser sous la forme suivante : 

```js
new Items(selectedItems).getAttributes()
```

**Comment by Kodlah** [comment]
Après concertation au sein de notre groupe, nous pensons que la solution la plus adaptée est celle du groupe de @seguragu @LeonVongphanith @Morillev...
Nous n'avons pas posté notre stratégie d'implémentation, cette dernière regroupant les mêmes travaux qu'a effectué ce groupe. 

Ainsi, le binôme @JoJOes et @Kodlah, s'occupent actuellement du test automatisé d'après le scénario suivant : 

_Fonctionnalité: Sélectionner des items en fonction d'un attribut donné
Scénario: Recherche par attribut
Soit "dessins" le portfolio ouvert
Quand on met "1999" dans la barre de recherche et on clique sur "Created : 1999"
Alors le dessin "1999_18-25_05_TUN_R_A" est affiché_

**Comment by Kodlah** [comment]
### Phase 1



- [x]  Scenarios (Gherkin)

- [X]  Mockups

- [X] Implementation strategy


 ### Phase 2

- [X]  Acceptance tests (Capybara)

- [ ]  Implementation

Le binôme @neumeiej et @macchrd du groupe @Hypertopic/graines-d-artistes s'occuperont de l'implémentation pour la semaine prochain (04/06).

**Comment by Kodlah** [comment]
### Phase 1

   * [x]   Scenarios (Gherkin)
 
   * [x]   Mockups

   * [x]  Implementation strategy


 ### Phase 2
 
   * [x]   Acceptance tests (Capybara)

   * [X]   Implementation

**Comment by benel** [comment]
Attention @Kodlah, vous travaillez sur votre branche maître...

**Comment by Kodlah** [comment]
> 
> 
> Attention @Kodlah, vous travaillez sur votre branche maître...

En effet, j'ai remarqué par la suite, je corrige

**Comment by benel** [comment]
@Hypertopic/visite-sur-site-de-vitraux @Hypertopic/graines-d-artistes Je n'avais pas compris que vos deux équipes avaient choisi d'implémenter chacun de son côté la fonctionnalité #158...

**Comment by benel** [comment]
@Morillev, @Kodlah et @macchrd Je trouverais dommage de laisser sur le carreau le travail de l'une de vos équipes.

Ma proposition est que vous compariez vos codes ligne à ligne (#355 et #343) et que vous preniez la forme la plus élégante pour chaque bloc. La #355 a déjà pris en compte plusieurs de mes recommandations, donc elle me semble un peu plus mûre, cependant il est fort possible que pour certains blocs la #343 propose de meilleures alternatives.

Je vous laisse faire ce travail de fusion (ce n'est pas inintéressant d'ailleurs !). Le résultat final sera bien-sûr le produit des trois co-auteurs.

Notez qu'il ne s'agit ici que de l'implémentation. Pour les tests, j'ai déjà demandé aux PR #344 et #328 de fusionner.

**Comment by benel** [comment]
Deployed.
