### ISSUE TITLE
Feature: Search using basic boolean algebra

### ISSUE THREAD

**Issue by nhuchon** [Hypertopic/Porphyry#194]
## Content
Allow user to choose the union or the intersection between multiple categories.
By default, the intersection is choose between the categories.

---

## Checklist

- [x] Scenarios (@louisVHZ & @maxiloud)
- [x] Mock-up (@timothee-bayart )
- [x] Acceptance tests (@louisVHZ & @maxiloud & @timothee-bayart )
- [x] Implementation （@LeafStark & @louisVHZ & @nhuchon & @jbaptisteblot )

**Comment by timothee-bayart** [comment]
Mock-up

![Boolean_Algebra(1)](https://user-images.githubusercontent.com/22634448/59503495-d28edb80-8ea0-11e9-8e8f-27d7c097c79f.png)

**Comment by louisVHZ** [comment]
# Scénario

```
#language: fr
#Maxime TRINQUARD
#Louis VAUCHEZ

Fonctionnalité: Rechercher des items en utilisant les opérations booléennes basiques

Contexte:

Contexte:
    Soit le point de vue "Histoire de l'art" rattaché au portfolio "vitraux"
    Soit la rubrique "Armoiries du donateur" rattachée au point de vue "Histoire de l'art"
    Soit la rubrique "XIIIe s." rattachée au point de vue "Histoire de l'art"

Scénario:
    Soit "vitraux" le portfolio ouvert
    Soit "Donateur" une des rubriques développées
    Soit "Datation" une des rubriques développées
    Soit la rubrique "Armoiries du donateur" est visible et sélectionnée
    Soit la rubrique "XIIIe s." est visible et sélectionnée
    Quand on sélectionne "ou" entre la rubrique "XIIIe s." et la rubrique "Armoiries du donateur"
    Alors l'item "SMV 102" est affiché
    Et l'item "SMV 100" est affiché
    Et l'item "SMV 101" est affiché
    Et l'item "SMV 105" est affiché
    Et l'item "SP 102" est affiché
    Et l'item "SP 110" est affiché
    Et l'item "SPSP 009" est affiché
    Et l'item "SPSP 209" est affiché
    Et l'item "SU 100" est affiché
```

**Comment by nhuchon** [comment]
Nous avons mis en place avec @jbaptisteblot la fonctionnalité, et nous avons 2 interfaces a proposé. 
Une avec un select, qui est intuitive mais pas forcément esthétique et une avec un bouton sous la forme de badge, comme pour la suppression ou la negation, moins intuitif mais plus esthétique
Version 1
![Implémentation 2](https://user-images.githubusercontent.com/43350880/59705618-08182980-91ff-11e9-99d1-5905c2ca9ea7.png)
Version 2
![Implémentation 1](https://user-images.githubusercontent.com/43350880/59705622-09e1ed00-91ff-11e9-8708-a94ba3c7aa57.png)

**Comment by benel** [comment]
Merci pour cette contribution à Porphyry.

- La version 2 est effectivement plus esthétique... Mais comment change-t-on le `ET` en `OU` et inversement ? En cliquant dessus ? Ou peut-être avez-vous préféré ne pas proposer de le changer ?
- Le `+` sert à rendre négatif et le `-` à le rendre  positif ? L'inverse ne serait-il pas plus logique ?
- Serait-il possible de noter les connecteurs logiques de manière infixée plutôt que préfixée ? Seuls les logiciens, écrivent de manière préfixée... La notation infixée ressemble plus à un morceau de phrase.

**Comment by jbaptisteblot** [comment]
- On clique effectivement sur le bouton pour changer entre le ET et le OU.

- L'inverse est effectivement plus logique, une erreur s'est glissée lors des changements et a fait que les icônes ont été inversées en rapport à l'ordre tel que nous l'avions conçu.

- Nous allons essayer de le faire, il est vrai que ce serait plus logique, le mettre sur le côté était le résultat plus simple pour une première implémentation, mais il est plus logique de l'avoir de manière infixée. Je tiens à noter cependant que même en le mettant de manière infixée, nous pourrons uniquement faire un seul type d'instruction au sein de parenthèses

**Comment by jbaptisteblot** [comment]
Voilà ce que nous avons réussi à faire, il est vrai que c'est bien plus agréable à lire.

![image](https://user-images.githubusercontent.com/475697/59716566-80d6b000-9216-11e9-9457-e2ff38397493.png)

**Comment by nhuchon** [comment]
Bonsoir monsieur @benel, 
Suite à l'implémentation que nous avons mis en place avec @jbaptisteblot, il nous a été nécessaire de modifier le système d'URI. Malheureusement, cela rend le test portfolio_select.feature non fonctionnel ; en effet l'une des étapes sélectionnait des catégories en visitant directement l’url adaptée (l'étape Soit les rubriques "Ateliers du Carmel du Mans" sont sélectionnées avec comme step definition: ![image](https://user-images.githubusercontent.com/43350880/59797497-1d18b980-92e0-11e9-9ca9-203aff928b84.png) 
Nous avons donc essayé de modifier l’implémentation de ce test, mais aucune solution ne nous a semblé correspondre au parcours utilisateur : 
- Utiliser le nouveau système d'URI se basant sur un JSON ne semble pas correspondre à ce qu’un utilisateur fera seul 
- Demander à cliquer sur un bouton non visible via la ligne de code find('a', text: topic, visible: false).click ou encore la ligne de code suivante Capybara.ignore_hidden_elements = false. Cependant cette implémentation ne permet pas de cliquer sur le lien, Capybara ne considérant pas le lien comme visible.
- Modifier le scénario : Nous pourrions penser à faire que le scénario commence par ouvrir la page puis va pour cliquer sur « Ateliers du Carmel du Mans » en ouvrant la catégorie « Ateliers », cependant cette implémentation est dépendante du design de la page, ce qui ne semble pas adapté non plus.

Auriez vous des indications ou des directions dans lesquelles nous pourrions orienter notre recherche ?
Merci d’avance

**Comment by benel** [comment]
> Utiliser le nouveau système d'URI se basant sur un JSON ne semble pas correspondre à ce qu’un utilisateur fera seul

Un usager n'est effectivement pas censé composer une URI lui-même (l'opacité des URI est même un des principes du Web), par contre, il est tout à fait autorisé à la mettre en favoris, la partager par courriel, etc.

Par ailleurs, comme c'est un `soit` et non un `quand`, on cherche juste la manière la plus simple et la plus rapide de se retrouver dans cet état. 

> Modifier le scénario : Nous pourrions penser à faire que le scénario commence par ouvrir la page puis va pour cliquer sur « Ateliers du Carmel du Mans » en ouvrant la catégorie « Ateliers », cependant cette implémentation est dépendante du design de la page, ce qui ne semble pas adapté non plus.

Le fait que  « Ateliers du Carmel du Mans » soit sous la catégorie « Ateliers » ne dépend pas à proprement parler du design de la page mais de la structure des données. Le fait qu'elle soit non visible tant que l'autre n'est pas ouverte dépend de la fonctionnalité d'affichage arborescent (inutile en effet de connaître précisément le DOM, on reste au niveau de ce que voit l'usager et de ce qu'il attend du système).

Pour résumer : les deux approches sont acceptables. La première est plus rapide à exécuter (ce qui à son importance) pour un test automatisé.
