### ISSUE TITLE
Open a resource

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#208]
Because a resource is just an attribute with an HTTP-URI value, this could be easily implemented by making attribute values clickable when they are HTTP-URIs.

**Comment by garnier5** [comment]
For the "studying abroad" project, it would be interesting to be able to click on a link to quickly access the resource of the foreign university thanks to the HTTP-URI of the partner university's website.

**Comment by moonkeys** [comment]
Pour "Young Artist", cette fonctionnalité permettrait d'ouvrir un dessin grâce à un HTTP-URI.

**Comment by Ciyax** [comment]
Dans le cadre du projet Studying abroad, l'ouverture d'une ressource permettrait d'accéder à la page annexe de description de l'UE, ou du site de l'université partenaire via une HTTP-URI.

**Comment by hebertquentin** [comment]
Dans le cadre de l'Archéologie grecque, il serait utile de pouvoir ouvrir les images (puisque c'est plus ou moins un catalogue d'images) via une HTTP-URI.

**Comment by benel** [comment]
@hebertquentin On est d'accord que les ressources principales s'affichent déjà quand ce sont des images ? La fonctionnalité qui est décrite ici concerne les ressources annexes. Vous pensez à quoi comme ressources annexes (ni image principale ni vignette) des vases ?

**Comment by hebertquentin** [comment]
@benel je ne sais pas réellement... D'autres photos de l'item, sous d'autres angles par exemple ?

**Comment by ElizabethBricoutUTT** [comment]
Dans le cadre du projet "récit d'expérience", cela pourrait être utile pour rediriger vers des articles sur d'autres sites webs, pour plus de détails par exemple.

**Comment by Starangon** [comment]
Projet Visite sur site de vitraux :
ON pourrait l'utiliser pour alléger (où compléter) certaines description en rajoutant des liens vers une documentation plus complète mais qui le serait trop pour un utilisateur lambda.

**Comment by ValentinLouerat** [comment]
Projet : Approche par compétence de la formation
Utile pour accéder à des informations complémentaires sur les différents UE/compétences

**Comment by Damien71** [comment]
Mock-up attached for the Studying Abroad project :
![image](https://user-images.githubusercontent.com/50024514/78921355-12a8f580-7a95-11ea-82ef-428c613b0dcf.png)

**Comment by benel** [comment]
Deployed.
