### ISSUE TITLE
How to downgrade to Java 6 on MacOS X ? 

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#24]
If you realize too late that you shouldn't have upgraded to Java 7, there is a way to re-enable Java 6 without reinstalling it from scratch:
http://support.apple.com/kb/HT5559

**Comment by awesomestmason** [comment]
I am having the same problem, and I have tried http://support.apple.com/kb/HT5559 and most youtube videos. When I type in terminal java -version I get:
java version "1.7.0_04"
Java(TM) SE Runtime Environment (build 1.7.0_04-b21)
Java HotSpot(TM) 64-Bit Server VM (build 23.0-b21, mixed mode)
So I still have Java 7... Anyone know how to downgrade properly..

**Comment by benel** [comment]
@awesomestmason Porphyry runtime only needs the `javaws` (Java Web Start) command to be re-enabled (and not the core `java` command). So I suppose your question is **unrelated to Porphyry**.

However I think that the solution to your problem is to switch between the installed versions in the java configuration panel (in `system preferences`). If you need more help, you should ask StackOverFlow or similar Q&A sites.
