### ISSUE TITLE
Consult items on a geographical map with custom layer

### ISSUE THREAD

**Issue by Marshlyin** [Hypertopic/Porphyry#272]
## Content

Same ticket as [Hypertopic/Porphyry#121)](https://github.com/Hypertopic/Porphyry/issues/121) but with a custom layer chosen by owner and custom points of interest, chosen by users. 

---

## Phase 1 

- [x] Scenarios  
- [x] Mockups 
- [x] Implementation strategy

## Phase 2 
- [ ] Acceptance tests
- [x] Implementation

**Comment by Kryddd** [comment]
Pour le projet **Kerameikos**, et dans la continuité du travail de Mathieu Drache, l'ajout de cette fonctionnalité permettra de visualiser les tombes et les batiments dans lesquels ont été retrouvés les vases à l'aide d'un fond de carte personnalisé.

**Comment by Thang-long** [comment]
Mockup avec @bialoian 
![mck1](https://user-images.githubusercontent.com/31899197/118263346-6e268d80-b4b6-11eb-81f8-615869dfbd97.png)
![mck2](https://user-images.githubusercontent.com/31899197/118263361-71217e00-b4b6-11eb-8927-57765f62da2e.png)

Cette feature change le fond de carte visuellement. Le comportement reste le même cependant (les points d'intérêts sont toujours affichés, ...).

**Comment by Thang-long** [comment]
# Stratégie d'implémentation
## Quelle partie du code sera impactée (classes, méthodes) ?
Le code à modifier pour afficher des entités et un calque personnalisés avec l'API Google Maps se situe dans [src/components/portfolioPage/GeographicMap.jsx](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/GeographicMap.jsx).

Il faudra modifier la méthode handleClick et créer une nouvelle méthode pour gérer l'affichage ou non des entités :
```javascript
handleClick = (place_id) =>  #{
    let place = this.state.places.find(x => x.place_id === place_id);
    let uri = `/?t={"type":"intersection","data":[{"type":"intersection","selection":["spatial : ${place.spatial}"],"exclusion":[]}]}`;
    this.props.history.push(uri);
}
```
La version actuelle de Porphyry utilise l'API Google Maps via le package react-geocode. A l'avenir, l'API GeoXEne permettra de géocoder des adresses inconnues par les services de Google.

## Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?
L'ajout semble assez simple. En effet, il faudrait gérer l'affichage ou non des entités et voir comment changer les calques à travers l'API Google Maps.

## Les données dont vous avez besoin sont-elles déjà chargées par la page ? Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ? Si non, quelle sera la requête la plus efficace et comment allez-vous récupérer dans la structure de données précisément celles qui vous intéressent ?
GeoXEne utilisera l'attribut spatial des items. Aucune modification ne sera nécessaire sur cet aspect puisque l'attribut est déjà structuré correctement pour être utilisé par react-geocode :
https://github.com/Hypertopic/Porphyry/blob/f73e48917603edb95de94457f153e86b66016451/src/components/portfolioPage/GeographicMap.jsx#L19

## Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?
Non, l'API Google Maps possède déjà des méthodes pour changer de calque et afficher ou non les entités.

## Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?
Non, tout est déjà disponible sur l'API Google Maps.

## Des étapes préalables de développement, testables, sont-elles envisageables afin de diminuer la complexité de la livraison ? Refactoring (livrable à part entière, isofonctionnel) ? Code développable et testable de manière externe au logiciel ? Étape du scénario (non livrable en tant que tel mais dont l"effet peut être testé) ?
Oui, il faudrait que l'API Google Maps et que les calques soient déployés.

**Comment by benel** [comment]
@Thang-long @bialoian 

Merci pour votre maquette. On pourrait la simplifier d'avantage : est-il réellement nécessaire de choisir si on veut afficher ou cacher le fond de carte ? Dit autrement, pensez-vous que votre partie prenante voudra cacher les fonds de carte ?

**Comment by benel** [comment]
@Thang-long Merci également pour le scénario #502.

@Hypertopic/kerameikos Au fait, comment se fait-il que ce soient les mêmes personnes qui travaillent sur les deux livrables (maquettes et scénarios) ? Quelle est la répartition des livrables par binômes ? Merci de la mentionner systématiquement dans les tickets.

En tenant compte de ma remarque sur la maquette : 
- Comment pourriez vous expliquer simplement ce qui changer quand la fonctionnalité sera implémentée ? 
- Dans quelle situation faudra-t-il se placer pour le voir ?

**Comment by Thang-long** [comment]
@benel Pour les maquettes, nous avions déjà fait celles-ci lors de la séance dédiée à Adobe XD avec Pascal SALEMBIER. 

### Est-il réellement nécessaire de choisir si on veut afficher ou cacher le fond de carte ? Dit autrement, pensez-vous que votre partie prenante voudra cacher les fonds de carte ?
C'est vrai, il vaudrait mieux afficher le fond de carte "custom" directement. Je ne pense pas que la partie prenante voudra cacher les fonds.

### Comment pourriez vous expliquer simplement ce qui changer quand la fonctionnalité sera implémentée ?
Pratiquement rien, si ce n'est que le fond de carte sera un fond de carte "custom" où on pourra voir où les vases ont été retrouvés. Le comportement devrait rester le même normalement.

### Dans quelle situation faudra-t-il se placer pour le voir ?
Sur la page "portfolio", on pourra voir la carte avec le fond de carte directement.

**Comment by benel** [comment]
@Thang-long Merci (de même !) pour la stratégie d'implémentation. Vous vouliez faire à vous tout seul le travail de 6 personnes ? Vous êtes un véritable homme-orchestre 😉 

> Il faudra modifier la méthode handleClick et créer une nouvelle méthode pour gérer l'affichage ou non des entités

Oubliez cette histoire de clic... Cela vous permettra de vous poser les bonnes questions... Quels sont les nouveaux paramètres à passer à GoogleMaps ? Dans quel cas on doit les rendre actif ? Comment pourrait-on faire pour les configurer. Et quel ticket non encore implémenté serait un bon pré-requis ?

Par ailleurs, c'est assez déstabilisant que vous ne référenciez pas du tout le code de test qui est fourni avec GeoXEne : après tout, c'est une bonne partie de la stratégie d'implémentation qui a été faite. Ça a pris 6 mois à un de vos camarades... Ce serait dommage de repartir à zéro.

**Comment by benel** [comment]
> Sur la page "portfolio", on pourra voir la carte avec le fond de carte directement.

Ça c'est la réponse que j'attendais à la question "Comment pourriez vous expliquer simplement ce qui changer quand la fonctionnalité sera implémentée ?".

Il reste à répondre à la question "Dans quelle situation faudra-t-il se placer pour le voir ?"
Je vais le voir par exemple en ouvrant le site des vitraux de l'Aube ?

**Comment by Thang-long** [comment]
Ahhhhh, non non, le fond de carte personnalisé ne devra s'afficher que pour le site du Kerameikos. Comme ce fond sera destiné à représenter le lieu où les vases ont été retrouvés, ça ne marchera pas avec les vitraux du coup.

**Comment by ianbialo** [comment]
> @Hypertopic/kerameikos Au fait, comment se fait-il que ce soient les mêmes personnes qui travaillent sur les deux livrables (maquettes et scénarios) ? Quelle est la répartition des livrables par binômes ? Merci de la mentionner systématiquement dans les tickets.

@Thang-long et moi-même travaillons sur ce ticket, les 3 autres binômes de notre groupe travaillent sur le second ticket https://github.com/orgs/Hypertopic/projects/29#card-56668382
Les binômes ont été mis à jour !

**Comment by Thang-long** [comment]
## Comme dans notre séance sur le développement, vous pouvez tester des petits bouts de code indépendants et les associer à votre stratégie (avec éventuellement des exemples de données, voire même des temps d'exécution).
J'ai repris le code que @Kryddd avait proposé pour le ticket #349, en ajoutant un booléen dans le composant `<LoadScript/>` pour afficher ou non les calques personnalisés en fonction du type d'utilisateur. Dans le code de Porphyry, le type d'utilisateur est adapté automatiquement et on pourrait se baser sur cela pour ne pas afficher les calques sur le site des vitraux. 
Qu'en pensez-vous @benel ?
```javascript
import React from 'react';
import { GoogleMap, Marker, LoadScript } from '@react-google-maps/api';
import conf from '../config.js';

class App extends React.Component {
  state = {
    place: []
  };

  componentDidMount() {
    fetch('http://localhost:3000/?address=Tombe 2, Pompeion, Kerameikos') // GeoXEne
      .then(response => response.json())
      .then(data => this.setState({ place: data.results[0].geometry.location }));
  }

  render() {
    const SETTINGS = await conf; // Récupération des paramètres pour connaître le type d'utilisateur (vases, vitraux, ...)
    let marker = <Marker position={this.state.place} />
    return (
      // Là où on peut changer les calques personnalisés et les afficher ou non
      <LoadScript googleMapsApiKey={process.env.REACT_APP_MAP_API_KEY} displayCustomLayers={SETTINGS.user === 'vases'}> 
        <GoogleMap
          mapContainerStyle={{ width: '100%', height: '600px' }}
          center={this.state.place}
          zoom={16}
        >
          {marker}
        </GoogleMap>
      </LoadScript>
    );
  }
  
}

export default App;
```

**Comment by benel** [comment]
@Thang-long 

>```js 
> <LoadScript googleMapsApiKey={process.env.REACT_APP_MAP_API_KEY} displayCustomLayers={SETTINGS.user === 'vases'}> 
>```

Désolé, je ne comprends pas...

1. Vous avez ajouté une propriété `displayCustomLayers` lors de l'appel du composant `LoadScript` or cette propriété ne semble pas définie dans la bibliothèque correspondante (cf. [documentation](https://react-google-maps-api-docs.netlify.app/#loadscript)).
2. Vous pensez mettre "en dur" le fait que votre fonctionnalité n'est activée que quand le portfolio s'appelle "vases" ? Rien ne vous choque ?

**Comment by Thang-long** [comment]
Je pensais que `<LoadScript>` était un composant à créer. Du coup, pour enlever le "code en dur" on peut le déplacer dans un fichier de configuration.

> @Thang-long
> 
> > ```js
> > <LoadScript googleMapsApiKey={process.env.REACT_APP_MAP_API_KEY} displayCustomLayers={SETTINGS.user === 'vases'}> 
> > ```
> 
> Désolé, je ne comprends pas...
> 
> 1. Vous avez ajouté une propriété `displayCustomLayers` lors de l'appel du composant `LoadScript` or cette propriété ne semble pas définie dans la bibliothèque correspondante (cf. [documentation](https://react-google-maps-api-docs.netlify.app/#loadscript)).
> 2. Vous pensez mettre "en dur" le fait que votre fonctionnalité n'est activée que quand le portfolio s'appelle "vases" ? Rien ne vous choque ?

**Comment by benel** [comment]
@Thang-long @bialoian 

> Du coup, pour enlever le "code en dur" on peut le déplacer dans un fichier de configuration.

Quand vous en serez à ce livrable, ce serait bien de faire une proposition de structuration du fichier de configuration pour indiquer pour chaque portfolio quels sont les calques à utiliser.

**Comment by Thang-long** [comment]
@benel
Avec @bialoian, dans le fichier `/public/config.yml`, nous pensons créer un attribut `layers` dans lequel on pourrait mettre une liste d'URI référençant les calques à afficher sur la carte.
```yaml
user: vitraux
services:
  - http://localhost
layers:
  - URI1
  - URI2
  - ...
```

**Comment by benel** [comment]
@Thang-long @bialoian 

> dans le fichier /public/config.yml, nous pensons créer un attribut layers dans lequel on pourrait mettre une liste d'URI référençant les calques à afficher sur la carte.

Oui c'est une première piste...

Par contre, cela signifierait, comme je le disais plus haut, que les calques seraient chargés (ou tout au moins configurés) même quand le portfolio n'a rien à voir. C 'est pourquoi, je suggrérais l'idée de faire dépendre ce paramètre du portfolio.
Est-ce que vous voyez ce que ça donnerait dans le fichier de configuration ?

> layers:
>  - URI1
>  - URI2
 > - ...

N'ayez pas peur de donner des exemples concrets (ceux du prototype).

**Comment by Thang-long** [comment]
Donc si j'ai bien compris, pour uniquement "toucher" au portfolio des vases, dans le fichier `config.yml`, il faudrait mettre :
```yaml
vases:
  layers:
    - URI1
    - URI2
    - ...
 ```
 Est-ce bien cela @benel ?

**Comment by benel** [comment]
> Est-ce bien cela @benel ?

Tout à fait @Thang-long !

**Comment by benel** [comment]
@Thang-long Pour éviter de mélanger des clefs prédéfinies (`user`, `services`) et des clefs libres (`vases`...), je rajouterai bien un étage dans la structure...

**Comment by Thang-long** [comment]
> @Thang-long Pour éviter de mélanger des clefs prédéfinies (`user`, `services`) et des clefs libres (`vases`...), je rajouterai bien un étage dans la structure...

```yaml
portfolio:
  vases:
    layers:
      - URI1
      - URI2
      - ...
 ```
Je propose quelque chose comme cela, qu'en pensez-vous ? @benel 
Comme ça, tout ce qui concerne le site du Kerameikos sera référencé dans `portfolio>vases`.

**Comment by benel** [comment]
@Thang-long C'est très bien ! 
Par contre, je tiens toujours à mes exemples précis ;)
Dites vous que ça vous fera gagner du temps ensuite pour les tests ou les démos.

**Comment by Thang-long** [comment]
Donc, si on récapitule pour la stratégie d'implémentation, nous avons :

## Quelle partie du code sera impactée (classes, méthodes) ?
Le code à modifier pour afficher des entités et un calque personnalisés avec l'API Google Maps se situe dans [src/components/portfolioPage/GeographicMap.jsx](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/GeographicMap.jsx).

Il faudra faire quelques modifications au niveau du `return` de la méthode `render()` pour prendre en compte les calques à afficher. Il faudra ajouter un autre composant `<GroundOverlay>` proposé par l'API Google Maps.
```javascript
return (
        <LoadScript googleMapsApiKey={this.state.api_key} >
          <GoogleMap
            mapContainerStyle={{ width: '100%', height: '400px' }}
            center={center}
            zoom={2}
            onLoad={this.handleLoad}
          >
            {markers}
          </GoogleMap>
        </LoadScript>
      );
```
La version actuelle de Porphyry utilise l'API Google Maps via le package react-geocode. A l'avenir, l'API GeoXEne permettra de géocoder des adresses inconnues par les services de Google.

## Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?
L'ajout semble assez simple. En effet, d'après la documentation de l'API Google Maps (cf. [documentation](https://react-google-maps-api-docs.netlify.app/#groundoverlay)), il est possible d'afficher un calque sur la carte en précisant un URI et des coordonnées pour placer l'image.

## Les données dont vous avez besoin sont-elles déjà chargées par la page ? Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ? Si non, quelle sera la requête la plus efficace et comment allez-vous récupérer dans la structure de données précisément celles qui vous intéressent ?
GeoXEne utilisera l'attribut spatial des items. Aucune modification ne sera nécessaire sur cet aspect puisque l'attribut est déjà structuré correctement pour être utilisé par react-geocode :
https://github.com/Hypertopic/Porphyry/blob/f73e48917603edb95de94457f153e86b66016451/src/components/portfolioPage/GeographicMap.jsx#L19

## Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?
Non, l'API Google Maps possède déjà des méthodes pour changer de calque et afficher ou non les entités.

## Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?
Non, tout est déjà disponible sur l'API Google Maps.

## Des étapes préalables de développement, testables, sont-elles envisageables afin de diminuer la complexité de la livraison ? Refactoring (livrable à part entière, isofonctionnel) ? Code développable et testable de manière externe au logiciel ? Étape du scénario (non livrable en tant que tel mais dont l"effet peut être testé) ?
Oui, il faudrait que l'API Google Maps et que les calques soient déployés.

## Comme dans notre séance sur le développement, vous pouvez tester des petits bouts de code indépendants et les associer à votre stratégie (avec éventuellement des exemples de données, voire même des temps d'exécution).
En prenant en compte ces remarques, on pourrait imaginer un prototype comme ceci :

Dans le fichier de configuration :
```yaml
user: vases
services:
  - http://localhost
staticMap: API_KEY
interactiveMap: API_KEY
portfolio:
  vases:
    layers:
      - uri: https://steatite.utt.fr/picture/405e66c63060b595c02e6590a8f6abbda104cb03
        bounds:
          south: 37.977910
          west: 23.718200
          north: 37.978780
          east: 23.719010
      - uri: https://steatite.utt.fr/picture/78e81db6ee77decd3e40cf3124c04a6aaaaa2fc4
        bounds:
          south: 37.97862453543905
          west: 23.716649743986387
          north: 37.978755
          east: 23.716789  
```

Dans le fichier prototype :
```javascript
import React from 'react';
import { GoogleMap, Marker, LoadScript, GroundOverlay } from '@react-google-maps/api';

class App extends React.Component {
  state = {
    place: []
  };

  componentDidMount() {
    fetch('http://localhost:3000/?address=Tombe 2, Pompeion, Kerameikos') // GeoXEne
      .then(response => response.json())
      .then(data => this.setState({ place: data.results[0].geometry.location }));
  }

  render() {
    let marker = <Marker position={this.state.place} />

    return (
      <LoadScript googleMapsApiKey={process.env.REACT_APP_MAP_API_KEY} >
        <GoogleMap
          mapContainerStyle={{ width: '100%', height: '600px' }}
          center={this.state.place}
          zoom={16}
        >
          <GroundOverlay key={'url'} url={process.env.layer1.uri} bounds={process.env.layer1.bounds}>
            {marker}
          </GroundOverlay>
          <GroundOverlay key={'url'} url={process.env.layer2.uri} bounds={process.env.layer2.bounds}>
            {marker}
          </GroundOverlay>
        </GoogleMap>
      </LoadScript>
    );
  }
}

export default App;
```

Qu'en pensez-vous @benel ?

**Comment by ianbialo** [comment]
> Donc si j'ai bien compris, pour uniquement "toucher" au portfolio des vases, dans le fichier `config.yml`, il faudrait mettre :
> 
> ```yaml
> vases:
>   layers:
>     - URI1
>     - URI2
>     - ...
> ```
> 
> Est-ce bien cela @benel ?

@Thang-long Du coup ça répond à la question que je me posais sur les portfolio tout à l'heure aha c'est plus clair maintenant :p

**Comment by benel** [comment]
En fait on ne s'est pas compris sur les exemples... Je voulais dire les deux URI qui sont données dans la démo de GeoXEne : https://github.com/Hypertopic/GeoXEne/blob/main/test/maps.js#L8-L16

**Comment by benel** [comment]
@Thang-long @bialoian En fait on ne s'est pas compris sur les exemples... Je voulais dire les deux URI qui sont données dans la démo de GeoXEne : https://github.com/Hypertopic/GeoXEne/blob/main/test/maps.js#L8-L16

**Comment by Thang-long** [comment]
@benel ce sont des URI qui seront dans le fichier de configuration ou que l'on récupère à travers un GET ?

**Comment by benel** [comment]
> ce sont des URI qui seront dans le fichier de configuration ou que l'on récupère à travers un GET ?

On les met dans le fichier de configuration (à la place de votre `uri_du_calque.jpg` ou `URI1`, `URI2`).. Attention, il y en a deux dans cet exemple...

**Comment by benel** [comment]
>     Fonctionnalité: Affichage de calques	
>      Scénario: Voir un calque sur la carte
>            Soit "Calque 1" le calque sélectionné
>            Alors le calque "Calque 1" est affiché sur la carte
>      Scénario: Voir plusieurs calques sur la carte
>            Soit "Calque 1|Calque 2" les calques sélectionnés
>            Alors le calque "Calque 1" est affiché sur la carte
>      Et le calque "Calque 2" est affiché sur la carte

Merci @Thang-long pour votre scénario (dans la demande d'intégration #510).
Mais vos données (ce qui est entre guillemets) n'est pas assez précis ou illustratif.
Le scénario doit pouvoir être "raconté" à quelqu'un... Comment fait-on pour voir que la fonctionnalité existe ? Avec un vrai exemple ? Qu'est-ce qui est nécessaire de faire au préalable ?

@Hypertopic/kerameikos À la prochaine réunion de suivi, il faudra remettre un binôme sur ces scénarios. Ils n'auraient pas dû être considérés comme terminés.

**Comment by Thang-long** [comment]
@benel Je ne comprends pas, on avait dit que ce scénario n'était pas réellement testable automatiquement. Seul un humain pourrait effectuer le scénario. On peut remplacer "Calque 1" et "Calque 2" par les URI des images en provenance de steatite ?

**Comment by ianbialo** [comment]
@benel Je suis pas sûr de comprendre non plus... @Thang-long peut-être qu'il faut aussi changer l'intitulé "afficher un calque" pour le remplacer par un exemple concret.

**Comment by benel** [comment]
@Thang-long @bialoian 

Même pour un humain (surtout pour un humain ?), il faut que ce soit compréhensible : 
- Décrire l'exemple (par exemple celui de vos deux nécropoles du Kerameikos),
- Expliquer comment l'indiquer dans la configuration.
- Expliquer ce qui change dans l'affichage.

Avec ça, un humain pourra effectivement tester votre fonctionnalité. 

OK ?

**Comment by benel** [comment]
@bialoian 

> peut-être qu'il faut aussi changer l'intitulé "afficher un calque" pour le remplacer par un exemple concret.

Autant les étapes doivent être spécifiques (avec un cas concret, des données d'exemple) autant le titre de la fonctionnalité et le titre du scénario doivent être génériques.
Je pense d'ailleurs que vous pouvez vous limiter à un seul scénario (ce n'est pas suffisamment différent avec un calque pour qu'il y ait un risque que ça marche avec deux et pas avec un).

**Comment by benel** [comment]
L'implémentation de la fonctionnalité est intégrée à la branche principale (https://github.com/Hypertopic/Porphyry/commit/c3899a3f1427187d20f807221c6ab2c4f91cf6b3) 🎉 
Bravo à @Thang-long et @bialoian 🏅

**Comment by benel** [comment]
La fonctionnalité est en production 🎉

**Comment by Thang-long** [comment]
> La fonctionnalité est en production 🎉

Trop cool, on voit les calques maintenant \o/

**Comment by ianbialo** [comment]
> > La fonctionnalité est en production 🎉
> 
> Trop cool, on voit les calques maintenant \o/

Et ça ça fait plaisir つ ◕_◕ ༽つ

**Comment by Kryddd** [comment]
## Acceptance tests

Après vérification, les tests de validation pour ce ticket ne peuvent pas être effectués avec l'aide de Capybara à cause de l'impossibilité de récupérer les coordonnées `south`, `west`, `north` et `east` d'un calque sur le frame Google Maps. Cette contrainte rend impossible l'implémentation dans Capybara de commandes comme `l'attribut "south" du calque "0" est "37.977910"`.
Cependant, le test peut être fait sous la forme d'un test manuel :

- Modifier le fichier de configuration public/config.yml et compléter avec une clé d'API google : 
```yaml
user: vases
services:
  - https://argos.utt.fr
  - https://steatite.utt.fr
map:
  key: CLE_API_GOOGLE
  geocodingService: https://maps.googleapis.com/maps/api/geocode/json
portfolio:
  vases:
    layers:
      - uri: https://steatite.utt.fr/picture/405e66c63060b595c02e6590a8f6abbda104cb03
        bounds:
          south: 37.977910
          west: 23.718200
          north: 37.978780
          east: 23.719010
```
- Lancer Porphyry
- Se rendre aux coordonnées du site de Kerameikos à Athènes (latitude 37.978345, longitude 23.718605) sur la carte de la page d'accueil.
- La carte devrait se trouver centrée sur le calque.

**Comment by benel** [comment]
> Cependant, le test peut être fait sous la forme d'un test manuel

Merci @Kryddd pour cette première version de test manuel.

Voici quelques pistes d'amélioration : 

> Lancer Porphyry

Dans le choix du verbe, mettez-vous plutôt à la place d'un utilisateur que d'un développeur.

> Se rendre aux coordonnées du site de Kerameikos à Athènes (latitude 37.978345, longitude 23.718605) sur la carte de la page d'accueil.

- Un peu comme dans le scénario, expliquez sur quoi on doit cibler pour zoomer (d'abord sur X, puis sur Y puis sur Z).
- Dans le test, il faut être précis sur les interactions, donc n'hésitez pas à expliciter une des manières de faire un zoom dans Google Maps.

> La carte devrait se trouver centrée sur le calque.

- Vous voulez dire avant le zoom ? Ça ce n'est pas sûr du tout, ça dépendra de la qualité de votre jeu de données...
- Vous voulez dire après le zoom ? Ça dépendra de la dextérité avec laquelle vous aurez zoomé...

**Comment by Kryddd** [comment]
## Acceptance tests (version 2)

- Modifier le fichier de configuration public/config.yml et compléter avec une clé d'API google : 
```yaml
user: vases
services:
  - https://argos.utt.fr
  - https://steatite.utt.fr
map:
  key: CLE_API_GOOGLE
  geocodingService: https://maps.googleapis.com/maps/api/geocode/json
portfolio:
  vases:
    layers:
      - uri: https://steatite.utt.fr/picture/405e66c63060b595c02e6590a8f6abbda104cb03
        bounds:
          south: 37.977910
          west: 23.718200
          north: 37.978780
          east: 23.719010
```
- Démarrer Porphyry avec la commande `npm start` dans un terminal
- Se rendre sur la page d'accueil de Porphyry à l'URI `http://localhost:3000`
- Se déplacer sur la carte en Grèce, à Athènes, sur le site archéologique Kerameikos à l'aide de la souris
- En zoomant à l'aide de CTRL + molette ou la flèche plus, le calque devrait apparaître
- Le calque est correctement placé s'il se trouve entre le Mur de Thémistocle à l'Ouest et le Pompéion à l'Est.

**Comment by CeyFun** [comment]
Bonjour, je me permets d'intervenir sur cette issue car je travaille aussi sur des problématiques de configuration pour un portfolio particulier (merci @benel de m'avoir parlé de [ceci](https://github.com/Hypertopic/Porphyry/pull/536#issuecomment-865613797)).
J'ai remarqué que si j’étends votre système pour le YAML (autant ne pas réinventer la roue) il y a des problèmes pour vos systèmes de calques : vous ne vérifiez pas si la propriété `layers` est présente.

https://github.com/Hypertopic/Porphyry/blob/191e172e43f2387aa9f4fe502726bbf57c672e3a/src/components/portfolioPage/GeographicMap.jsx#L26-L30

Je vous conseillerai de mettre une condition supplémentaire pour vérifier la présence de cette propriété ou alors de donner une valeur par défaut avec le 'ou logique' `||`.

Si vous voulez je peux faire un commit et une pull request mais ça peut vous faire des contributions 'gratuites' 😉.

**Comment by benel** [comment]
> J'ai remarqué que si j’étends votre système pour le YAML (autant ne pas réinventer la roue) il y a des problèmes pour vos systèmes de calques : vous ne vérifiez pas si la propriété layers est présente.

Je confirme : il doit effectivement y avoir dans les logs un `Cannot read property 'map' of undefined` dans le `render` lorsque la carte est configurée mais pas les calques.

**Comment by Kryddd** [comment]
J'ai fait une pull request pour corriger le problème. Merci à @CeyFun et @benel  de nous l'avoir signalé !
