### ISSUE TITLE
Update an item's attribute

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#29]
- [x] Scénarios (Meng Ruolin Fangxu)
- [x] Maquettes (David Lorraine Yuanjia)
- [x] Tests automatisés  (Jie)
- [x] Implémentation (Ruolin Fangxu)

**Comment by davp01x** [comment]
Fonctionnalité pour l'annuaire participatif :
Modifier les informations de bases (attributs) d'une personne (item)

**Comment by Pinksea** [comment]
![update_attribute_29](https://user-images.githubusercontent.com/16323265/39620116-5f352c1c-4f8a-11e8-8c36-69845c5a09ce.png)

**Comment by Pinksea** [comment]
![update_attribute_29](https://user-images.githubusercontent.com/16323265/39621208-38f7882a-4f8e-11e8-853e-f1511bc37308.png)

La personne modifie un attribut ( UV modifiable pour les enseignants ici par exemple), il clique sur le crayon et on obtient la deuxième image.
