### ISSUE TITLE
Unset an item's attribute

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#30]
- [x] Scénarios (Meng Ruolin Fangxu)
- [x] Maquettes (David Lorraine Yuanjia)
- [x] Tests automatisés  (Ruolin Fangxu)
- [x] Implémentation(Yuanjia)

**Comment by davp01x** [comment]
Fonctionnalité pour l'annuaire participatif :
Supprimer les informations de bases (attributs) d'une personne (item)

**Comment by Pinksea** [comment]
![unset_attribute_30](https://user-images.githubusercontent.com/16323265/39622141-69c4e8a0-4f91-11e8-8c40-e52d50132576.png)
Pour supprimer un attribut un utilisateur cliquera sur le crayon (image1), et les attributs qui sont supprimables apparaîtront avec une petite croix rouge (image2). S'il clique sur la croix rouge il reviendra à la première image

**Comment by benel** [comment]
Implemented (but with a bug depending on the browser and the window size).
