### ISSUE TITLE
Set an item's attribute

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#31]
- [x] Scénarios (Meng)
- [x] Maquettes (David Lorraine Yuanjia)
- [x] Tests automatisés(Meng)
- [x] Implémentation (Lorraine)

**Comment by davp01x** [comment]
Fonctionnalité pour l'annuaire participatif :
Créer une informations de bases (attributs) pour une personne (item)

**Comment by Pinksea** [comment]
![set_attribute_31](https://user-images.githubusercontent.com/16323265/39621675-dfd2214a-4f8f-11e8-8451-062e6bdb1181.png)
L'utilisateur clique sur le +de la première image et obtient l'image suivante.
Il peut créer un attribut de la valeur qu'il souhaite, une proposition sera faite, sur les anciens attributs déjà créés par d'autres utilisateurs
