### ISSUE TITLE
Assign an existing topic to an item

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#32]
- [x] Scénarios ( Leo Schneider @leoschneider, Valentin Porcelini @Sallaa, Jianwei Zheng)
- [x] Maquettes (Aurore Thomas @aurorethomas, Audrey Henriette @Audreyhrtt, David Galante @folowbaka)
- [ ] Tests automatisés (Corentin Laithier @CorentinLthr )
- [x] Implémentation (Florent Pergoud @flopshoubox)

**Comment by UnexpectedLobster** [comment]
Fonctionnalité pour l'annuaire participatif :
Affecter une personne (item) à une catégorie existante [étudiant, enseignant, laboratoire, ...] (topic)
