### ISSUE TITLE
consult items more easily on mobile phone

### ISSUE THREAD

**Issue by yvan-noume** [Hypertopic/Porphyry#327]
## Content
improve site consultation on mobile by hiding unnecessary parts
Please describe the issue here...

---

## Checklist

Please check that your issue is correctly described:

### Mandatory

- [ ] Its topic must be different from the topic of any other existing ticket (open or closed).
- [ ] The ticket must be written in English.
- [ ] Its title must be as short, as user-centered and as explicit as possible:
    - If it is a feature, the title must be the user action (beginning with a verb, and please not `manage`),
    - If it is a bug, the title must describe the intended behavior (with `should`).
- [ ] It must be labeled with a type:
    - `Feature` for a new behavior,
    - `Fix` for the intended behavior which would be different from the current one,
    - `Refactoring` for the exact same behavior but developed in a different way (for better performance, better maintainability, etc.).

### Optional

- [ ] It may be labeled with the affected page (application screen):
    - `Portfolio page`,
    - `Item page`,
    - `Viewpoint page`.
- [ ] It might be labeled with deprecated pieces of Hypertopic software implementing earlier versions of this `feature`:
    - `Replace LaSuli v2`,
    - `Replace Porphyry v6`.
- [ ] If the ticket is for a suggested `fix`, please help us by providing both the intended behavior and the current one as well as a scenario to reproduce the problem.

**Comment by benel** [comment]
> improve the mobile interface 

Il faut reformuler l'intitulé pour que ce soit l'action **d'un utilisateur** (ce qu'il va pouvoir faire grâce à vous... et qu'il a beaucoup de mal à faire avec la version actuelle).

**Comment by yvan-noume** [comment]
maquette pour l'amélioration de la consultation sur mobile:
page principale:
![a](https://user-images.githubusercontent.com/61839194/81945427-65c71880-95fe-11ea-9fd0-87978ba5ae88.PNG)
<img width="280" alt="81944060-76768f00-95fc-11ea-8f5d-b238692c8074" src="https://user-images.githubusercontent.com/61839194/81945493-78415200-95fe-11ea-8e50-28f1485d2b47.png">
affichage d'un item
![New Wireframe 4 copy 2](https://user-images.githubusercontent.com/61839194/81945558-8db67c00-95fe-11ea-8c9c-ffa893022013.png)

**Comment by yvan-noume** [comment]
**Stratégie d'implémentation**

1. Quelle partie du code sera impactée (classes, méthodes) ?
    plusieurs fichiers seront impactées:
    -portfolio.jsx : le bloc qui gère l'affichage des points de vue
<img width="557" alt="port" src="https://user-images.githubusercontent.com/61839194/82540877-e088ba00-9b4f-11ea-8810-04666bb22d3a.PNG">
   
    -corpora.jsx : le bloc qui gère l'affichage des créateurs d'item
<img width="559" alt="cor" src="https://user-images.githubusercontent.com/61839194/82541121-41b08d80-9b50-11ea-8a21-1ba4bd3ccac0.PNG">

    -attribute.jsx : bloc qui gère la modification des attributs
<img width="527" alt="attr" src="https://user-images.githubusercontent.com/61839194/82541397-b2f04080-9b50-11ea-89e3-aca28b8757ef.PNG">

    -inputWithSuggestions.jsx : bloc qui permet d'ajouter des rubriques
<img width="482" alt="in" src="https://user-images.githubusercontent.com/61839194/82541570-f64aaf00-9b50-11ea-8a45-efe312b85541.PNG">

    -topicPath.jsx : bouton de suppression de rubrique
<img width="566" alt="top" src="https://user-images.githubusercontent.com/61839194/82541812-52153800-9b51-11ea-87ca-ca7a474beb18.PNG">

    -item.jsx : bloc pour la création d'attributs
<img width="412" alt="itm" src="https://user-images.githubusercontent.com/61839194/82541968-84269a00-9b51-11ea-9d25-3e76b7283574.PNG">

2. Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?
Aucune difficulté particulière.

3.Les données dont vous avez besoin sont-elles déjà chargées par la page ?
oui

4.Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?
oui: bootstrap

5.Doit-on intégrer des services extérieurs ?
Non

**Comment by benel** [comment]
>> 4.Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?

> oui: bootstrap

- Pourriez-vous expliciter le principe général qui va permettre avec Bootstrap de cacher des éléments HTML ? 
- N'oubliez pas non plus d'expliquer les raisons de votre choix du point de basculement.

**Comment by yvan-noume** [comment]
> 
> 
> > > 4.Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?
> 
> > oui: bootstrap
> 
>     * Pourriez-vous expliciter le principe général qui va permettre avec Bootstrap de cacher des éléments HTML ?
> 
>     * N'oubliez pas non plus d'expliquer les raisons de votre choix du point de basculement.

Bootstrap propose des classes qui permettent selon la taille de l'écran de l'utilisateur d'afficher ou de cacher un certain  nombres d'élément HTML. Donc il suffit de rajouter ces classes en précisant le point de basculement. 
<img width="476" alt="a" src="https://user-images.githubusercontent.com/61839194/82700889-66e7ed80-9c6f-11ea-8542-33ff9e412b02.PNG">
<img width="607" alt="b" src="https://user-images.githubusercontent.com/61839194/82700900-69e2de00-9c6f-11ea-9628-7320efdd2d2f.PNG">

Le tableau ci-dessus indique les differents classes à utiliser selon la taille de l'écran sur laquelle des éléments seront cachés. La classe choisie est la deuxième qui correspond à cacher certains éléments uniquement sur les plus petit écran. 
Le choix s'est porté vers cette classe parce que d'après les statistiques actuelle, la taille moyenne des écrans est de 5,5 pouce (source :https://www.phonearena.com/news/Average-phone-screen-size-resolution-storage-RAM-report-AnTuTu_id106725).  Ce qui correspond pour bootstrap à des écrans de taille xs.
<img width="617" alt="c" src="https://user-images.githubusercontent.com/61839194/82702240-eb3b7000-9c71-11ea-8750-a4e721f85ea7.PNG">
En convertissant 576px en pouce, on obtient 5,905511811.

Donc le point de basculement a été choisi pour des ecrans de moins de 576px car ce sont les plus répandu actuellement.

**Comment by benel** [comment]
Déployé.
