### ISSUE TITLE
Assign a new topic to an item

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#33]
- [x] Scénarios ( Leo Schneider @leoschneider, Valentin Porcellini @Sallaa)
- [x] Maquettes (Aurore Thomas @aurorethomas, Audrey Henriette @Audreyhrtt, David Galante @folowbaka)
- [ ] Tests automatisés (Corentin Laithier @CorentinLthr)
- [ ] Implémentation (Florent Pergoud @flopshoubox)

**Comment by PymZoR** [comment]
Fonctionnalité pour l'annuaire participatif : 
Affecter une personne (item) à une catégorie [statut, passion, asso, UV ...] (topic)

- [ ] Scénarios
- [ ] Maquettes
- [ ] Tests automatisés
- [ ] Implémentation

**Comment by UnexpectedLobster** [comment]
Fonctionnalité pour l'annuaire participatif :
Affecter une personne (item) à une nouvelle catégorie [association, UV, ...] (topic)

**Comment by benel** [comment]
Pour fluidifier l'intégration, vous pouvez soumettre une pull request pour la fonctionnalité et une autre pour les tests...

**Comment by benel** [comment]
Extrait de : https://github.com/orgs/Hypertopic/teams/porphyry/discussions/2 (par @aurorethomas, @Audreyhrtt, @folowbaka)  

 1. En ajoutant une nouvelle catégorie non existante dans la BDD, aucune suggestion n'est proposée. L'utilisateur peut donc ajouter cette catégorie en appuyant sur le bouton vert, ou ajouter des parents à cette catégorie en appuyant sur la touche entrée.
On commence donc par ajouter la catégorie "Venus" dans le point de vue histoire des religions pour caractériser cet item.
<img width="587" alt="2 - assignnew" src="https://user-images.githubusercontent.com/11554541/40170546-f3992c26-59c8-11e8-9f6f-60b72bcb8c72.png">

   2. Une fois la catégorie non existante saisie, elle est ajoutée et grisée pour permettre d'associer des catégories parent (chemin) à cette dernière. 
<img width="586" alt="3 - assignnew" src="https://user-images.githubusercontent.com/11554541/40170558-fab98f00-59c8-11e8-818a-5e2e12beed63.png">

   3. On associe donc ensuite la catégorie parent "Personnages" à la catégorie "Venus". 
<img width="589" alt="4 - assignnew" src="https://user-images.githubusercontent.com/11554541/40170570-02c1e594-59c9-11e8-8681-1909c3cf8065.png">

   4. Une fois la catégorie parent existante saisie et ajoutée pour caractériser la nouvelle catégorie, elle est ajoutée et grisée (voir 2.) pour permettre d'associer d'autres catégories parent (chemin) à cette dernière. 
<img width="588" alt="5 - assignnew" src="https://user-images.githubusercontent.com/11554541/40170586-10b1df38-59c9-11e8-9676-f8b80a199081.png">

   5. Une fois l'utilisateur satisfait du chemin des catégorie caractérisant l'item, il peut alors cliquer sur le bouton vert (valider) afin d'ajouter le chemin de cette nouvelle catégorie descriptive à l'item.
<img width="587" alt="6 - assignnew" src="https://user-images.githubusercontent.com/11554541/40170604-1d12dc00-59c9-11e8-8357-0f86cabff82f.png">
N'hésitez pas à nous faire des retours ou remarques sur ces maquettes avant le développement imminent de ces fonctionnalités.

**Comment by benel** [comment]
Si j'ai bien compris, la fonctionnalité avait été implémentée mais malheureusement suite à une mauvaise manipulation, la personne qui l'avait développée a perdu le code correspondant.

**Comment by benel** [comment]
Implemented by 18474e8.
