### ISSUE TITLE
Consult items on a static geographical map

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#333]
## Content

As a team member of @Hypertopic/graines-d-artistes, @macchrd would like users to see selected items on a **static** geographical map (depending on their `spatial` attribute) instead of as a list of names or thumbnails.

This feature is a simplified version of #121 since the map is **not interactive** _per se_ (only by changing the selection on Pophyry). 

@Hypertopic/graines-d-artistes, don't forget to implement acceptance tests, to assure that future implementation of #121 would not break this feature you asked for. 

---

### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
### Phase 2
- [ ] Acceptance tests (Capybara)
- [x] Implementation

**Comment by benel** [comment]
Deployed.

**Comment by Kodlah** [comment]
### Phase 1

- [X]  Scenarios (Gherkin)

- [X]  Mockups

- [X]  Implementation strategy

 ### Phase 2

- [ ]  Acceptance tests (Capybara)

- [x]  Implementation

**Comment by benel** [comment]
@Kodlah Was the acceptance test written and integrated?

**Comment by Kodlah** [comment]
> 
> 
> @Kodlah Was the acceptance test written and integrated?

No, not yet ! Sorry, I removed the checked box above.
