### ISSUE TITLE
Unassign a topic from an item

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#34]
- [x] Scénarios (Valentin Porcellini @Sallaa , Léo Schneider @leoschneider)
- [x] Maquettes (Aurore Thomas @aurorethomas, Audrey Henriette @Audreyhrtt)
- [ ] Tests automatisés (Corentin Laithier @CorentinLthr)
- [x] Implémentation (Florent Pergoud @flopshoubox)

**Comment by davp01x** [comment]
Fonctionnalité pour l'annuaire participatif :
Enlever une catégorie [association, UV, ...] (topic) à une personne/un profil (item)
