### ISSUE TITLE
Consult items with custom geocoded entities on a map

### ISSUE THREAD

**Issue by SorelMboua** [Hypertopic/Porphyry#349]
## Content

As a team member of @Hypertopic/archeologie-grecque , @SorelMboua would like users to see selected items on a personal static map which does not use google maps services.

This feature is an upgraded version of #121 since we have custom geographical entities, that we need to be geocoded (in order to have a position on a map) but that are unknown to third party services.

---

## Phase 1

- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy

## Phase 2
- [ ] Acceptance tests (Capybara)
- [x] Implementation

**Comment by benel** [comment]
> As a team member of @Hypertopic/archeologie-grecque , @SorelMboua would like users to see selected items on a personal static map which does not use google maps services.
This feature is an upgraded version of #121 since the map is not geographical and cannot use longitude and latitude or addresses for the creation of markers.

@Hypertopic/archeologie-grecque To make the description clearer, you should tell that you have **custom** geographical entities, that you would need to be **geocoded** (in order to have a position on a map) but that are unknown to third party services.

**Comment by albertelombo** [comment]
En tant que membre du groupe des journées du patrimoine je propose de pouvoir consulter les articles à partir de codes donnant des indications sur leur localisation sur une carte afin de mettre à profit la nomenclature des photos de vitraux qui est liée à leur position dans l'édifice.

**Comment by benel** [comment]
> En tant que membre du groupe des journées du patrimoine je propose de pouvoir consulter les articles à partir de codes donnant des indications sur leur localisation sur une carte afin de mettre à profit la nomenclature des photos de vitraux qui est liée à leur position dans l'édifice.

@albertelombo Le ticket pourrait effectivement être pertinent pour votre situation d'usage (les entités géocodées seraient alors les "baies", c'est-à-dire les fenêtres). Par contre, comme nous l'avons vu pendant la réunion, ce serait très coûteux humainement en création de données (il faudrait que quelqu'un aille mesurer les coordonnées GPS précises de chaque baie : il y en a déjà une centaine pour l'édifice qui sera visité le jour J... et imaginez si on veut généraliser un jour l'approche au corpus des 1800 photographies...). Comme on l'a vu en réunion, d'autres solutions du ticket #369 semblent plus réalistes.

**Comment by ianbialo** [comment]
En tant que membre du groupe du projet @Hypertopic/kerameikos, il est je pense intéressant de représenter les différents vases sur les sites de fouilles de manière à ce que l'on puisse se rendre compte facilement de leurs positions.

**Comment by benel** [comment]
> En tant que membre du groupe du projet @Hypertopic/kerameikos, il est je pense intéressant de représenter les différents vases sur les sites de fouilles de manière à ce que l'on puisse se rendre compte facilement de leurs positions.

@biaolan Effectivement. C'est pour cela que @florian-dehe l'avait déjà ajouté à votre kanban.

Pour argumenter à propos de son utilité dans votre projet, notez que dans votre cas, les entités à géocoder sont les tombes des deux nécropoles du site. Si les tombes sont géocodées, cela permettra d'utiliser directement le nom de la tombe dans la description de chaque item (et non les coordonnées en longitude et latitude, ce qui ne serait guère commode).

**Comment by Kryddd** [comment]
Mockup avec @florian-dehe

![Home](https://user-images.githubusercontent.com/32571260/118243797-20eaf180-b49f-11eb-9d4b-7bf0c0a8a3f2.png)
![Home - clicked](https://user-images.githubusercontent.com/32571260/118243824-2a745980-b49f-11eb-8fd6-9cbb442618ac.png)

Cette feature ne change rien visuellement, en théorie, puisqu'elle n'affecte que la provenance des coordonnées à afficher sur la carte.

**Comment by Kryddd** [comment]
# Stratégie d'implémentation
Avec @florian-dehe 
## Quelle partie du code sera impactée (classes, méthodes) ?
Le code à modifier pour pouvoir afficher des entités inconnues par l'API de geocoding de Google se trouve exclusivement dans [src/components/portfolioPage/GeographicMap.jsx](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/GeographicMap.jsx)

La modification à effectuer se trouve dans les méthodes _fetchPlaces et fromAddress :
https://github.com/Hypertopic/Porphyry/blob/f73e48917603edb95de94457f153e86b66016451/src/components/portfolioPage/GeographicMap.jsx#L74-L93

La version actuelle de Porphyry utilise l'API de geocoding de Google via le package [react-geocode](https://github.com/shukerullah/react-geocode). A l'avenir, l'API [GeoXEne](https://github.com/Hypertopic/GeoXEne) permettra de géocoder des adresses inconnues par les services de Google.

## Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?
Le changement à effectuer reste très simple, puisqu'il suffit de remplacer l'utilisation du package react-geocode par un appel à une API.

## Les données dont vous avez besoin sont-elles déjà chargées par la page ? Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ? Si non, quelle sera la requête la plus efficace et comment allez-vous récupérer dans la structure de données précisément celles qui vous intéressent ?

GeoXEne utilisera l'attribut spatial des items. Aucune modification ne sera nécessaire sur cet aspect puisque l'attribut est déjà structuré correctement pour être utilisé par react-geocode : 
https://github.com/Hypertopic/Porphyry/blob/f73e48917603edb95de94457f153e86b66016451/src/components/portfolioPage/GeographicMap.jsx#L19

## Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ?
L'appel à GeoXEne peut être fait avec un simple fetch. L'ajout d'une dépendance ne paraît donc pas nécessaire dans cette situation.

## Comme dans notre séance sur le développement, vous pouvez tester des petits bouts de code indépendants et les associer à votre stratégie (avec éventuellement des exemples de données, voire même des temps d'exécution).

On peut tester le fonctionnement de GeoXEne et afficher le résultat sur une carte avec le code React suivant :
``` javascript
import React from 'react';
import { GoogleMap, Marker, LoadScript } from '@react-google-maps/api';

class App extends React.Component {
  state = {
    place: []
  };

  componentDidMount() {
    fetch('http://localhost:2999/?address=Tombe 2, Pompeion, Kerameikos') // GeoXEne
      .then(response => response.json())
      .then(data => this.setState({ place: data.results[0].geometry.location }));
  }

  render() {
    let marker = <Marker position={this.state.place} />
    return (
      <LoadScript googleMapsApiKey={process.env.REACT_APP_MAP_API_KEY} >
        <GoogleMap
          mapContainerStyle={{ width: '100%', height: '600px' }}
          center={this.state.place}
          zoom={16}
        >
          {marker}
        </GoogleMap>
      </LoadScript>
    );
  }
  
}

export default App;
```

## Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?

Le service [GeoXEne](https://github.com/Hypertopic/GeoXEne) sera utiliser. GeoXEne permet de géocoder des lieux à partir d'un attribut au format [spatial](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/spatial/). L'API GeoXEne fait office de proxy pour l'API de geocoding de Google lorsqu'il ne connait pas l'attribut spatial à géocoder.
L'API s'appelle par une requête GET à l'URI suivante : 
`http://{Nom de domaine de GeoXEne}/?address={Attribut spatial à géocoder}`

## Des étapes préalables de développement, testables, sont-elles envisageables afin de diminuer la complexité de la livraison ? Refactoring (livrable à part entière, isofonctionnel) ? Code développable et testable de manière externe au logiciel ? Étape du scénario (non livrable en tant que tel mais dont l"effet peut être testé) ?
Pour pouvoir mettre en place cette solution en production, il faut que GeoXEne soit déployé.

**Comment by benel** [comment]
@Kryddd Votre stratégie d'implémentation est plutôt pas mal, si ce n'est que l'on ne comprend pas comment vous allez spécifier l'adresse de GeoXEne (ou à défaut de l'API de Google puisque les deux sont compatibles). En effet, jusqu'à maintenant on n'avait pas à se poser la question puisque react-geocode interrogeait toujours le même serveur.

**Comment by Kryddd** [comment]
@benel Concenant la stratégie d'implémentation, l'adresse de GeoXene pourra être stockée dans le fichier `config.yml`. Il pourra donc être accessible de la même façon que la clé d'api google dans [GeographicMap.jsx](https://github.com/Hypertopic/Porphyry/blob/f73e48917603edb95de94457f153e86b66016451/src/components/portfolioPage/GeographicMap.jsx) : `conf.geocodingService`, par exemple.
Mettre l'URI de GeoXEne dans le fichier de configuration plutôt que de le coder en dur permettra d'interchanger le service par Google Maps si le corpus utilisé ne géocode pas ses items ou si l'API GeoXEne n'est pas disponible.

**Comment by benel** [comment]
@Kryddd 
> Mettre l'URI de GeoXEne dans le fichier de configuration plutôt que de le coder en dur permettra d'interchanger le service par Google Maps si le corpus utilisé ne géocode pas ses items ou si l'API GeoXEne n'est pas disponible.

Super ! C'est tout à fait ça. 

Vous avez donc plusieurs cas : 
- pas de service de cartographie (donc pas de carte affichée),
- le service de géocodage de GoogleMaps,
- un service de géocodage de son choix (par exemple n'importe quelle instance de GeoXEne) du moment qu'il est compatible avec GoogleMaps.

> conf.geocodingService, par exemple.

Ce serait peut-être pas mal de regrouper tout ce qui a trait à la cartographie...

**Comment by Kryddd** [comment]
@benel 
(avec @alca-creator )
Pour être sûr que nous ayons bien compris :
- pas de service de cartographie (donc pas de carte affichée), -> interactiveMap  ou staticMap ne sont pas définis dans config.yml
- le service de géocodage de GoogleMaps, -> Aucun service de géocoding n'est défini dans config.yml
- un service de géocodage de son choix (par exemple n'importe quelle instance de GeoXEne) du moment qu'il est compatible avec GoogleMaps. -> l'URI vers un service de géocoding est défini dans config.yml

> regrouper tout ce qui a trait à la cartographie...  

Est ce que ça veut dire regrouper les paramètres liés à la cartographie ensemble dans le config.yml ? Dans ce cas, on aurai une structure du type  `conf.map.interactiveMap` ,`conf.map.geocodingService`, ...
Dans ce cas là, ça pose un problème si on met à jour les plateformes Porphyry existantes puisqu'il faudra changer la structure de config.yml pour qu'ils puissent fonctionner correctement.

**Comment by benel** [comment]
@Kryddd @alca-creator 

> pas de service de cartographie (donc pas de carte affichée), -> interactiveMap ou staticMap ne sont pas définis dans config.yml

OK.

> un service de géocodage de son choix (par exemple n'importe quelle instance de GeoXEne) du moment qu'il est compatible avec GoogleMaps. -> l'URI vers un service de géocoding est défini dans config.yml

OK.

> le service de géocodage de GoogleMaps, -> Aucun service de géocoding n'est défini dans config.yml

Pas forcément... Pour éviter de donner un avantage à Google par rapport à ses concurrents éventuels, on peut supprimer ce cas et du coup se rabattre sur le précédent quand on veut utiliser GoogleMaps.

> Est ce que ça veut dire regrouper les paramètres liés à la cartographie ensemble dans le config.yml ? Dans ce cas, on aurai une structure du type conf.map.interactiveMap ,conf.map.geocodingService, ...

Oui, par exemple... On peut même le précéder d'un petit _refactoring_ (je peux m'en charger) pour supprimer les cartes statiques (qui ne sont quasiment plus utilisées) et donc simplifier un peu le nom de la clé.
Du coup, on a besoin de la clé d'API et de l'URI du service de geocoding pour cette fonctionnalité. Tandis que la fonctionnalité #272 aura besoin de la liste des calques (et c'est un peu plus compliqué puisque là c'est portfolio par portfolio).

> Dans ce cas là, ça pose un problème si on met à jour les plateformes Porphyry existantes puisqu'il faudra changer la structure de config.yml pour qu'ils puissent fonctionner correctement.

C'est exact. Ceci dit pour l'instant c'est gérable ;)

**Comment by Kryddd** [comment]
Bonjour M. @benel ,
Maintenant que tous les points de la stratégie d'implémentation sont clarifiés, et avec l'accord de l'équipe, nous passons maintenant à la phase 2 du projet.

**Comment by benel** [comment]
@Kryddd @Hypertopic/kerameikos 

> Maintenant que tous les points de la stratégie d'implémentation sont clarifiés

OK. Je coche le livrable.

> et avec l'accord de l'équipe, nous passons maintenant à la phase 2 du projet.

En toute rigueur le scénario n'est [pas terminé](https://github.com/Hypertopic/Porphyry/pull/504#issuecomment-850283418) (même s'il ne manque pas grand chose, il faut le faire).

Soit vous attendez (ou vous aidez le binôme à terminer le scénario), soit vous passez sur le ticket suivant...

**Comment by benel** [comment]
@Kryddd @Hypertopic/kerameikos 

Je suis désolé d'être un peu psychorigide sur l'application de la méthode Lean/Kanban, mais comme le projet d'IF05 n'est qu'un "prétexte" pour que vous vous appliquiez la méthode. Je suis obligé...
Là ce n'est qu'une affaire de 15-30 minutes d'attente, mais c'est bien de savoir que de manière générale, il est préférable d'attendre ou d'aider les autres qui ont avancé moins vite que de se précipiter sur une nouveau livrable (ce qui est un peu contre-intuitif).

**Comment by benel** [comment]
Bonne nouvelle @Hypertopic/kerameikos ! GeoXEne est en production (en https, avec le nom de domaine de l'UTT).

**Comment by benel** [comment]
Félicitations @florian-dehe @franckfotso1 @ClemUTT ! 🎉
Votre scénario est intégré !

**Comment by benel** [comment]
Félicitations @franckfotso1 @Kryddd ! Votre implémentation de la fonctionnalité est en production ! 🎉

**Comment by benel** [comment]
La fonctionnalité est en production 🎉

**Comment by franckfotso1** [comment]
### **Acceptance tests**
Mr @benel , avec @alca-creator  nous avons proposé ceci comme première version de tests manuels
![test](https://user-images.githubusercontent.com/73475604/122180056-62006800-ce88-11eb-9a1a-2b41698e377c.PNG)

**Comment by benel** [comment]
Merci @franckfotso1 et @alca-creator pour cette grille.

Je vois que vous avez adopté un formalisme de "requirements". Ça existe effectivement en génie logiciel. Cependant ce n'est pas l'approche d'IF05 qui veut que (selon les principes agiles) tous les livrables puissent avoir du sens et de la valeur pour l'usager.

Dans votre cas, ma demande est seulement que vous décriviez à un utilisateur, quelles sont les actions qu'il doit faire sur l'interface pour vérifier que les scénarios écrits par vos camarades sont bien implémentés dans la version actuelle de Porphyry.

D'accord ?

**Comment by franckfotso1** [comment]
Mr @benel , Après la prise en compte de vos remarques, nous avons modifié nos tests afin de donner plus de sens pour l'usager.
Ainsi, notre test manuel prend la forme suivante :

1. Modifier le fichier configuration public/config.yml et compléter avec GeoXene : 

user: vases
services:
  - https://argos.utt.fr
  - https://steatite.utt.fr
map:
  key: CLE_API_GOOGLE
  geocodingService: https://geoxene.utt.fr

2. Ouvrir/lancer Porhyry ( npm start dans le terminal)

3. Écrire dans la barre de recherche le nom d'un vase ( ou celui d'une tombe)
Ex: (donnée de GeoXEne): "Tombe 2, Pompeion, Kerameikos": { lat: 37.97824388117687, lng: 23.718648807908984 },

4. Une liste avec les mots clés rentrés précédemment s'affiche

5. Cliquer sur l'élément de la liste nommé "nom : nom du vase"

6. Le vase s'affiche sur la page

7. Cliquer sur le vase

8. Une carte devrait se trouver sur la page avec un symbole marquant la position du vase

9. Passer sa souris sur le symbole présent sur la carte

10. La latitude et la longitude du vase devrait s'afficher sur la carte

**Comment by franckfotso1** [comment]
Mr @benel j'aimerai faire valider mes activités ( Écrire une application en React) et (le Git-Graal), comment puis-je le faire ? êtes vous disponible en présentiel cette après midi ou puis je faire un partage d'écran ?

**Comment by benel** [comment]
@franckfotso1 Comme ça n'a pas vraiment de rapport à le ticket, j'ai répondu à votre question ici : https://github.com/orgs/Hypertopic/teams/if05-p21/discussions/3

**Comment by benel** [comment]
@Hypertopic/kerameikos

Avez-vous réussi (avec ou sans l'aide de M. Luce) à trouver la correspondance entre les nécropoles indiquées dans le point de vue "provenance" et vos deux calques ?

Si oui, êtes-vous au clair sur les différentes étapes nécessaires pour monter une démo autour de quelques vases trouvés dans des tombes de ces deux nécropoles ?

**Comment by Kryddd** [comment]
Nous n'avons pas encore pu prendre contact avec M. Luce mais nous pouvons tout de même faire une démonstration de la fonctionnalité avec des données potentiellement fausses. Il nous suffit d'utiliser une version modifiée de GeoXEne en local.

**Comment by benel** [comment]
> nous pouvons tout de même faire une démonstration de la fonctionnalité avec des données potentiellement fausses. 

Certes, mais ça fera beaucoup moins d'impression à M. Luce. Ce serait vraiment dommage, alors que c'est faisable en vraiment peu de temps.

J'ai regardé de mon côté... Apparemment : 
- la catégorie [KER NORD Eridanos](https://vases.porphyry.org/?t={%22type%22:%22intersection%22,%22data%22:[{%22type%22:%22intersection%22,%22selection%22:[%2213ae085b86924fc0a3d2b5c55b20310b%22],%22exclusion%22:[]}]}) correspondent à votre grande plan,
- et la catégorie [KER Sud Eridanos 2 PG](https://vases.porphyry.org/?t={%22type%22:%22intersection%22,%22data%22:[{%22type%22:%22intersection%22,%22selection%22:[%227e3837e33fa241a48f831a9da4a5c5af%22],%22exclusion%22:[]}]}) au petit plan.

Je vous laisse vérifier que les numéros dans les sous-catégories correspondent à peu près aux numéros sur les plans.

Voici les différentes étapes : 
- Pour chaque plan : 
  - Sélectionner la catégorie correspondante.
  - Pour quelques vases sélectionnés : 
    - noter pour la suite le numéro de tombe (qui apparait dans la catégorie) ,
    - remplir l'attribut `spatial` avec le numéro de tombe et le nom de la nécropole (ex : `Tombe 1, Nécropole au Nord de l'Eridanos, Kerameikos`),
    - noter à part ce nom de lieu pour plus tard par exemple dans un tableau.
- Lancer le GeoXene de test.
- Pour chaque valeur de `spatial` notée précédemment : 
  - cliquer sur la carte la tombe correspondante, copier les coordonnées qui apparaissent dans la console, et la coller dans un tableau en face du nom de lieu,
  - mettez à jour les correspondances entre noms de lieux et les coordonnées qui sont indiquées dans GeoXene.

Ça va aller ?

**Comment by benel** [comment]
@Hypertopic/kerameikos 

J'en ai fait quelques uns pour la nécropole au Nord de l'Eridanos (grand plan).
<img width="1361" alt="Capture d’écran 2021-06-24 à 17 52 44" src="https://user-images.githubusercontent.com/597307/123294340-0af83400-d515-11eb-9a1d-aac5501caee5.png">
Je vous laisse en faire quelques un pour celle au Sud de l'Eridanos (petit plan) ?

**Comment by Kryddd** [comment]
J'ai fait la même chose de mon côté : 
![205522158_499714624473071_7668695166142516350_n](https://user-images.githubusercontent.com/32571260/123295358-ef415d80-d515-11eb-87a4-a09c3128de48.png)
Cependant, pour la nécropole au Sud de l'Eridanos, je n'ai pas les informations sur quel vase appartient à quelle tombe.

**Comment by Kryddd** [comment]
J'ai fait la même chose de mon côté pour la nécropole au Nord de l'Eridanos : 
![205522158_499714624473071_7668695166142516350_n](https://user-images.githubusercontent.com/32571260/123296074-9d4d0780-d516-11eb-9799-c2e380732646.png)

Je vais continuer sur les vases au Sud de l'Eridanos

**Comment by benel** [comment]
> Cependant, pour la nécropole au Sud de l'Eridanos, je n'ai pas les informations sur quel vase appartient à quelle tombe.

Comme je l'indiquais plus haut, vous les avez apparemment dans `KER Sud Eridanos PG`:

<img width="400" alt="Capture d’écran 2021-06-24 à 18 10 46" src="https://user-images.githubusercontent.com/597307/123297098-8c50c600-d517-11eb-9cd7-17936e279a34.png">

Les numéros que vous voyez ci-dessus sont ceux des tombes. Quand vous cliquez dessus, vous avez les vases.

**Comment by benel** [comment]
Comme je l'ai indiqué, il y a un bug avec les apostrophes droites. C'est pourquoi j'ai utilisé les courbes en attendant.

Mais le comportement de GoogleMaps est curieux quand on clique sur un marqueur...

**Comment by Kryddd** [comment]
J'ai rajouté un attribut spatial à certains vases au Sud de l'Eridanos correspondant aux données dans [la pull request faite sur GeoXEne](https://github.com/Hypertopic/GeoXEne/pull/7)
Démo avec les tombes au Sud de l'Eridanos : 
![203655365_197112198985911_2363836969128181387_n](https://user-images.githubusercontent.com/32571260/123311309-4f8ccb00-d527-11eb-8af4-528e1671c4ce.png)

**Comment by benel** [comment]
> J'ai rajouté un attribut spatial à certains vases au Sud de l'Eridanos correspondant aux données dans la pull request faite sur GeoXEne.

Bravo @Kryddd ! 

C'est tout de suite plus impressionnant avec de vraies données !

<img width="1424" alt="Capture d’écran 2021-06-24 à 22 49 54" src="https://user-images.githubusercontent.com/597307/123330664-976b1c80-d53e-11eb-9d85-abefc63989d4.png">

Je ne pensais pas que vous en ajouteriez autant. C'est super, comme cela vous allez pouvoir faire des démonstrations plus intéressantes en sélectionnant par exemple une caractéristique et en voyant le résultat sur la carte/

<img width="1424" alt="Capture d’écran 2021-06-24 à 22 52 34" src="https://user-images.githubusercontent.com/597307/123330912-e87b1080-d53e-11eb-96fd-afc0851b2cff.png">
