### ISSUE TITLE
"Go back" should link to selected items (instead of all items)

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#368]
# Rationale

"Go back to home page" links to the portfolio with all items (i.e. with an empty selection).
The text is quite clear on what it does, however it is surprising in the way that it "breaks" the navigation logic.

# Workarounds

- Use the browser "back" button instead.
- Open items in new tabs (and eventually close them to go back to the original tab).

# Deliverables status

## Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
## Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

**Comment by qhainos** [comment]
**Dans le cadre du projet Porphyry**, et dans un cadre de navigation "agréable" pour les utilisateurs (de toutes applications en général), il est important que le bouton "back" ramène ces derniers à leur sélection d'items plutôt qu'à la liste de tous les items non filtrés, afin de ne pas lui faire faire une nouvelle recherche à chaque consultation d'item, ou de le forcer à ouvrir ces items dans un nouvel onglet (plus compliqué sur mobile).
**Dans le cadre des journées du patrimoine**, cette correction prend son sens dans le cas ou un utilisateur qui filtre ses items veut certainement voir plusieurs vitraux liés entre eux (par date, style, ou lieu). Le forcer à refaire sa sélection pour chaque vitrail serait décourageant et contre productif.

**Comment by benel** [comment]
> Dans le cadre des journées du patrimoine, cette correction prend son sens dans le cas ou un utilisateur qui filtre ses items 

En plus, dans votre cas, probablement, l'utilisateur arrivera dès le départ avec un filtre activé : celui de l'édifice...

**Comment by benel** [comment]
Implémentation partielle (dans le cas des plans d'édifice mais pas dans le cas plus général de la planche contact) dans f68d4fedf3fa7b0ccafcb0f1a8f77db7fbb2962e.

**Comment by Yunrayz** [comment]
Maquette : 

![maquette368](https://user-images.githubusercontent.com/46678149/172885711-0d839ef9-2114-44dd-a503-f22b3fe461b6.png)



Proposition de stratégie d'implémentation :
- Ajouter un props "selectedURI" à item.jsx
- Lorsque l'on clique sur un item, on récupère l'URI et la passe via le state du link du routeur
- Lors de l'appui sur "Retour à l'accueil", on récupère l'URI stocké pour récupérer les sélections

**Comment by benel** [comment]
> Implémentation partielle (dans le cas des plans d'édifice mais pas dans le cas plus général de la planche contact) dans https://github.com/Hypertopic/Porphyry/commit/f68d4fedf3fa7b0ccafcb0f1a8f77db7fbb2962e.

En plus d'être moins général, le retour au plan des édifices ne fonctionne pas quand on navigue d'items en items de même nom. Il faudra prévoir le cas dans vos scénarios

**Comment by benel** [comment]
> En plus d'être moins général, le retour au plan des édifices ne fonctionne pas quand on navigue d'items en items de même nom. Il faudra prévoir le cas dans vos scénarios

Please note that a temporary fix (f6222b674aa34bde8774c3409b21fdd4e9816ebc) was brought so that "Browsing to same name items should not prevent from going back to the building map".

It will be replaced by your more general fix.

**Comment by Yunrayz** [comment]
https://user-images.githubusercontent.com/46678149/171654717-06996c70-cd72-4481-9d65-2e9052e9a23d.mp4

Vidéo du bug fix

**Comment by benel** [comment]
@Hypertopic/gravures-antiques-sur-pierres-fines 
Moving the ticket to "Done" is supposed to mean that you sent me a pull request and that I have accepted to review it. 
For now, I haven't seen any 🙄

**Comment by Yunrayz** [comment]
https://user-images.githubusercontent.com/46678149/172875960-234555c8-9337-462f-a003-c7bb92d171b4.mp4

Live exemple of the fix with audio description (French)

**Comment by Caramella-ICE** [comment]
Exemple of selection when consulting an item with the same name name in an item page.

https://user-images.githubusercontent.com/91554187/172879757-b6e6f8d9-c63d-4d3f-8583-33d9ff19caee.mp4
