### ISSUE TITLE
The attributes of an item shared must become hashtags

### ISSUE THREAD

**Issue by YaellePihan** [Hypertopic/Porphyry#372]
#### What is the valuable outcome that cannot be achieved with current features?
Lors du partage d'un item sur facebook, cela permet d'avoir des hashtags ajoutés automatiquement dans l'espace dédié par facebook à cet effet. Ces hashtags correspondent à des attributs de l'item devant être partagé sur facebook. 

#### For which stakeholder (people, role, project, domain) is it important? 
C'est important pour la chargée de communication car cela représente un gain de temps en comparaison à une entrée manuelle des hashtags. 
#### Which user action should be enabled (or restricted)? For who?
Pour la chargée de communication et ses collègues.
#### Phase 1
- [ ] Scenarios (Gherkin)
Etapes pour accéder à cette fonctionnalité : 
- sélectionner un item
- cliquer sur partager l'item sur facebook
- voir une fenêtre apparaître avec tous les attributs de l'item
- sélectionner les attributs qui deviendront des hashtags sur facebook
- voir l'aperçu de facebook montrant l'item et les hashtags ajoutés
- publier sur facebook
- [ ] Mockups
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

**Comment by YaellePihan** [comment]
We are the team of @Hypertopic/cite-du-vitrail, we want to give the possibility to users to have the attributs of an item they want to share, added as hashtags to their post. The user we have thought of is the communication manager so that he/she can share items easier but also common people.

**Comment by benel** [comment]
@YaellePihan @Hypertopic/cite-du-vitrail 

- Vous pouvez modifier le commentaire initial pour mettre les différents éléments de réponse sous les questions correspondantes.
- Je ne suis pas complètement certain d'avoir compris ce que vous avez en tête : c'est lors d'un partage d'un item sur un réseau social qui gère les hashtags ?
- Pour la visée, montez en abstraction. La simplicité ne suffit pas. En quoi cette fonctionnalité concourt aux missions de la Cité du Vitrail et plus particulièrement de la chargée de communication ?

**Comment by YaellePihan** [comment]
j'ai modifié ce ticket le 30 avril en réponse à votre commentaire, j'ajoute que suite à notre entretient avec la chargée de communication Fanny Portier, ce ticket avait été retenu : elle n'utilisait jusqu'alors pas les hashtags mais trouvait cela pertinent pour augmenter la qualité de ses publications.

**Comment by benel** [comment]
En quoi est-ce différent de ce que votre équipe est en train d'implémenter dans le ticket #373 ? @YaellePihan

**Comment by benel** [comment]
Ou alors, c'est pour faire pour les attributs ce que vous faites déjà pour les catégories ?

**Comment by benel** [comment]
Ou alors c'est pour faire sur Facebook ce que vous faites sur Instagram ?
