### ISSUE TITLE
Allow the User to go on Instagram with an Icon on Disqus Plugin

### ISSUE THREAD

**Issue by LSauter68140** [Hypertopic/Porphyry#374]
### Description

We want to add a icon Instagram to be able to share a stained-glass window on this social network

#### We allow this feature only for the mobile User 
Because on desktop we can't publish anything on Instagram web version

#### Phase 1
- [ ] Mock ups
- [ ] Scenarios (Gherkin)
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

**Comment by benel** [comment]
@LSauter68140 

> Add a Instagram Icon on Disqus Plugin

- Une fonctionnalité c'est ce que le logiciel permet à l'usager de faire. Or ce n'est pas lui/elle qui va ajouter l'icone, c'est vous... Il faudrait reformuler le titre de sorte que le sujet implicite du verbe soit l'usager. 
- Par ailleurs, n'oubliez pas le critère "n" de INVEST. Peut-être qu'il existe plusieurs moyens techniques et plusieurs rendus visuels pour que l'usager fasse ce qu'il a envie de faire.

> [x] Scenarios (Gherkin)

La case est cochée... Vous avez déjà implémenté le scénario Gherkin ? On ne verra ce que c'est que début avril...


Enfin pensez à argumenter en quoi cette fonctionnalité serait nécessaire pour le projet @Hypertopic/cite-du-vitrail 
Cela correspond à la première ligne des "user sorties" (la "visée").

**Comment by LSauter68140** [comment]
Cette implémentation permettra à l'utilisateur d'être redirigé vers Instagram sur la page de l'aube pour les vitraux (demande de la partie prenante ). On a aussi ajouté un ticket en lien avec celui ci qui permettra d'expliquer à l'utilisateur comment partager un vitrail sur son Instagram (non disponible nativement sur la plateforme et nécessite de télécharger manuellement l'image du vitrail)

**Comment by benel** [comment]
@LSauter68140 N'oubliez pas de changer le titre du ticket pour qu'il suive les règles de formulation d'une fonctionnalité.
