### ISSUE TITLE
Show the item's picture on a Facebook publication

### ISSUE THREAD

**Issue by manacheh** [Hypertopic/Porphyry#375]
### Description
If an user wants to share an item from Porphyry to Facebook, the publication on Facebok will show the shared item.

#### What is the valuable outcome that cannot be achieved with current features?
Currently, the publication on Facebook only contains a link to the item on Porphyry.

#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Mockups
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

**Comment by benel** [comment]
@manacheh @Hypertopic/cite-du-vitrail Si vous rédigez le ticket sous forme d'une fonctionnalité, le verbe doit être tel que son sujet implicite soit l'usager (en effet ce n'est pas l'usager qui va "montrer").
Autrement vous auriez pu également le rédiger sous forme d'un FIX (la structure [un peu différente](https://github.com/Hypertopic/Porphyry/blob/v7/.github/ISSUE_TEMPLATE/fix-request.md) est peut-être plus adaptée).

Pour la visée, il faudrait aussi monter un peu en abstraction : Quelle est la conséquence (par rapport aux missions de la Cité du vitrail et plus particulièrement à celles de la chargée de communication de cette absence d'image dans les partages sur Facebook) ?
