### ISSUE TITLE
The picture of a shared item is not visible on a Facebook publication 

### ISSUE THREAD

**Issue by manacheh** [Hypertopic/Porphyry#380]
### Description
When an user shared an item from Porphyry to Facebook, the picture of this item is not visible in the Facebook publication.

#### What is the valuable outcome that cannot be achieved because of this bug?
The post on Facebook does not contain any indication of the shared item which makes the post very vague and not very intuitive.

#### For which stakeholder (people, role, project, domain) is it important?
This is important for anyone (professional or not) who regularly shares items. The absence of the item's photo makes the publication less impactful. 

#### Reproduction scenario
4. See error (if applicable, add screenshots to help explain your problem).

#### Environment
 - OS: [e.g. Windows 10, macOS 10.15, iOS]
 - Browser: [e.g. chrome 88, safari 14]

#### Workaround
Solution you found to avoid the problem.

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Implementation strategy
- no mockup (fix)

#### Phase 2
- [x] Implementation
- [ ] manual tests

**Comment by manacheh** [comment]
Team ''Cité du Vitrail'' :
According to the stakeholder, showing the picture of a shared item is necessary because visitor's attention needs to be attracted. 
The ''Cité du Vitrail'' , being a project which the purpose is to make stained glass accessible for everyone, the lack of picture is a handicap for this one.

**Comment by Toine-prog** [comment]
Voici deux versions possibles des scénarios pour la fonctionnalité "Partager un item sur Facebook".
@benel 

[Scenario_Facebook.txt](https://github.com/Hypertopic/Porphyry/files/6509263/Scenario_Facebook.txt)

**Comment by benel** [comment]
Merci @Toine-prog pour cette première version de scénario.

N'hésitez pas à mettre du code directement dans les commentaires... 
Pensez aussi à mentionner l'autre personne du binôme qui l'a écrit avec vous.

> Cas où il n'est pas possible de partager un item sur Facebook directement à partir de Porphyry

En fait cette notion de "cas" existe dans Cucumber. C'est ce qu'ils appellent `Scénario`.

> Scénario: téléchargement de l'image
> Scénario: Entrer dans Facebook
> Scénario: Créer une publication sur Facebook

Ma première remarque nous amène à ma seconde : vous avez mis dans des scénarios différents des étapes qui devraient être dans le **même** scénario.

C'est une erreur assez classique des gens qui débutent avec le BDD : vous avez été troublé par le fait qu'il n'y ait qu'un seul "Quand" alors que vous avez une série d'opérations exécutées par l'utilisateur (cliquer, remplir, etc.).
La solution est qu'il ne faut pas se focaliser sur les opérations élémentaires, mais sur des actions de plus haut niveau.
En général, vous n'avez pas trop à chercher... Le nom de l'action dans le "Quand" est précisément celle de la fonctionnalité. Vous avez écrit "Partager un item sur Facebook" comme nom de la fonctionnalité. C'est tout à fait de ce genre.
Mais alors à quoi ça sert de faire un scénario ? Justement pour choisir toutes les données d'exemple (celles qui doivent apparaître entre guillemets) et qui vont permettre de mesurer la différence entre le résultat et les prérequis, ce qui permet d'illustrer l'intérêt de la fonctionnalité.

Est-ce que vous voyez ce qu'il y a à faire ?

**Comment by Toine-prog** [comment]
Bonjour, j'ai fait les scénarios avec @Fulin-ZHANG

**Comment by benel** [comment]
@Fulin-ZHANG Ce ticket, qui est en cours de conception/développement, ne sera fermé que quand son implémentation sera intégrée à la branche principale. Donc il va falloir attendre un peu ;)

**Comment by Fulin-ZHANG** [comment]
> @Fulin-ZHANG Ce ticket, qui est en cours de conception/développement, ne sera fermé que quand son implémentation sera intégrée à la branche principale. Donc il va falloir attendre un peu ;)

Désolé pour

**Comment by Toine-prog** [comment]
@benel Voici la deuxième version du scénario en essayant d'appliquer vos remarques avec @Fulin-ZHANG .

```cucumber
#language: fr

Fonctionnalité: Partager un item sur Facebook

Cas où il n'est pas possible de partager un item sur Facebook directement à partir de Porphyry

Scénario: Partager un item sur Facebook

  Soit "AXN 009" un item ouvert
  Quand l'utilisateur partage un item sur Facebook
  Alors l'item "AXN 009" est téléchargé
  Et l'application Facebook s'est ouvert
  Et l'utilisateur publie l'item sur Facebook
```

----------------------------------------------------------------------
Cas où il est possible de partager un item sur Facebook directement à partir de Porphyry

```cucumber
Scénario: L'utilisateur se connecte sur Facebook

  Soit "AXN 009" un item ouvert
  Quand l'utilisateur se connecte sur "Facebook"
  Alors l'utilisateur est connecté 

Scénario: partager item sur Facebook

  Soit "AXN 009" un item ouvert 
  Et l'utilisateur est connecté avec Facebook
  Quand l'utilisateur partage un item sur Facebook
  Alors l'application Facebook s'ouvre
  Et l'utilisateur publie l'item sur Facebook
```

**Comment by benel** [comment]
@Toine-prog @Fulin-ZHANG 

J'ai édité moi-même votre message pour activer la fonctionnalité de coloration syntaxique de GitHub. N'oubliez pas de le faire la prochaine fois, le code est alors beaucoup plus facile à relire (si vous ne savez comment faire, visualisez le message en mode édition).

> Cas où il n'est pas possible de partager un item sur Facebook directement à partir de Porphyry
> Cas où il est possible de partager un item sur Facebook directement à partir de Porphyry

C'est exactement ce genre de choses qu'il faudrait mettre comme titre des scénarios.
Par contre, pour l'instant on ne comprend pas très bien pourquoi c'est possible parfois et parfois pas... Il faudrait être plus explicite... Si c'est juste à cause de la connexion à Facebook, inutile de tester le cas 

> `Scénario: L'utilisateur se connecte sur Facebook`

Ça c'est typiquement un prérequis du partage.

>  `Quand l'utilisateur partage un item sur Facebook`

"Un item" ? Lequel ? `AXN 009` ?

Cette étape est l'étape centrale. Gardez uniquement celle-ci puis demandez-vous comment vous pourriez tester le fait que l'item a été partagé. Qu'est-ce qui a changé et sur quelle plateforme ? Quelle est la différence entre avant et après ?

**Comment by Toine-prog** [comment]
Voici une 3ème version des scénarios avec @benel 

```cucumber
#language: fr

Fonctionnalité: Partager un item sur Facebook

Scénario: Il n'est pas possible de partager un item sur Facebook directement à partir de Porphyry

  Soit "AXN 009" un item ouvert
  Quand l'utilisateur partage "AXN 009" sur Facebook
  Alors l'item "AXN 009" est téléchargé
  Et l'application Facebook s'est ouvert
```
```cucumber
Scénario: il est possible de partager un item sur Facebook directement à partir de Porphyry

  Soit "AXN 009" un item ouvert 
  Et l'utilisateur est connecté avec Facebook
  Quand l'utilisateur partage "AXN 009"sur Facebook
  Alors l'onglet de partage de Facebook s'ouvre
```

**Comment by benel** [comment]
@Toine-prog @Fulin-ZHANG 

> Scénario: Il n'est pas possible de partager un item sur Facebook directement à partir de Porphyry

Comme je l'indiquais précédemment : "Si c'est juste à cause de la connexion à Facebook, inutile de tester le cas".
En effet, est-ce que ce cas correspond réellement à une amélioration du comportement de Porphyry que vous allez apporter en développant cette fonctionnalité ? Je ne pense pas...
À la limite si dans ce cas, le partage fonctionnait quand même (par magie ?), ça arrangerait plutôt les utilisateurs...

> Scénario: il est possible de partager un item sur Facebook directement à partir de Porphyry

Maintenant que vous avez votre "Quand". Il faut répondre à la question que je vous posais :  

"Demandez-vous comment vous pourriez tester le fait que l'item a été partagé. 
 Qu'est-ce qui a changé et **sur quelle plateforme** ? 
Quelle est la différence entre avant et après ?"

En effet, sur quelle plateforme peut-on voir que quelque chose a changé entre _avant_ et _après_ avoir partagé un item de Porphyry sur Facebook ?

**Comment by Toine-prog** [comment]
@benel 
Avec @Fulin-ZHANG, nous avons du mal à comprendre l’intérêt des scénarios dans notre cas. Parce que du coup on a l'impression d'avoir qu'un seul scénario à écrire. On a essayé de reprendre une nouvelle fois en compte vos remarques et avons réalisé ceci.


```cucumber
#language: fr

Fonctionnalité: Partager un item sur Facebook

```
```cucumber
Scénario: il est possible de partager un item sur Facebook directement à partir de Porphyry

  Soit "AXN 009" un item ouvert 
  Et l'utilisateur est connecté avec Facebook
  Quand l'utilisateur partage "AXN 009"sur Facebook
  Alors "AXN 009" est publié sur Facebook
```

**Comment by benel** [comment]
@Toine-prog 

> Avec @Fulin-ZHANG, nous avons du mal à comprendre l’intérêt des scénarios dans notre cas. Parce que du coup on a l'impression d'avoir qu'un seul scénario à écrire. 

C'est tout à fait possible. Ça veut seulement dire qu'il n'y a qu'un seul cas (tout rentre dans le cas général : il n'y a pas de cas particulier).

>  Soit "AXN 009" un item ouvert 
  Et l'utilisateur est connecté avec Facebook
  Quand l'utilisateur partage "AXN 009"sur Facebook
  Alors "AXN 009" est publié sur Facebook

C'est mieux...
Mais peut-être qu'il était déjà publié sur Facebook avant que vous le partagiez.
Oui, je sais, il faut tout dire... mais c'est le principe des tests...

**Comment by Toine-prog** [comment]
@benel  5ème version avec @Fulin-ZHANG 


```cucumber
#language: fr

Fonctionnalité: Partager un item sur Facebook

```
```cucumber
Scénario: il est possible de partager un item sur Facebook directement à partir de Porphyry

  Soit "AXN 009" un item ouvert 
  Et l'utilisateur est connecté avec Facebook
  Quand l'utilisateur partage "AXN 009"sur Facebook
  Alors "AXN 009" est la publication la plus récente sur la page Facebook du publicateur
```

**Comment by Toine-prog** [comment]
@benel Version finale Scénarios @Fulin-ZHANG 


```cucumber
#language: fr

Fonctionnalité: Partager un item sur Facebook

```
```cucumber
Scénario: il est possible de partager un item sur Facebook directement à partir de Porphyry

  Soit "AXN 009" un item ouvert 
  Et l'utilisateur est connecté avec Facebook
  Quand l'utilisateur partage "AXN 009" sur Facebook
  Alors "AXN 009" est la publication la plus récente sur la page Facebook de l'utilisateur
```

**Comment by LSauter68140** [comment]
Pour la phase de stratégie d'implémentation
On va essayer de garder le composant de partage actuel, ce qui nous parait le plus simple et ce qui aura le plus de chance d'aboutir à un résultat.
Au lieu de partager la page (ce qui est en place actuellement et qui ne fonctionne pas), on partagerait directement l'url de l'image ce qui a plus de chance de fonctionner.

Pour cela on a d'abord regarder ou se trouve le composant disqus et comment l'utiliser.
https://github.com/Hypertopic/Porphyry/blob/d1438c5e1a3198f5d8aec8218bc38c4d6da241d9/src/components/itemPage/Item.jsx#L341-L349
Voici ce que prend en paramètre le composant disqus 
```javascript
 import { DiscussionEmbed } from 'disqus-react';

<DiscussionEmbed
    shortname='example'
    config={
        {
            url: this.props.article.url,
            identifier: this.props.article.id,
            title: this.props.article.title,
            language: 'zh_TW' //e.g. for Traditional Chinese (Taiwan)	
        }
    }
/> 
```
il suffit donc de rajouter un ligne url dans l'objet config actuel 
https://github.com/Hypertopic/Porphyry/blob/d1438c5e1a3198f5d8aec8218bc38c4d6da241d9/src/components/itemPage/Item.jsx#L342-L345

dans cette url on mettra donc le lien du vitrail à partager.
Ce lien vers la photo du vitrail ce trouve dans l'objet props  mis en entrée dans la fonction Comment

![image](https://user-images.githubusercontent.com/48133985/120067758-b1b7f480-c07d-11eb-93d7-da66ab72d284.png)

l'objet config pourrait donc ressembler à ça ;

```javascript


let config = {
    identifier: props.item.id,
    title: props.item.name,
    url: props.item.resource ? props.item.resource[0] : null,
}


```
@YaellePihan @Toine-prog @benel

**Comment by benel** [comment]
@LSauter68140 Merci pour cette stratégie d'implémentation !

Donc, on est d'accord que pour l'instant `DiscussionEmbed` prend par défaut comme URI à partager celle de la page contenant le composant, et qu'en renseignant cette propriété supplémentaire, vous allez pouvoir donner à la place celle de l'image. Oui, ça devrait fonctionner ! 🤞🏼

**Comment by benel** [comment]
@LSauter68140 @YaellePihan Merci pour cette stratégie d'implémentation !

Donc, on est d'accord que pour l'instant `DiscussionEmbed` prend par défaut comme URI à partager celle de la page contenant le composant, et qu'en renseignant cette propriété supplémentaire, vous allez pouvoir donner à la place celle de l'image. Oui, ça devrait fonctionner ! 🤞🏼

**Comment by LSauter68140** [comment]
Oui c'est ça !, Par contre en local on arrive pas à utiliser le composant disqus, par défaut props.appId est null (ce qui est cohérent vu qu'on n'a pas la même base de données que la version en ligne).
https://github.com/Hypertopic/Porphyry/blob/d1438c5e1a3198f5d8aec8218bc38c4d6da241d9/src/components/itemPage/Item.jsx#L346-L349
Il suffit donc d'enlever la ligne. Or en local il y a un temps d’accès de donnée le "fetch" de la query, donc en premier temps on a un props qui est nul et ensuite une fois la réponse de la base de données obtenue (l’objet props a reçu les bonnes valeurs), le composant https://github.com/Hypertopic/Porphyry/blob/d1438c5e1a3198f5d8aec8218bc38c4d6da241d9/src/components/itemPage/Item.jsx#L341 ne se met pas à jour (pas de rerender). Est donc possible d'afficher correctement le composant `DiscussionEmbed`  en local ? Ou vu la configuration actuel il ne fonctionne qu'avec la version en ligne ?
Merci pour votre réponse

**Comment by benel** [comment]
@LSauter68140 @YaellePihan 

> Par contre en local on arrive pas à utiliser le composant disqus, par défaut props.appId est null 

Vous ne l'avez pas mis dans votre configuration ?

Pour un premier test d'affichage, vous pouvez réutililiser celui de la production (à l'adresse `/config.yml` d'un des sites en production). Mais le mieux ensuite pour faire des tests est de vous créer un compte (la procédure à suivre est donnée à la fin du [README](https://github.com/Hypertopic/Porphyry/blob/v7/README.md) de Porphyry, "enable comments").

Tenez moi au courant si vous rencontrez des difficultés.

**Comment by LSauter68140** [comment]
> Vous ne l'avez pas mis dans votre configuration ?
> 
> Pour un premier test d'affichage, vous pouvez réutililiser celui de la production (à l'adresse `/config.yml` d'un des sites en production). Mais le mieux ensuite pour faire des tests est de vous créer un compte (la procédure à suivre est donnée à la fin du [README](https://github.com/Hypertopic/Porphyry/blob/v7/README.md) de Porphyry, "enable comments").

Bon finalement j'ai pu créer un compte disqus et j'ai fait 2 3 changements sur le code
et ça a l"air de bien fonctionner.
![image](https://user-images.githubusercontent.com/48133985/120331650-4b85d880-c2ee-11eb-940e-d4177e9f207d.png)

**Comment by benel** [comment]
Super @LSauter68140 @YaellePihan !
Du coup, votre stratégie d'implémentation fournit déjà l'implémentation elle-même ?
Si c'est bien le cas, j'attends avec impatience votre demande d'intégration !

**Comment by Toine-prog** [comment]
@benel 
Bonjour monsieur, j'ai une question concernant le scénario facebook réalisé avec @Fulin-ZHANG .

Doit-on faire un pull request de notre scénario même si celui-ci n'est pas automatisable ? Cela permettrait de valider la compétence de contribution.

**Comment by benel** [comment]
@YaellePihan 

Suite à notre réunion à propos des tests à propos du téléchargement de fichiers, voici : 

- [la spécification de l'entête HTTP](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Content-Disposition#en_tant_quentête_de_réponse_pour_le_corps_principal),
- un essai un peu ancien (dans un environnement de test un peu différent) pour [récupérer le nom du fichier téléchargé](https://github.com/Hypertopic/Tire-a-part/blob/master/spec/spec_helper.rb#L51).

**Comment by Quentin-UTT** [comment]
@benel 
Voici la première version des tests "humain" réalisés avec @Lan-MU623 

```
Soit("AXN 009 un item ouvert") faire
    Sur Porphyry, l'utilisateur clique sur l'item AXN 009 pour l'ouvrir
end

Quand ("l'utilisateur partage "AXN 009" sur Facebook") faire
	Cliquer sur le bouton partager de Facebook puis sur Publier l'item
end

Alors ("AXN 009 est la publication la plus récente sur la page Facebook de l'utilisateur" faire
	Se rendre sur Facebook.
	Aller sur son profil.
	Vérifier que l'item AXN 009 correspond à la dernière publication.
end

```

**Comment by benel** [comment]
@Toine-prog @Fulin-ZHANG 

> Doit-on faire un pull request de notre scénario même si celui-ci n'est pas automatisable ? 

Pourquoi pas ? Après tout c'est quand même une forme de documentation.

> Cela permettrait de valider la compétence de contribution.

C'est effectivement une bonne idée.

**Comment by benel** [comment]
Implemented by ad13af6544b5f5367bc19796f8e2d9004e313ba7.
