### ISSUE TITLE
Get similar items according to an item's attribute value

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#39]
Similarly to what is done on topics, you could **click on an attribute value** and open the portfolio page in which every item with this value would be selected (#158) or sorted (#38) (the designers should choose either of the prerequisites).

### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

**Comment by Kodlah** [comment]
Projet Graines d'artistes : 
Cette fonctionnalité pourrait permettre de regrouper les dessins selon la valeur d'un attribut commun. On pourrait, par exemple, afficher tous les dessins provenant du même auteur.

**Comment by sbramstein** [comment]
Greek vases : This issue joins the #38 one and has a real meaning for greek vases. To filter on a precise value. Like having the vases made of the same material. So as well this issue should be placed at the high part of our ranking.

**Comment by lerideew** [comment]
For the "study abroad" projet.
The user should be able to consult multiples UEs having the same attribute values (e.g.: UEs with the same University, in the same country or having the same subject).

**Comment by FirielEinor** [comment]
For the "Stained Glass on site" project, this feature would be useful for the user who could look for other stained glass from the same time period or with the same character on it, or from the same author

**Comment by Starangon** [comment]
> For the "Stained Glass on site" project, this feature would be useful for the user who could look for other stained glass from the same time period or with the same character on it, or from the same author

Projet Visite sur site de vitraux :
Cela pourrait aussi servir pour découvrir de nouveaux vitraux, trouver de futurs endroits a visiter, où simplement en trouver d'autres au même endroit.

**Comment by yvan-noume** [comment]
projet visite sur site de vitraux:
Cette fonctionnalité permettrait à l'utilisateur d'avoir des suggestions d'items correspondant à la valeur de l'attribut d'une autre item.

**Comment by benel** [comment]
> For the "Stained Glass on site" project, this feature would be useful for the user who could look for other stained glass from the same time period or with the same character on it, or from the same author

@FirielEinor Pour l'auteur de la photographie OK, c'est bien un attribut. Par contre, si vous parlez de la datation du vitrail ou des personnages représentés ce ne sont pas des attributs mais des catégories.

**Comment by ghost** [comment]
Pour le projet Collectives' stories, cette fonctionnalité nous permettra de faire des suggestions d'autres récits expériences, et de regrouper les récits d'un même auteur, ou d'une même organisation.

**Comment by melaniehoneychurch** [comment]
Cette fonctionnalité est très intéressante pour le projet sur les vitraux car elle permettrait de faire une recherche sur les vitraux en fonction de l'église dans laquelle ils se trouvent.

**Comment by ChloeChamaillard** [comment]
Projet Approche par compétences de la formation :
Cette fonctionnalité pourrait permettre d'obtenir les UE selon différents attributs (le nombre d'heures ...)

**Comment by benel** [comment]
> Cette fonctionnalité pourrait permettre d'obtenir les UE selon différents attributs (le nombre d'heures ...)

@ChloeChamaillard OK... Ceci dit, l'exemple n'est pas forcément le plus pertinent... Beaucoup d'UE ont le même nombre d'heures...

**Comment by yvan-noume** [comment]
**Équipe visite sur site de vitraux**
le problème rencontré est au niveau de la maquette. nous avons juste fais la version mobile de la maquette donc il y a la version pc à faire. De plus nous avons constaté que la maquette sur mobile que nous avions déjà faite était trop déconnecté du site. Donc nous allons refaire les maquettes(version mobile et pc) en se basant sur l'interface de phorphyry. 
@TheStarTom et @yvan-noume  travaillent sur ce livrable cette semaine.

**Comment by jejroux** [comment]
> 
> 
> **Équipe visite sur site de vitraux**
> le problème rencontré est au niveau de la maquette. nous avons juste fais la version mobile de la maquette donc il y a la version pc à faire. De plus nous avons constaté que la maquette sur mobile que nous avions déjà faite était trop déconnecté du site. Donc nous allons refaire les maquettes(version mobile et pc) en se basant sur l'interface de phorphyry.
> @TheStarTom et @yvan-noume travaillent sur ce livrable cette semaine.

@melaniehoneychurch et @jejroux travaillent sur l'écriture du/des scénarios de la fonctionnalité.

**Comment by Starangon** [comment]
voici la maquette version PC que l'on a réalisé (en prenant en compte les résultats et attentes du #158) :
![image](https://user-images.githubusercontent.com/57453148/81306702-0f972a00-9080-11ea-8dc0-0e10ce83b9f5.png)

**Comment by yvan-noume** [comment]
voici la maquette version mobile que l'on a réalisé tout en sachant qu'un ticket destiné à l'amélioration de la consultation sera créé.
![81301584-867cf480-9079-11ea-9c1a-bec4baa958df](https://user-images.githubusercontent.com/61839194/81928948-63f15b00-95e6-11ea-896b-71f385ca17fa.png)
![81302167-49653200-907a-11ea-8a70-b3df78c4f18a](https://user-images.githubusercontent.com/61839194/81928953-6653b500-95e6-11ea-9da7-4e4ce098d8e4.png)

**Comment by benel** [comment]
> voici la maquette version mobile que l'on a réalisé tout en sachant qu'un ticket destiné à l'amélioration de la consultation sera créé.

@yvan-noume Si je me souviens bien des discussions dans votre espace de groupe, les widgets liés à l'édition seront cachés dans la version mobile.

Je le précise parce qu'en théorie ça pourrait faire échouer les tests des autres équipes. Pour ce cas précis, j'en doute mais c'est au cas où (pour prendre l'habitude d'anticiper ce genre de problèmes).

**Comment by jejroux** [comment]
Voici le scénario correspondant pour le projet des vitraux:

Fonctionnalité : À partir d'un item, obtenir ceux qui ont une même valeur d'attribut

Scénario :

Soit "SNZ 005" l'item affiché
Quand on choisit l'attribut "spatial : Église Saint-Nizier, Troyes"
Alors l'attribut "spatial : Église Saint-Nizier, Troyes" est sélectionné
Et l'item "SNZ 005" est affiché
Et l'item "SNZ 006" est affiché

**Comment by benel** [comment]
@jejroux 

OK, il y a une bonne base, mais maintenant, il faudrait mieux voir l'effet de la sélection. A priori, après une sélection, on devrait voir **moins** d'items qu'avant : autrement dit, certains items qui étaient visibles avant, ne doivent **plus** être visibles après.

**Comment by jejroux** [comment]
@benel Ajouter à la fin la ligne :

_Et l'item "PSM 002" n'est pas affiché_

Est-ce que ça suffirait ?

**Comment by yvan-noume** [comment]
> 
> 
> > voici la maquette version mobile que l'on a réalisé tout en sachant qu'un ticket destiné à l'amélioration de la consultation sera créé.
> 
> @yvan-noume Si je me souviens bien des discussions dans votre espace de groupe, les widgets liés à l'édition seront cachés dans la version mobile.
> 
> Je le précise parce qu'en théorie ça pourrait faire échouer les tests des autres équipes. Pour ce cas précis, j'en doute mais c'est au cas où (pour prendre l'habitude d'anticiper ce genre de problèmes).

oui effectivement ces widgets seront cachés.

**Comment by Kodlah** [comment]
En se basant sur les travaux effectués par les autres groupes, l'avancement du ticket est actuellement le suivant : 
 ### Phase 1

   * [X]  Scenarios (Gherkin)

   * [X]  Mockups

   * [ ]  Implementation strategy

 
 ### Phase 2
   * [ ]  Acceptance tests (Capybara)
 
   * [ ]  Implementation

Le binôme @JoJOes et @moonkeys du projet @Hypertopic/graines-d-artistes s'occuperont pour la semaine prochaine (04/06) de la stratégie d'implémentation et des tests d'acceptations.

**Comment by moonkeys** [comment]
**Stratégie d'implémentation**

La fonctionnalité #39 sera implémentée dans le fichier `Attribute.jsx`  dans la fonction `AttributeValue`. Les fonctionnalités de `react-router-dom` seront sollicités pour rediriger l'utilisateur. Il arrivera sur la page des portfolios du site avec la recherche correspondant à l'attribut cliqué.

**Comment by benel** [comment]
> Il arrivera sur la page des portfolios du site avec la recherche correspondant à l'attribut cliqué.

Du coup, quelle pourrait être la forme de l'URI ?

L'intérêt de la conception détaillée, c'est de limiter la quantité de travail et de décisions à prendre lors du développement.

**Comment by neumeiej** [comment]
**Stratégie d’implémentation** :

**Préambule** :
Nous nous sommes basés sur les travaux effectués par les autres groupes pour effectuer notre stratégie d’implémentation, notamment les mockups publiés par @yvan-noume et @TheStarTom ainsi que la stratégie d’implémentation rédigée par @moonkeys.
Ce ticket poursuit la feature #158, un clic sur un attribut ouvre une page du portfolio regroupant les items possédant les mêmes attributs.

**Quelles sont les parties du code impactées (classes, méthodes)** ?
La classe Attribute.jsx sera impactée, puisque c’est elle qui gère le rendu des attributs. La méthode AttributeValue devra notamment être modifiée de manière à générer un lien cliquable pour accéder au contenu recherché.
 
<img width="454" alt="image" src="https://user-images.githubusercontent.com/33666392/83681338-8f160b80-a5e2-11ea-9bd3-bbe2f7996d64.png">

**Par où commencer** ?
Il s’agit de générer un URI comprenant une requête GET pour accéder au portfolio avec comme critère de recherche l’attribut cliqué. Cela est permis par la feature #158 qui consiste à sélectionner des items selon un attribut. Cet URI renseignera une propriété href qui rendra la valeur de l’attribut cliquable et qui ouvrira la ressource lorsqu'elle est cliquée.

**Comment transmettre un attribut dans la requête GET** ?
Voilà ci-dessus un exemple d’URI généré à partir d’un attribut « _created_ » ayant pour valeur une date « _2014-04-05_ ».
 
<img width="453" alt="Unbenannt" src="https://user-images.githubusercontent.com/33666392/83681490-c684b800-a5e2-11ea-8bb5-cc4f6023bba7.png">

On observe donc que l’attribut est transmis dans la requête GET sous forme d’un **objet** dénommé selection et ayant deux champs : 
-	_attribute_ qui renseigne donc le **type d’attribut**
-	_value_ qui renseigne la **valeur de l’attribut**

**Comment by benel** [comment]
@neumeiej OK. Ça m'a l'air bien. Pour que ce soit complet, ajoutez l'URI en mode texte (au-dessous de l'image). Ça facilitera la lecture ainsi que le travail des binômes qui travailleront sur les tests et l'implémentation.

**Comment by benel** [comment]
J'ai vu passer le scénario (`.feature` dans https://github.com/Hypertopic/Porphyry/commit/2c264259e46dceed7bddada7f04093d1d37fa482 par @melaniehoneychurch). Par contre, je n'ai pas vu le test...

Il n'y a qu'une seule étape à implémenter (et elle est très simple) mais il la faut quand même.

**Comment by jejroux** [comment]
@benel Je m'en charge !

**Comment by benel** [comment]
Deployed.
