### ISSUE TITLE
Create a child to a topic

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#43]
as

 easily as in an outliner.

Prerequisite: #42.
- [x] Scénarios (Fangxu)
- [x] Maquettes
- [x] Tests automatisés
- [x] Implémentation

**Comment by davp01x** [comment]
Fonctionnalité pour l'annuaire participatif :
Créer un sous-thème [Charc'UTT, Club bières] (child) sur un thème [Degustation] (topic)

**Comment by gumn** [comment]
Les maquettes ont été montrées aux parties prenantes en créant une vidéo à partir du site : https://checkvist.com/auth/index
