### ISSUE TITLE
Rename a topic

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#44]
as easily as in an outliner
- [x] Scénarios (Jie JI)
- [x] Maquettes (Ruolin ZHENG)
- [x] Tests automatisés 
- [x] Implémentation

**Comment by davp01x** [comment]
Fonctionnalité pour l'annuaire participatif :
Renommer un thème [CS, ME, Informatique, Étudiant, Enseignant, Robotique] (topic)

**Comment by gumn** [comment]
Les maquettes ont été montrées aux parties prenantes en créant une vidéo à partir du site : https://checkvist.com/auth/index
