### ISSUE TITLE
Move as an upper topic

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#45]
- [x] Scénarios (Fangxu)
- [x] Maquettes (Yuanjia)
- [ ] Tests automatisés
- [x] Implémentation

**Comment by gumn** [comment]
Les maquettes ont été montrées aux parties prenantes en créant une vidéo à partir du site : https://checkvist.com/auth/index

**Comment by gumn** [comment]
Implémenté par notre équipe, nécessité de presser Ctrl pendant l'opération. A valider à l'usage.

**Comment by gumn** [comment]
Les utilisateurs ne sont pas favorables a priori à la nécessité de presser Ctrl pour activer la fonction, mais cela sécurise les écran tactiles et/ou de petite taille.

**Comment by benel** [comment]
Implemented but not very usable.

**Comment by benel** [comment]
Refactored by #139.
