### ISSUE TITLE
Comment (or share with friends) an item

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#47]
- [x] Scénarios
- [x] Maquettes 
- [x] Tests automatisés 
- [x] Implémentation 

with discussion threads, links to sources, and maybe uploaded documents.

While a bit too much "post-modern" for science, comments could be "liked" by peers. 

Comments could also be shared optionally on social networks to get visibility on one's work. This would also benefit the platform by dragging in additional contributors.

As an example of APIs that could be developed or integrated, here are:

- [Facebook's social plugin](https://developers.facebook.com/products/social-plugins/comments/),
- [Disqus comment plugin](https://disqus.com).

**Comment by gumn** [comment]
Bonjour aux membres des team archéologie et open acess :
Nous sommes trois team à avoir mis la feature #47 Comment (or share with friends) an item
La question est donc la suivante :
Est-ce qu'une team en particulier s'attaque au sujet ? Sinon, comment se répartit-on la tâche ? On doit au moins se mettre d'accord sur l'aspect global (maquette) et la répartition dans ce cas. Les maquettes faites par notre team sont sur https://drive.google.com/drive/folders/1tTAaW3AySE3GClESuND_dsTdTT_AgI9F
(dossier commentaire pour la maquette papier et com_mockup pour la maquette balsamiq)
En même temps apparemment les modules facebook sont pas mal donc on risque de s'aligner.

**Comment by gumn** [comment]
subfeatures:
- create a comment
- suppress a comment (possible even if answered)
- like a comment or an answer
- answer a comment

**Comment by davp01x** [comment]
Fonctionnalité pour l'annuaire participatif :
Commenter le profil d'une personne (item)

Priorité : très basse pour notre projet

**Comment by Sallaa** [comment]
@gumn Bonjour, cette fonctionnalité ne sera pas implémentée par notre équipe **Archéologie Grecque** car elle n'est pas prioritaire aujourd'hui

**Comment by gumn** [comment]
Sur cette fonctionnalité, il est prévu de dépendre du ficher de configuration, en fonction du portfolio
-> attribut "enabled : true" pour l'activation globale
-> attribut "public : true" si tout le monde peut commenter, avec false ce ne sera que le user de l'item cf annuaire participatif

**Comment by Brochette1012R** [comment]
# Maquettes :
![page item](https://user-images.githubusercontent.com/37656648/41152192-38e82e34-6b13-11e8-90f1-15f5a822b841.png)
![page onclick report](https://user-images.githubusercontent.com/37656648/41152193-390823e2-6b13-11e8-85a5-98e865e33eb1.png)
![page onclick respond](https://user-images.githubusercontent.com/37656648/41152194-3923eca8-6b13-11e8-8f67-58e903f6d531.png)
![page report comment](https://user-images.githubusercontent.com/37656648/41152196-393f34f4-6b13-11e8-880c-ef057fbde4f3.png)
![page respond](https://user-images.githubusercontent.com/37656648/41152197-39577cee-6b13-11e8-85a1-e2b4a2e19c47.png)

**Comment by benel** [comment]
Dès que vous aurez trouvé la bonne manière de configurer le plugin, pensez à faire une pull request...

**Comment by benel** [comment]
L'intégration de *Disqus* a permis l'ajouter des fonctionnalités suivantes :
 
- Partager un item au sein de son réseau social,
- Commenter un item ou répondre à un commentaire (en texte libre avec des images et des liens vers des ressources externes),
- Recommander ou partager un commentaire ou une discussion,
