### ISSUE TITLE
Add an emoticon option to write a comment

### ISSUE THREAD

**Issue by Fulin-ZHANG** [Hypertopic/Porphyry#511]
Allow users to conveniently share moods and preferences on pictures.

**Comment by benel** [comment]
Before this feature is implemented, please note that Disqus plugin makes it possible to: 

1. use emojis in a comment: 
<img width="367" alt="Capture d’écran 2021-06-02 à 17 21 38" src="https://user-images.githubusercontent.com/597307/120507704-56f90280-c3c7-11eb-8c06-f994474e3623.png">
2. recommend a picture:
<img width="677" alt="Capture d’écran 2021-06-02 à 17 25 24" src="https://user-images.githubusercontent.com/597307/120508023-a3444280-c3c7-11eb-954b-add7bb8743a9.png">

**Comment by Fulin-ZHANG** [comment]
What you said makes sense, but if we want to share emoticons after we connect to disqus, we have to use emoji in the mobile phone input method. There are no very eye-catching buttons or options to enter emoticons in this area. I don't know if this idea is stupid, but it may provide a little convenience. Especially computer users.
