### ISSUE TITLE
Allow the user to choose the hashtags they want to share

### ISSUE THREAD

**Issue by Lan-MU623** [Hypertopic/Porphyry#512]
When users share our pictures on Instagram, they can choose the tags we provide. Not only that, we can design a function that allows him to create a new hashtag when he chooses a hashtag. We can save the hashtags he created, so that people in the future can use the hashtags created by the previous people when sharing pictures.

**Comment by benel** [comment]
For Instagram, could you explain how is this different from @373?

For Facebook, this doesn't seem compatible with #380... Is it?

**Comment by Lan-MU623** [comment]
@benel 
For Instagram, it just like #vitrail or  #32783794, it's a label/tag for a class of things. @373 is remind a user who's name is 373.

For Facebook, I forgot there is no tag in Facebook. I will delete Facebook in my ticket.

**Comment by benel** [comment]
Sorry for the typo: I meant "Porphyry issue #373".

**Comment by Lan-MU623** [comment]
oui c'est just comme #373 que vous avez dit 3 jours avant, c'est un function de #373

**Comment by benel** [comment]
> oui c'est just comme #373 que vous avez dit 3 jours avant, c'est un function de #373

Dans ce cas, @Hypertopic/cite-du-vitrail , vous pouvez fermer le ticket.

**Comment by Lan-MU623** [comment]
But the difference is that users can create tags and let other users use the tags he created

**Comment by benel** [comment]
> But the difference is that users can create tags and let other users use the tags he created

Isn't that exactly what topics are for?

**Comment by Lan-MU623** [comment]
@benel 
I don't know why you close my ticket. It just a normal ticket and different from other's. Could you give me a reason of close it or how can I improve it? Thank you.

**Comment by benel** [comment]
For IF05, I already validated your skill, don't worry.

> Could you give me a reason of close it or how can I improve it? 

After four attempts to get the ticket reformulated, I still don't understand what is exactly the ticket about and how it is different from what already exists. 
As the maintainer of the repository, I am in charge with managing the ticket list so that it does not extend endlessly, and I cannot keep a ticket I don't understand.
If you or another user really need this feature, you/he/she will open a new ticket.

Regards.

**Comment by Lan-MU623** [comment]
OK, I am sorry that my lack of expressive skills prevents you from understanding my ticket.
