### ISSUE TITLE
Add the possibility to create groups

### ISSUE THREAD

**Issue by majestyck** [Hypertopic/Porphyry#529]
### Description

Add the possibility to create group. 

This will help to create groups by topic like data science, mechanical and centralize items by thematics

**Comment by benel** [comment]
Groups of what? Of people? Of topics?

**Comment by majestyck** [comment]
Yeah, it will be a group of topics on the same thematics. Groups will have name. For example we will be able to create a groupe named c++ programming that will regroup all c++ courses (for overseas studies)

**Comment by benel** [comment]
I'm afraid you didn't get what is the Hypertopic model (the model used in Porphyry)...

You can already regroup topics into a topic (recursively)

```
- Programming (Topic)
  - Object-oriented programming (Topic)
    - C++ (Topic)
    - Java (Topic)
    - Objective C (Topic)
  - Functionnal programming (Topic)
  - Procedural programming (Topic)
- Data modelling (Topic)
  - Designing a database schema (Topic)
 ```

And you can also link a topic to several items : 

```
- Java (Topic)
  - LO02 (Item)
  - CS106A (Item)
```

**Comment by majestyck** [comment]
Oh I didn't know that could be used in that way, I'm gonna close the ticket
