### ISSUE TITLE
Search should not reset the current query

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#553]
#### What is the valuable outcome that cannot be achieved because of this bug?

Combining browsing and search corresponds to the way users are looking for items.

#### For which stakeholder (people, role, project, domain) is it important?

To be determined.

#### Reproduction scenario
1. Go to vitraux.porphyry.org
2. Browse `Histoire de l'art : Datation > XIXe s.`
3. Search `created:1907/1914`
4. The current query is `(created:1907/1914)`

#### Expected behavior

The current query should be `(XIXe s.) and (created : 1907/1914)`.

#### Workaround

Switch steps 2 and 3.

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Implementation strategy

#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

**Comment by maxime-huyghe** [comment]
![image](https://media.discordapp.net/attachments/949261456661159991/954344035634528256/20220318_115718.jpg?width=507&height=676)

**Comment by Couapy** [comment]
On devra probablement modifier les components Selection, et / ou [SearchBar](https://github.com/Hypertopic/Porphyry/blob/v7/src/components/portfolioPage/SearchBar.jsx#L42) avec un potentiel [Selection.toggleTopic](https://github.com/Hypertopic/Porphyry/blob/v7/src/Selection.js#L65).
Je ne pense pas qu'il y aura des difficultés particulières.

Les données sont déjà chargées dans la page (recherche déjà existante, et système de recherche déjà existant).
Nous n'avons besoin de rien autre.

**Comment by benel** [comment]
### Point d'avancement du 28/04

- Scénarios : fait (avec l'aide d'une personne de l'autre demi-groupe),
- Stratégie d'implémentation : à finaliser,
- Tests : à finaliser.


Autre : nettoyer l'historique de la PR.

**Comment by MaximeMZ** [comment]
### Stratégie d'implémentation :

**Quelle partie du code sera impactée (classes, méthodes) ? Utilisez les React DevTools (extensions de Chrome ou Firefox) pour faire le lien entre la structure de la page et celle du code.** 

La recherche sera impactée soit le composant "searchBar.jsx"  (Porphyry/src/components/portfolioPage/SearchBar.jsx)
et l’objet “Selection” (Porphyry/src/Selection.js)



**Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?**

La modification de l’objet  selection et de ses fonctions de modification peut poser problème puisque qu’il faut entièrement revoir le comportements de ces fonctions tout en conservant les fonctionnalitées déjà présentes (ajout d’items à la recherche par un clic sur les catégories d’un point de vue)


**Les données dont vous avez besoin sont-elles déjà chargées par la page ?** 

OUI -> il s’agit d’une correction de bug seulement sur le comportement de la recherche.


**Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ?**

Format des données : 


>items: [{ 
>    année : “ “ ,
>    corpus : “ “ ,
>    expo : “ “ ,
>    id : “ “ , 
>    item : “ “ , 
>    name : “ “ , 
>    record : “ “ , 
>    ressource : “ “ , 
>    spatial : ” “ , 
>    thumbnail : “ “ , 
>    topic : { id :” “ , viewpoint : “ “ } 
> } ]

On peut s’inspirer de l’ajout d’une catégorie dans la recherche pour corriger le bug -> portfolioPage> topic.jsx dans la méthode handleClick (ligne55)


**Si non, quelle sera la requête la plus efficace  et comment allez-vous récupérer dans la structure de données précisément celles qui vous intéressent ?**

Ø

**Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ? Quelles sont celles que vous choisirez et pourquoi ?**

Ø


**Doit-on intégrer des services extérieurs (ex : cartographie) ?** 

Ø


**De quelles fonctionnalités en particulier aura-t-on besoin ?** 

Ø


**Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ?** 

Ø


**Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?** 

Ø


**Type URI :** 
http://localhost:3000/?t={%22type%22:%22intersection%22,%22data%22:[{%22type%22:%22intersection%22,%22selection%22:[%22name%20:%20AXN%20009%22,%224dbf2acc119ff3458a53ae9de59a44a7%22],%22exclusion%22:[]}]}

**Comment by benel** [comment]
### Point d'avancement du 29/04

- Scénarios : intégrer le cas des topics (peut-être dans celui des concurrents)
- Stratégie d'implémentation : Pour une prochaine fois penser à mentionner le refactoring préalable
- Implémentation : à finir, en cours de dépôt.

**Comment by Couapy** [comment]
A l'heure actuelle il manque le comportement liant des sélection dans des parenthèses (topics frères et soeurs).

**Comment by IrisBR** [comment]
Note de réunion :
Fait - les 4 livrables sont validé

**Comment by benel** [comment]
La correction est en production 🎉 

Bravo à l'équipe🏅
