### ISSUE TITLE
The building map should be disabled when empty

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#560]
#### What is the valuable outcome that cannot be achieved because of this bug?

With the building map extension enabled (visitMap: true), when a location is selected (spatial: xxxxx), items that correspond to the pattern /\w+ \d+/ are placed around the map according to the CNRS rules for numbering stain glasses in a church. 

But some items may have good reasons for not matching the pattern: for example, they are not necessarily in a church (e.g. `Société académique de l'Aube`, ` Musée de Vauluisant`).

#### For which stakeholder (people, role, project, domain) is it important?

To be defined.

#### Reproduction scenario

1. Open the `vitraux`portfolio.
2. Select `spatial: Société académique de l'Aube, Troyes`
3. The map is  "loading" endlessly.
 
<img width="914" alt="Capture d’écran 2022-02-22 à 11 54 20" src="https://user-images.githubusercontent.com/597307/155118711-e5095e02-43a3-4d19-9889-ac05091ad8e7.png">

#### Expected behavior

The default index should be shown instead.
<img width="914" alt="Capture d’écran 2022-02-22 à 11 54 55" src="https://user-images.githubusercontent.com/597307/155118445-8e9eb652-f130-4361-9ade-044df1750e57.png">

#### Environment
 - OS: [e.g. Windows 10, macOS 10.15, iOS]
 - Browser: [e.g. chrome 88, safari 14]

#### Workaround
Solution you found to avoid the problem.

#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

**Comment by maxime-huyghe** [comment]
The scenario and test are already done (portfolio_search.feature:5). The problem arises when we set the portfolio>vitraux>visitMap config value to true.

**Comment by maxime-huyghe** [comment]
# Stratégie d'implémentation

## Quelle partie du code sera impactée (classes, méthodes) ? Utilisez les React DevTools (extensions de Chrome ou Firefox) pour faire le lien entre la structure de la page et celle du code.

Le `Portfolio` sera impacté, car c'est lui qui définit les conditions d'affichage de la `VisitMap`.

## Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?

ø

## Les données dont vous avez besoin sont-elles déjà chargées par la page ?

Les données dont nous avons besoin (est-ce qu'un plan est présent) ne sont pas chargées par la page.

## Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?

ø

**Comment by benel** [comment]
Fixed by 2be6c217b8c1e94e599410f48f8693ef2210d4c3.
