### ISSUE TITLE
Document's attributes should be in a copyright

### ISSUE THREAD

**Issue by axelgcd** [Hypertopic/Porphyry#570]
### Description

The informations about de author and the date would be moved in a copyright under the picture. 

#### What is the valuable outcome that cannot be achieved because of this bug?

The user can see the more valuable informations quickly.

#### For which stakeholder (people, role, project, domain) is it important?

Important for users who are visiting.

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Implementation strategy

#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

**Comment by benel** [comment]
Good. Could you please rephrase the title with the required pattern (`<object> should be...`) for fixes?

For example: `Item page elements should be sorted according to...`.

**Comment by benel** [comment]
@Hypertopic/visite-sur-site-de-vitraux

**Comment by Couapy** [comment]
Maybe collapse the description block ?

**Comment by maxime-huyghe** [comment]
We need to modify the Item and Ressource components.

**Comment by maxime-huyghe** [comment]
We don't need to change any algorythm.

**Comment by maxime-huyghe** [comment]
We already have the necessary data, we only need to display it elsewhere.

**Comment by maxime-huyghe** [comment]
We don't need any external service.

**Comment by axelgcd** [comment]
Déplacer les information : date et auteur dans un copyright sous l'image

**Comment by benel** [comment]
This is only required for small displays, right?

**Comment by axelgcd** [comment]
Yes

**Comment by benel** [comment]
### Point d'avancement du 29/04

- Scénario : ajouter une étape disant que l'on est sur mobile.
- Stratégie de développement : vérifier après le développement que c'était effectivement assez simple.
- Tests de recette : prévoir une étape pour la consultation mobile.

**Comment by axelgcd** [comment]
Not as easy as we thought because we did not know how to detect the screen size. 
Every point completed

**Comment by IrisBR** [comment]
Note de réunion :
En cours - problème d'historique
Ancienne notion du ticket => modifier la formation de la page au format mobile
Perte de notion donc besoin de l'ajout d'un nouveau ticket qui demanderai de condenser l'affichage des topics au format mobile (feature).

**Comment by benel** [comment]
Fix in production. Well done 🎉

**Comment by benel** [comment]
Fix in production. Well done @Hypertopic/vitraux-de-troyes  🎉

**Comment by PaulHego** [comment]
Screen cast for navigation basics
Co authored by @Thomond5 

https://user-images.githubusercontent.com/75336237/171807822-9d299d44-f440-4b3a-a821-f676e5ab53e9.mp4

**Comment by maxime-huyghe** [comment]
I moved this to the doing column because it wasn't too difficult to implement but it's a very important feature for mobile browsing.
