### ISSUE TITLE
See the location of items on a Google Map

### ISSUE THREAD

**Issue by corentinprp51** [Hypertopic/Porphyry#571]
### Description
Allow users to read the exact location of items on a Google Map

**What is the valuable outcome that cannot be achieved with current features?**

**For which stakeholder (people, role, project, domain) is it important?**

**Which user action should be enabled (or restricted)? For who?**

**Additional details (solutions you think about, or workarounds you tried)**

### Deliverables status

**Phase 1**

- [ ]  Scenarios (Gherkin)
- [ ]  Mockups
- [ ]  Implementation strategy

**Phase 2**

- [ ]  Acceptance tests (Capybara)
- [ ]  Implementation

**Phase 3**

- [ ]  Screencast

**Comment by benel** [comment]
How is it different from the existing feature?

**Comment by corentinprp51** [comment]
> How is it different from the existing feature?

Il est vrai que ce ticket ressemble très fortement à celui-ci : https://github.com/Hypertopic/Porphyry/issues/272 dans notre cas
L'objectif étant la visualisation d'une map sur l'écran d'accueil où les différents items sont affichés en fonction de leur localisation exacte avec un layer permettant de réaliser le parcours archéologique (vu avec la partie prenante)

**Comment by benel** [comment]
> Il est vrai que ce ticket ressemble très fortement à celui-ci : https://github.com/Hypertopic/Porphyry/issues/272 dans notre cas

Si c'est le cas, @corentinprp51, vous pouvez fermer ce ticket et le retirer de votre projet. 
Par contre, même s'il ne s'agit pas d'une nouvelle fonctionnalité, il semblerait que ce soit un nouveau cas d'usage important à explorer. Continuons cette discussion dans votre espace.
