### ISSUE TITLE
Consult a viewpoint

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#58]
Here is a TODO list to achieve this:

- [x] Fetch a viewpoint and display its JSON (with **NodeJS**)
- [x] Create a hashmap of children indexed by fathers (with **NodeJS**)
- [x] Given a viewpoint URI, display the corresponding viewpoint as JSON in the HTML page (with **ReactJS**)
- [x] Given a viewpoint URI, display the corresponding viewpoint as an HTML list (with **ReactJS**)

**Comment by florianess** [comment]
```
var fetch = require('node-fetch')

//display the viewpoint "Histoire de l'art"

fetch('http://argos2.hypertopic.org/a76306e4f17ed4f79e7e481eb9a1bd06')
    .then(function(res) {
        return res.json();
    }).then(function(json) {

//Show only topics (not users)
        console.log(json.topics);
    }); 
```

**Comment by benel** [comment]
Hi @florianess,

Concerning your code above, you could use , instead of `fetch`, `db.get` from the [Hypertopic package](https://www.npmjs.com/package/hypertopic). For now there is not much difference. But it will get really useful when you begin to combine reads and updates.

Regards.

**Comment by florianess** [comment]
https://pastebin.com/nLbYe2GF
