### ISSUE TITLE
Delete a topic

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#59]
- [x] Scénarios 
- [x] Maquettes
- [x] Tests automatisés
- [x] Implémentation

**Comment by CorentinLthr** [comment]
- [ ] Scénarios
- [ ] Maquettes
- [ ] Tests automatisés
- [ ] Implémentation

**Comment by gumn** [comment]
Les maquettes ont été montrées aux parties prenantes en créant une vidéo à partir du site : https://checkvist.com/auth/index
