### ISSUE TITLE
The building map should remain active when a topic is selected

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#591]
#### What is the valuable outcome that cannot be achieved because of this bug?

Searching for a given topic inside a building.

#### For which stakeholder (people, role, project, domain) is it important?

@adrienfallot

#### Reproduction scenario

1. Go to "Saint-Jean-au-Marché" item page
2. Select "Personnages > NT > Jean le Baptiste"
3. The town map is show instead of the building map. 

<img width="400" alt="Capture d’écran 2022-04-22 à 16 19 32" src="https://user-images.githubusercontent.com/597307/164733411-060ec23e-948c-4a9a-b9b5-31f07728dcae.png">  <img width="400" alt="Capture d’écran 2022-04-22 à 16 19 17" src="https://user-images.githubusercontent.com/597307/164733457-f853ef81-e405-4170-a522-4dc34612a03b.png">

#### Expected behavior

The building map should stay and display the filtered items.

#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

**Comment by IrisBR** [comment]
Note de réunion :
Rajout au projet en cours car ticket plus important que "Search for a pattern in topics, attributes and attribute values"
active = reste afficher
Lorsque l'on recherche dans le bâtiment => la carte du batiment disparait et la map apparaît

**Comment by Couapy** [comment]
We are working on the scenario.

**Comment by Couapy** [comment]
![image](https://user-images.githubusercontent.com/39948565/167104918-732bd3be-7f07-4696-a560-99fb316e1d78.png)

**Comment by Couapy** [comment]
Nous avons créé le scénario suivant : 

```gherkin
Scénario: avec une recherche

Soit "vitraux" le portfolio ouvert
Soit "spatial : Église Saint-Jean-au-Marché, Troyes" la recherche actuelle
Soit "Personnages" une des rubriques développées
Soit "AT" une des rubriques développées
Quand on choisit la rubrique "Isaac"
Alors l'image item "SJ" est affichée
Et l'image item "SJ 001" est affichée
Mais l'image item "SJ 000" est cachée
Mais l'image item "SJ 100" est cachée
Mais l'image item "SJ 102" est cachée
Mais l'image item "SJ 002" est cachée
Mais l'image item "SJ 020" est cachée
```

**Comment by Couapy** [comment]
## Stratégie d'implémentation

### Quelle partie du code sera impactée (classes, méthodes) ? Utilisez les React DevTools (extensions de Chrome ou Firefox) pour faire le lien entre la structure de la page et celle du code.

Nous devrions probablement modifier [VisitMap](https://github.com/Hypertopic/Porphyry/tree/v7/src/components/portfolioPage/VisitMap.jsx) et [Portfolio](https://github.com/Hypertopic/Porphyry/tree/v7/src/components/portfolioPage/Portfolio.jsx)

### Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?

Cela dépendrade la complexité de VisitMap et de sa conception.

### Les données dont vous avez besoin sont-elles déjà chargées par la page ?

Il faut que le plan soit chargé, cependant si les critères de recherche ne correspondent pas, il ne peut être affiché.

**Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ?**

Je ne sais pas encore.

**Si non, quelle sera la requête la plus efficace et comment allez-vous récupérer dans la structure de données précisément celles qui vous intéressent ?**

On pourrait demander à récupérer l'objet carte s'il n'est pas chargé en faisant une requête supplémentaire.

**Existe-t-il des bibliothèques qui pourraient simplifier l'implémentation ? Quelles sont celles que vous choisiriez et pourquoi ?**

Non.

### Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? avec quels paramètres ?

Non plus.

**Comment by Couapy** [comment]
Co authered with @IrisBR and @Sandekuku 

https://user-images.githubusercontent.com/39948565/171810715-9c643359-a7d5-4c12-a704-88dae1738191.mp4
