### ISSUE TITLE
Consult item topics on mobile

### ISSUE THREAD

**Issue by LucasJeanpierre** [Hypertopic/Porphyry#595]
### Description
Condense the item's display to a mobile format

#### What is the valuable outcome that cannot be achieved with current features?
The user can see the more valuable information quickly

#### For which stakeholder (people, role, project, domain) is it important?
Important for users who are visiting

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy

#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

### Phase 3
- [x] Screencast

**Comment by IrisBR** [comment]
![Maquette](https://user-images.githubusercontent.com/72936212/167097469-ed7fd734-defe-473d-bb45-90f5ae3c9cf4.png)

**Comment by IrisBR** [comment]
Implementation strategy :
We will need to modify the Item and Ressource components.
We already have the necessary data, we only need to display it differently.
We don't need any external service.
This is only required for small displays, so we need to know how to detect the screen size.

**Comment by IrisBR** [comment]
Mockups : made with @LucasJeanpierre
![20220513_081352](https://user-images.githubusercontent.com/72936212/168222543-e22cfdc4-d061-46dc-a9a9-18c805d08ba5.jpg)
![20220513_081340](https://user-images.githubusercontent.com/72936212/168222526-3ce54c9d-0578-43f0-9038-4076fd0866bb.jpg)

**Comment by PaulHego** [comment]
Implementation strategy :
We will need to modify the Item component.
We already have the necessary data, we only need to display it differently.
We don't need any external service.
This is only required for small displays, so we need to know how to detect the screen size.

**Comment by IrisBR** [comment]
Maquette :
![image](https://user-images.githubusercontent.com/72936212/169478912-99a04cf7-5f7e-49d1-bb05-19407ede8b4d.png)
![image](https://user-images.githubusercontent.com/72936212/169478955-89c8ecb0-44a3-4a86-91b8-9836178a730b.png)
![image](https://user-images.githubusercontent.com/72936212/169478972-23ea84d4-00be-453b-b809-454a22e1ec29.png)

**Comment by maxime-huyghe** [comment]
implementation done

**Comment by maxime-huyghe** [comment]
I did a screencast with @LucasJeanpierre :

https://user-images.githubusercontent.com/65220804/171805293-dc405573-5867-4c50-8c1b-d5f8f876e2f8.mp4
