### ISSUE TITLE
Delete a viewpoint

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#60]
#### Additional details (solutions you think about, or workarounds you tried)

A workaround is to delete viewpoints through:
- CouchDB administration interface,
- Argos Rest API.

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy

#### Phase 2
- [x] Acceptance tests (Capybara)
- [x] Implementation

### Phase 3
- [x] Screencast

**Comment by Ciyax** [comment]
Par rapport aux viewpoints que nous avons définis dans le cadre du projet Studying abroad  : RIs, Etudiants, Universités, Responsable de Branche... sont-ils susceptibles d'évoluer au point qu'un d'entre eux devienne obsolète au point de le supprimer ?

**Comment by benel** [comment]
> sont-ils susceptibles d'évoluer au point qu'un d'entre eux devienne obsolète au point de le supprimer ?

Votre question semble suggérer que ça pourrait arriver mais que la probabilité est très faible.
Dans ce cas suggérez la fonctionnalité mais avec une priorité très basse, vous verrez bien si la partie prenante principale vous le confirme.

**Comment by SorelMboua** [comment]
For the group "Greek Vases", in my opinion, this is a very useful feature as the user can delete a viewpoint if he feels that it is no longer relevant.

**Comment by benel** [comment]
> delete a viewpoint if he feels that it is no longer relevant

@SorelMboua Such as an old or falsified theory?

**Comment by FirielEinor** [comment]
Visite sur site de vitraux :
Cette fonctionnalité est utile si l'on crée par erreur un point de vue, il faut pouvoir le supprimer.

**Comment by lildelfino** [comment]
Projet "graine d'artiste" : on a voulu tester la création de viewpoint et maintenant nous en avons un en trop. De plus la fonctionnalité pour aider les psychologues n'est pas forcément acquise, donc nous serons peut-être amenés à supprimer le pdv correspondant.

**Comment by benel** [comment]
@Hypertopic/graines-d-artistes-1 

Depuis 4 ans (date des débuts de la version 7 de Porphyry), personne n'a encore considéré la fonctionnalité Hypertopic/Porphyry#60 comme suffisamment prioritaire pour l'implémenter. C'est probablement parce que son usage est à la fois rare et risqué et que ce sont surtout les développeurs-testeurs qui en ont besoin (pour nettoyer leurs preuves de recette) or ceux-ci sont capables d'utiliser directement l'API (le service Web).

Comment faire ?

1. Dans Porphyry, éditez le point de vue à supprimer.
    <img width="388" alt="Capture d’écran 2021-03-18 à 20 24 08" src="https://user-images.githubusercontent.com/597307/111685275-ffb3af00-8827-11eb-95cd-64820e4401f8.png">
2. Copiez le dernier segment de l'URI (et collez le quelque part pour l'utiliser plus tard).
    <img width="605" alt="Capture d’écran 2021-03-18 à 20 26 36" src="https://user-images.githubusercontent.com/597307/111685547-55885700-8828-11eb-9998-d11c7b1d129b.png">
3. Installez un client REST, par exemple [celui-ci](https://addons.mozilla.org/fr/firefox/addon/restclient/) développé par un étudiant de l'UTT, dans Firefox.
4. Faites une requête GET avec cet identifiant sur le service Argos en production.
    <img width="984" alt="Capture d’écran 2021-03-18 à 20 42 52" src="https://user-images.githubusercontent.com/597307/111687459-95503e00-882a-11eb-8510-c414563b0cd3.png">
5. Dans la réponses, copiez le champ `ETag`.
    <img width="486" alt="Capture d’écran 2021-03-18 à 20 38 04" src="https://user-images.githubusercontent.com/597307/111687247-5b7f3780-882a-11eb-858f-50e9f582e23a.png">
6. Faites une requête DELETE avec l'identifiant dans l'URI et avec l'`ETag` en tant qu'entête `If-Match`.
    <img width="984" alt="Capture d’écran 2021-03-18 à 20 47 49" src="https://user-images.githubusercontent.com/597307/111687989-40f98e00-882b-11eb-9871-af37fb1570df.png">

**Comment by DariaSegalard** [comment]
Fonctionnalité : Supprimer un point de vue (#60 Delete a viewpoint)
https://github.com/orgs/Hypertopic/projects/36#card-78964464

Scénario :

```gherkin
Soit un utilisateur connecté
Et le point de vue “Céramique AF Motifs” est en mode édition
Et l’utilisateur souhaite modifier le point de vue “Céramique AF Motifs”
Quand l’utilisateur supprime le point de vue “Céramique AF Motifs”
Alors le point de vue “Céramique AF Motifs” ne fait plus partie du portfolio
```

Co-éditeurs : Simon G, Alexis S, Shir F, Daria S.

Maquette  :
![6 3 _ #60_delete_viewpoint_from_modification_du_point_de_vue_2](https://user-images.githubusercontent.com/57755204/161240241-d1f7e576-d48e-45fd-afca-0a89de749db0.jpg)

**Update :** Après concertation de l'équipe, mise à jour de la maquette pour correspondre à un choix d'implémentation différent :
![#60_Delete_a_viewpoint](https://user-images.githubusercontent.com/71147115/166225009-d991e9c4-047f-401f-a242-5c2f425b9e46.jpg)

**Comment by DariaSegalard** [comment]
# Stratégie d'implémentation

### Quelle partie du code sera impactée (classes, méthodes) ? 

Classe **Outliner** : 
- Ajout d'une méthode de suppression (par exemple "applyDelete()', sur le même modèle qu'"applyChange()".
- Ajout d'une balise HTML de bouton "Supprimer" dans le render() de la classe Outliner (en dessous de contributeur), pour appeler la méthode "applyDelete()".
- Gérer le renvoi de l'utilisateur sur la page d'accueil lorsque le point de vue est supprimé + message d'information.


### Y aura-t-il des difficultés d'un point de vue algorithmique ? Avez-vous des pistes pour les résoudre ?
Accéder à la base de données et supprimer des éléments au lieu de les modifier.
-> Piste de résolution : se baser sur les méthodes "applyChange()" et "_fetchData()". Reprendre les fonctions delete d'Hypertopic (suppression d'objets). Tester des bouts de code en se basant sur ces méthodes avant d'implémenter la nouvelle fonctionnalité.

### Les données dont vous avez besoin sont-elles déjà chargées par la page ?

Oui
**- Si oui, quelle est la structure des données et comment allez-vous récupérer précisément celles qui vous intéressent ?**
"id" du point de vue à supprimer (récupérable depuis le pathname)

**Existe-t-il des [bibliothèques](https://www.npmjs.com/) qui pourraient simplifier l'implémentation ? Quelles sont celles que vous choisiriez et pourquoi ?**
Nous pourrons reprendre le principe des fonctions delete d'Hypertopic (suppression d'objets).

### Doit-on intégrer des services extérieurs (ex : cartographie) ? De quelles fonctionnalités en particulier aura-t-on besoin ? Est-ce que le service choisi les propose ou doit-on passer chez un concurrent ? Comment s'utilisent ces fonctionnalités ? Avec quels paramètres ?
Non (hors Hypertopic pour la base de donnée).

_Co-éditeurs : Alexis S, Shir F, Daria S._

**Comment by benel** [comment]
### Point d'avancement du 29/04

- Maquette : ne correspond pas à ce que vous voulez faire.
- Stratégie de développement : Pour une autre fois, bien de tester des bouts de code.

**Comment by DariaSegalard** [comment]
## Démonstration du ticket https://github.com/Hypertopic/Porphyry/issues/60

Suite à l'implémentation de la suppression d'un point de vue, voici la vidéo de démonstration et d'illustration de cette nouvelle fonctionnalité. 

_L'utilisateur se rend sur la page d'édition du point de vue à supprimer.
Il clique sur le bouton "Supprimer" (ou "Delete" sur la version anglaise) et confirme son choix sur le pop-up. 
Le point de vue est alors définitivement supprimé du catalogue._

**Jeu de données :**
Portfolio : Vitraux.
Point de vue : Viewpoint to Delete.

_Co-éditeurs : Shir F, Daria S._

https://user-images.githubusercontent.com/71147115/168255931-b1d67929-948e-4077-81c1-5e4033451948.mp4

**Comment by benel** [comment]
Vous avez fait votre screencast avec la version anglaise de Porphyry. Est-ce intentionnel ?

**Comment by benel** [comment]
Félicitations @Hypertopic/vases-grecs-du-kerameikos , votre fonctionnalité est en production 🎉

**Comment by DariaSegalard** [comment]
> Vous avez fait votre screencast avec la version anglaise de Porphyry. Est-ce intentionnel ?

Oui, l'objectif était de montrer que la remarque sur l'absence de traduction pour cette fonctionnalité avait bien été prise en compte -> https://github.com/Hypertopic/Porphyry/pull/581#discussion_r871175828.
Nous pouvons cependant refaire la vidéo de démonstration de la fonctionnalité sur la version française de Porphyry, si vous préférez.

**Comment by benel** [comment]
> Nous pouvons cependant refaire la vidéo de démonstration de la fonctionnalité sur la version française de Porphyry, si vous préférez.

Ce n'est pas tant pour moi que pour vous : 
- vous en aurez besoin pour votre présentation finale,
- ça pourrait être une bonne idée de l'envoyer à votre partie prenante principale pour l'informer de l'avancée de votre projet.

**Comment by DariaSegalard** [comment]
Merci pour vos remarques :)

Voici donc la vidéo de démonstration et d'illustration de la fonctionnalité de suppression d'un point de vue, en français.

_L'utilisateur se rend sur la page d'édition du point de vue à supprimer.
Il clique sur le bouton "Supprimer" et confirme son choix sur le pop-up. 
Le point de vue est alors définitivement supprimé du catalogue._

**Jeu de données :**
Portfolio : Vitraux.
Point de vue : Point de vue à supprimer.

_Co-éditeurs : Shir F, Daria S._

https://user-images.githubusercontent.com/71147115/173028615-b9b7e095-f270-4964-a6de-f81cb4583aaa.mp4
