### ISSUE TITLE
Layout should be more mobile friendly on item page

### ISSUE THREAD

**Issue by Thomond5** [Hypertopic/Porphyry#603]
### Description
Remove margins on mobile
Remove not important infomation on mobile page 
Reorder the item on page.

#### For which stakeholder (people, role, project, domain) is it important?
This is crucial for mobile users.

#### Expected behavior
It's expected that the item page is clean with important information only.

#### Environment
 - OS: [e.g. Windows 10, macOS 10.15, iOS]
 - Browser: [e.g. chrome 88, safari 14]

#### Phase 1
- [x] Mock-up
- [x] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation

**Comment by Thomond5** [comment]
### Stratégie d'implementation 
made with @LucasJeanpierre 
**Quel partie du code sera impactée?**

Le dossier styles sera modifié.
Certain composant react seront(suprimé/modifié)

**Il n'y aura aucune difficulté algorythmique de prévu.**

**Il n'y aura pas besoin de donnée chargées par la page.**

**Il n'y a pas de service extérieure a intégrer.**

**Comment by IrisBR** [comment]
Maquette : (l'authentification est retirer en version mobile)
![image](https://user-images.githubusercontent.com/72936212/169479747-9ea9e561-4997-4748-be63-0c1430c4146c.png)
![image](https://user-images.githubusercontent.com/72936212/169478955-89c8ecb0-44a3-4a86-91b8-9836178a730b.png)
![image](https://user-images.githubusercontent.com/72936212/169479809-72078862-41fb-4558-adb4-f904bd3ec11a.png)
