### ISSUE TITLE
Display/close a topic

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#61]

**Comment by gumn** [comment]
L'implémentation du drag and drop de l'équipe vitraux donne cette possibilité, seulement il faudrait par défaut ne voir que les topics principaux (un voire deux niveaux).
Cf https://github.com/Hypertopic/Porphyry/pull/106

**Comment by benel** [comment]
@gumn La fonctionnalité proprement dite est implémentée. S'il y a besoin de la modifier (pour ne voir  au départ que certains niveaux), merci de créer un ticket spécifique.
