### ISSUE TITLE
Cache problem

### ISSUE THREAD

**Issue by chao** [Hypertopic/Porphyry#7]
I think you will need to clear the cache in HTTP PUT/POST/DELETE methods.

For example, when you issued a PUT request to modify a viewpoint on CouchDB, then you try to get this viewpoint immediately, you still will get the old data from cache if your listener cannot get the notification from CouchDB in time.

**Comment by benel** [comment]
The observer (outside the API) should indeed not update itself. The intended way to use the API is that the observer is updated when the observable (HypertopicMap) notifies it.

**Comment by chao** [comment]
Well, the problem is CouchDB might not be able to notify the observer in time (e.g. the network latency).

**Comment by benel** [comment]
For now, I prefer to trust CouchDB features.
If you see any latency noticeable by the user, feel free to reopen this ticket.

**Comment by chao** [comment]
I do have the issue cause by network latency.
In my objective C library, I wrote a test case to test my framework. However, sometime test case will get error and sometime not. 
For example:

viewpoint = corpus.createViewpoint('vp');
viewpoint.rename('new name');
name = viewpoint.getName();

However, here I still got 'vp' instead of 'new name'. Normally CouchDB should stream the notification to HypertopicMap simultaneously. I doubt it might be my router QoS function cause this issue.

You can close this issue, I will let you know more when I have more information.

**Comment by benel** [comment]
What I meant in my first comment is that in a real setting (not unit test), getName wouldn't be called synchronously after rename.

**Comment by benel** [comment]
But if it makes your unit tests pass, you can reset the client cache on POST/PUT/DELETE...
