### ISSUE TITLE
Interface avec typographie, couleur et mise en page améliorée

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#71]
- [x] Mise en place du framework Bootstrap
- [x] Mise en place de la nouvelle hiérarchisation des tailles de texte
- [x] Disposition des blocs de l'interface
- [x] Réorganisation du header + ajout de la barre de recherche
- [x] Modification/ajout des textes et présentations des titres de niveau 2 et 3
- [x] Modification des couleurs (background et police)
- [x] Ajout d'un lien de retour à l'accueil quand on est sur un item
- [x] Ajout de la possibilité de voir un item en pleine taille
- [x] Remettre les liens de la bonne couleur
- [x] Disposition des items dans la colonne de droite
- [x] Mettre en place les pills badges pour les compteurs d'items

**Comment by heliamagnan** [comment]
## Typography best practices

- Ideal body copy size : 16px
- Between 50 and 70 characters per line is optimal
- Line height : 1.5

### Text proportions :

![text size](https://user-images.githubusercontent.com/12372374/37775967-96ea10cc-2de4-11e8-8cc4-77943387a8ec.PNG)

### Ma contribution au sujet de la typographie

J'ai utilisé les proportions de taille de texte montrées ci-dessus. Je me suis ainsi affranchie des soucis de retour à la ligne qui perturbaient la bonne lecture des informations sur l'interface, tout en restant lisible sur des écrans de plus petite résolution.

Concernant le type de la police, j'ai fait le choix d'une sans-serif (sans les empattements aux extrémités des caractères) car de façon générale, il n'y a pas de paragraphes de textes dans l'interface. Dans ce cas, une police sans-serif est plus lisible.

**Comment by heliamagnan** [comment]
## Bootstrap ressources

- [Grid System](https://getbootstrap.com/docs/4.0/layout/grid/)

**Comment by heliamagnan** [comment]
## Colors

La principale modification que j'ai apporté aux niveau des couleurs utilisées dans Porphyry, est le changement du marron du header en rouge foncé. 

- Ancien marron : `#993300`
- Rouge foncé : `#8b0000`

Le choix de cette couleur réside dans l'idée de moderniser l'interface, mais également permettre un meilleur accord entre les autres couleurs utilisées dans l'interface et une meilleure mise en valeur du logo :

![logo](https://user-images.githubusercontent.com/12372374/39270108-45efcc6e-48d5-11e8-8a26-5e0218719ac2.PNG)

Concernant les autres couleurs de l'interface, j'ai gardé le gris clair et le gris foncé que l'on peut retrouver dans respectivement dans le bandeau affichant le corpus et le header.

- Gris clair `#696969`
- Gris foncé `#3c3232`

J'ai également conservé le blanc du fond des deux colonnes principales de la page.

- Blanc `#ffffff`

Et pour mettre en valeur ce blanc des colonnes (les colonnes vont perdre leurs contours dans une question de modernisation de Porphyry, je renvoie au commentaire sur la disposition de l'interface), j'ai choisi une couleur de fond à peine moins claire, tirant sur le bleu, contrastant avec le rouge et s'accordant aussi bien avec les gris.

- Bleu clair : `#e6ecf0`

Concernant les différents textes présents dans l'interface, ils seront de couleurs noires ou blanches selon le contraste (un texte blanc ira mieux sur un fond gris, mais sera illisible sur un fond trop clair par exemple), ou gris pour les textes secondaires (comme le "Rechercher... dans la barre de recherche).

**Comment by heliamagnan** [comment]
## Disposition de l'interface

###  Vue d'ensemble de l'accueil 

![accueil](https://user-images.githubusercontent.com/12372374/39291068-0bd9d26a-4932-11e8-9306-b4bd8fbb632a.PNG)

De façon générale, nous avons un header et deux colonnes. La symétrie des éléments a été l'objet d'un soin particulier. L'effet "tableau" que connaissait l'ancienne interface a été supprimé de façon à moderniser Porphyry.

### Header

Pour ma contribution à l'amélioration de l'interface, j'ai réalisé des modifications au niveau du header. On peut constater un changement de disposition des éléments à l'intérieur : 

![header](https://user-images.githubusercontent.com/12372374/39271317-05b0d842-48d9-11e8-916d-173e67a17474.PNG)

Le logo de Porphyry passe à gauche. J'explique ce choix par la volonté de mettre en avant l'outil sans pour autant mettre dans l'ombre le sujet du portfolio qui est, dans le cas utilisé pour ma maquette, "VITRAUX" (et surtout le gros titre en taille 48 de l'interface, il serai difficile de le rater).

Aussi, une barre de recherche à fait son apparition. Élément incontournable d'un site web, les tendances actuelles font qu'elle se place souvent directement à droite du logo, dans le header. Ses fonctionnalités seront implémentées dans le cadre de l'UE IF05.

Enfin, pas de modifications concernant le bandeau gris foncé, qui précisera ce qui est affiché dans l'interface.

### Colonne de gauche (points de vue)

![colone de gauche](https://user-images.githubusercontent.com/12372374/39291200-7c2f805a-4932-11e8-8e7d-6eb45da3e740.PNG)

Pour la colonne de gauche, il ne s'agit plus des points de vue qui se trouvent dans le bandeau de couleur en haut de la colonne, mais du label "Points de vue", clarifiant la fonctionnalité de la colonne. Les points de vue sont désormais représentés comme des titres de second niveau, délimités par de sobres lignes grises clair très utilisées dans les sites désignés avec bootstrap.

À l'origine, j'avais pris en compte dans ma maquette les fonctionnalités pour déplier et replier des catégories. Cette fonctionnalité a été implémentée tout récemment dans Porphyry.

On peut aussi constater la présence du nombre d'item par catégorie entre parenthèses. Dans l'implémentation réelle, ces nombres seront représentés dans des "pill badges" propres à bootstrap.

### Colonne de droite (corpus)

![colone de droite](https://user-images.githubusercontent.com/12372374/39293465-3b72cffc-4939-11e8-93fb-eaeb19fe7811.PNG)

Pour la colonne de droite, peu de changements, le corpus est le label de cette colonne. Les éléments dans la colonne ont été centrés pour une question de symétrie. Je serai amenée encore à réfléchir à la taille de ces éléments.

D'un point de vue d'optimisation du temps de chargement de l'interface, un chargement progressif au fil du défilement pourrait être envisageable. La pagination par contre n'est pas envisageable dans un soucis de "vue globale" de tous les éléments.

### Vue d'ensemble de la page d'un item

![item](https://user-images.githubusercontent.com/12372374/39298517-b657dafc-4946-11e8-8c4c-c26494cb1cc2.PNG)

Pour la page propre à un item, à l'origine, c'était le nom de l'item qui figurait à la place de l'actuel "VITRAUX". Pour un soucis de cohérence, j'ai préféré remettre "VITRAUX" comme sur la page d'accueil pour bien garder à l'idée le portfolio sur lequel on se trouve. Le nom de l'item prend désormais place comme label de la colonne de droite.

De façon générale, on peut aussi constater que les colonnes ont des tailles fixes, ce qui permet qu'une colonne prédomine sur l'autre, perturbant ainsi la lisibilité des information.

### Colonne de gauche (information)

![cgaucheitem](https://user-images.githubusercontent.com/12372374/39298399-5d4dee7e-4946-11e8-9f0d-a220d30a751b.PNG)

Tout comme la colonne de gauche sur la page d'accueil, j'ai créé un label fixe pour cette colonne : "Informations". En suite les titres de second niveaux sont présentés également comme sur la page d'accueil. Nous y retrouvons dans l'ordre les attributs généraux du document, et les points de vue.

La mise en gras de la valeur d'un label permet de se concentrer sur le contenu. Ceci a été conservé de l'ancienne interface. Également concernant les attributs du document, ils sont alignés par rapport aux deux points séparant le label de la valeur. 

Comme expliqué dans le commentaire sur la typographie, la réorganisation des tailles de texte permet aux fils d’Ariane des points de vue d'être plus lisible et de tenir généralement sur une ligne.

### Colonne de droite (item)

![cdroiteitem](https://user-images.githubusercontent.com/12372374/39297395-b07de944-4943-11e8-8e05-ab5338148cbf.PNG)

La colonne de droite affiche "concrètement" l'item. AInsi le label sera le nom de l'item, qui à l'origine se trouvait en gros titre. Pour la cohérence, il trouve mieux sa place au dessus de l'item directement.

L'item, dans le cas d'un item de type image, disposera d'une taille suffisante pour être analysable sans être en pleine taille. Mais également, la possibilité de voir l'item en pleine taille se fera par le lien "Voir l'image en taille réelle". Cela nous permettra un scroll vertical et horizontal exceptionnellement pour justement avoir accès à tous les détails de l'image sans déformer (cad. réduction de la colonne de gauche) l'interface.
