### ISSUE TITLE
Download the article attachment

### ISSUE THREAD

**Issue by heliamagnan** [Hypertopic/Porphyry#95]
- [x] (Prérequis) Mise en place d'un système de configuration de l'affichage d'item
- [x] Affichage de l'abstract de l'article
- [ ] Ajout d'un bouton permettant de télécharger le fichier attaché

**Comment by gnoxr** [comment]
Voir la proposition [Modes d'affichage des items][1].

[1]: https://github.com/orgs/Hypertopic/teams/porphyry/discussions/3

**Comment by gumn** [comment]
Could be linked to the need, for Cité du Vitrail, to download the photo and item's atributes (and topics)
As for the portfolio view, we could set up different way of downloading following portfolios.
As for "vitraux", the resolution of the picture could be chosen at download.

**Comment by benel** [comment]
Closed for now because it was phrased as related to an ancient project.

@gumn Because your feature is different, I created a new feature request (#153). Please comment it if you have more details.
